/* GENERATED by dxvk-ppc64le/thunk/gen_winecom.py -- do not edit.
 *
 * Native-lane COM marshal tables for the d3d12 surface, from
 * interfaces_d3d12.json (117 interfaces).  Interface order is sorted
 * by name -- the same order spec2thunk COM mode gives the guest
 * module's stub arrays, and the runtime cross-checks the IIDs at
 * attach so the two cannot silently disagree.
 */

/* argument classes: cls[i] describes parameter i AFTER `this` */
#define CA_PASS          0
#define CA_IFACE_IN      1
#define CA_RIID          2
#define CA_PPV_OUT       3
#define CA_RET_PTR       4
#define CA_EVENT         5
#define CA_IFACE_ARR_IN  6

#define COMF_RET_VOID    1  /* method returns void */
#define COMF_RET_VIA_ARG 2  /* sret: RAX = the __ret argument */
#define COMF_HAND        4  /* served by d3d12_hand_funcs[aux] */

struct d3d12_com_slot
{
    const char *name;
    const char *refuse;        /* non-NULL: log once, E_NOTIMPL */
    const unsigned char *cls;  /* argc-1 classes; NULL = all CA_PASS */
    unsigned char argc;        /* including `this` */
    unsigned char flags;
    unsigned char aux;         /* CA_PPV_OUT: its RIID param index;
                                  COMF_HAND: hand function index */
    unsigned char aux2;        /* CA_IFACE_ARR_IN: count param index */
};

struct d3d12_com_iface
{
    const char *name;
    GUID iid;
    UINT slot_count;
    const struct d3d12_com_slot *slots; /* NULL: IUnknown slots only,
                                           the rest refused (step 7) */
};

enum d3d12_iface_index
{
    D3D12_IFACE_ID3D10Blob = 0,
    D3D12_IFACE_ID3D12ApplicationIdentity = 1,
    D3D12_IFACE_ID3D12CommandAllocator = 2,
    D3D12_IFACE_ID3D12CommandList = 3,
    D3D12_IFACE_ID3D12CommandQueue = 4,
    D3D12_IFACE_ID3D12CommandSignature = 5,
    D3D12_IFACE_ID3D12DescriptorHeap = 6,
    D3D12_IFACE_ID3D12Device = 7,
    D3D12_IFACE_ID3D12Device1 = 8,
    D3D12_IFACE_ID3D12Device10 = 9,
    D3D12_IFACE_ID3D12Device11 = 10,
    D3D12_IFACE_ID3D12Device12 = 11,
    D3D12_IFACE_ID3D12Device13 = 12,
    D3D12_IFACE_ID3D12Device14 = 13,
    D3D12_IFACE_ID3D12Device15 = 14,
    D3D12_IFACE_ID3D12Device2 = 15,
    D3D12_IFACE_ID3D12Device3 = 16,
    D3D12_IFACE_ID3D12Device4 = 17,
    D3D12_IFACE_ID3D12Device5 = 18,
    D3D12_IFACE_ID3D12Device6 = 19,
    D3D12_IFACE_ID3D12Device7 = 20,
    D3D12_IFACE_ID3D12Device8 = 21,
    D3D12_IFACE_ID3D12Device9 = 22,
    D3D12_IFACE_ID3D12DeviceChild = 23,
    D3D12_IFACE_ID3D12DeviceConfiguration = 24,
    D3D12_IFACE_ID3D12DeviceConfiguration1 = 25,
    D3D12_IFACE_ID3D12DeviceFactory = 26,
    D3D12_IFACE_ID3D12DeviceRemovedExtendedData = 27,
    D3D12_IFACE_ID3D12DeviceRemovedExtendedDataSettings = 28,
    D3D12_IFACE_ID3D12DeviceRemovedExtendedDataSettings1 = 29,
    D3D12_IFACE_ID3D12DeviceRemovedExtendedDataSettings2 = 30,
    D3D12_IFACE_ID3D12Fence = 31,
    D3D12_IFACE_ID3D12Fence1 = 32,
    D3D12_IFACE_ID3D12GraphicsCommandList = 33,
    D3D12_IFACE_ID3D12GraphicsCommandList1 = 34,
    D3D12_IFACE_ID3D12GraphicsCommandList10 = 35,
    D3D12_IFACE_ID3D12GraphicsCommandList2 = 36,
    D3D12_IFACE_ID3D12GraphicsCommandList3 = 37,
    D3D12_IFACE_ID3D12GraphicsCommandList4 = 38,
    D3D12_IFACE_ID3D12GraphicsCommandList5 = 39,
    D3D12_IFACE_ID3D12GraphicsCommandList6 = 40,
    D3D12_IFACE_ID3D12GraphicsCommandList7 = 41,
    D3D12_IFACE_ID3D12GraphicsCommandList8 = 42,
    D3D12_IFACE_ID3D12GraphicsCommandList9 = 43,
    D3D12_IFACE_ID3D12Heap = 44,
    D3D12_IFACE_ID3D12Heap1 = 45,
    D3D12_IFACE_ID3D12LifetimeOwner = 46,
    D3D12_IFACE_ID3D12LifetimeTracker = 47,
    D3D12_IFACE_ID3D12MetaCommand = 48,
    D3D12_IFACE_ID3D12Object = 49,
    D3D12_IFACE_ID3D12Pageable = 50,
    D3D12_IFACE_ID3D12PipelineLibrary = 51,
    D3D12_IFACE_ID3D12PipelineLibrary1 = 52,
    D3D12_IFACE_ID3D12PipelineState = 53,
    D3D12_IFACE_ID3D12ProtectedResourceSession = 54,
    D3D12_IFACE_ID3D12ProtectedResourceSession1 = 55,
    D3D12_IFACE_ID3D12ProtectedSession = 56,
    D3D12_IFACE_ID3D12QueryHeap = 57,
    D3D12_IFACE_ID3D12Resource = 58,
    D3D12_IFACE_ID3D12Resource1 = 59,
    D3D12_IFACE_ID3D12Resource2 = 60,
    D3D12_IFACE_ID3D12RootSignature = 61,
    D3D12_IFACE_ID3D12RootSignatureDeserializer = 62,
    D3D12_IFACE_ID3D12SDKConfiguration = 63,
    D3D12_IFACE_ID3D12SDKConfiguration1 = 64,
    D3D12_IFACE_ID3D12StateObject = 65,
    D3D12_IFACE_ID3D12StateObjectProperties = 66,
    D3D12_IFACE_ID3D12StateObjectProperties1 = 67,
    D3D12_IFACE_ID3D12SwapChainAssistant = 68,
    D3D12_IFACE_ID3D12Tools = 69,
    D3D12_IFACE_ID3D12VersionedRootSignatureDeserializer = 70,
    D3D12_IFACE_ID3D12WorkGraphProperties = 71,
    D3D12_IFACE_ID3DDestructionNotifier = 72,
    D3D12_IFACE_IDXGIAdapter = 73,
    D3D12_IFACE_IDXGIAdapter1 = 74,
    D3D12_IFACE_IDXGIAdapter2 = 75,
    D3D12_IFACE_IDXGIAdapter3 = 76,
    D3D12_IFACE_IDXGIAdapter4 = 77,
    D3D12_IFACE_IDXGIDecodeSwapChain = 78,
    D3D12_IFACE_IDXGIDevice = 79,
    D3D12_IFACE_IDXGIDevice1 = 80,
    D3D12_IFACE_IDXGIDevice2 = 81,
    D3D12_IFACE_IDXGIDevice3 = 82,
    D3D12_IFACE_IDXGIDevice4 = 83,
    D3D12_IFACE_IDXGIDeviceSubObject = 84,
    D3D12_IFACE_IDXGIDisplayControl = 85,
    D3D12_IFACE_IDXGIFactory = 86,
    D3D12_IFACE_IDXGIFactory1 = 87,
    D3D12_IFACE_IDXGIFactory2 = 88,
    D3D12_IFACE_IDXGIFactory3 = 89,
    D3D12_IFACE_IDXGIFactory4 = 90,
    D3D12_IFACE_IDXGIFactory5 = 91,
    D3D12_IFACE_IDXGIFactory6 = 92,
    D3D12_IFACE_IDXGIFactory7 = 93,
    D3D12_IFACE_IDXGIFactoryMedia = 94,
    D3D12_IFACE_IDXGIKeyedMutex = 95,
    D3D12_IFACE_IDXGIObject = 96,
    D3D12_IFACE_IDXGIOutput = 97,
    D3D12_IFACE_IDXGIOutput1 = 98,
    D3D12_IFACE_IDXGIOutput2 = 99,
    D3D12_IFACE_IDXGIOutput3 = 100,
    D3D12_IFACE_IDXGIOutput4 = 101,
    D3D12_IFACE_IDXGIOutput5 = 102,
    D3D12_IFACE_IDXGIOutput6 = 103,
    D3D12_IFACE_IDXGIOutputDuplication = 104,
    D3D12_IFACE_IDXGIResource = 105,
    D3D12_IFACE_IDXGIResource1 = 106,
    D3D12_IFACE_IDXGISurface = 107,
    D3D12_IFACE_IDXGISurface1 = 108,
    D3D12_IFACE_IDXGISurface2 = 109,
    D3D12_IFACE_IDXGISwapChain = 110,
    D3D12_IFACE_IDXGISwapChain1 = 111,
    D3D12_IFACE_IDXGISwapChain2 = 112,
    D3D12_IFACE_IDXGISwapChain3 = 113,
    D3D12_IFACE_IDXGISwapChain4 = 114,
    D3D12_IFACE_IDXGISwapChainMedia = 115,
    D3D12_IFACE_IUnknown = 116,
    D3D12_IFACE_COUNT = 117
};

#define D3D12_HAND_COUNT 2

static const struct d3d12_com_slot slots_ID3D10Blob[5] =
{
    { "IUnknown::QueryInterface", NULL, NULL, 3, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "ID3D10Blob::GetBufferPointer", NULL, NULL, 1, 0, 0, 0 },
    { "ID3D10Blob::GetBufferSize", NULL, NULL, 1, 0, 0, 0 },
};

static const unsigned char cls_ID3D12CommandAllocator_5[] = { CA_PASS, CA_IFACE_IN };
static const unsigned char cls_ID3D12CommandAllocator_7[] = { CA_RIID, CA_PPV_OUT };
static const struct d3d12_com_slot slots_ID3D12CommandAllocator[9] =
{
    { "IUnknown::QueryInterface", NULL, NULL, 3, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "ID3D12Object::GetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateDataInterface", NULL, cls_ID3D12CommandAllocator_5, 3, 0, 0, 0 },
    { "ID3D12Object::SetName", NULL, NULL, 2, 0, 0, 0 },
    { "ID3D12DeviceChild::GetDevice", NULL, cls_ID3D12CommandAllocator_7, 3, 0, 0, 0 },
    { "ID3D12CommandAllocator::Reset", NULL, NULL, 1, 0, 0, 0 },
};

static const unsigned char cls_ID3D12CommandList_5[] = { CA_PASS, CA_IFACE_IN };
static const unsigned char cls_ID3D12CommandList_7[] = { CA_RIID, CA_PPV_OUT };
static const struct d3d12_com_slot slots_ID3D12CommandList[9] =
{
    { "IUnknown::QueryInterface", NULL, NULL, 3, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "ID3D12Object::GetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateDataInterface", NULL, cls_ID3D12CommandList_5, 3, 0, 0, 0 },
    { "ID3D12Object::SetName", NULL, NULL, 2, 0, 0, 0 },
    { "ID3D12DeviceChild::GetDevice", NULL, cls_ID3D12CommandList_7, 3, 0, 0, 0 },
    { "ID3D12CommandList::GetType", NULL, NULL, 1, 0, 0, 0 },
};

static const unsigned char cls_ID3D12CommandQueue_5[] = { CA_PASS, CA_IFACE_IN };
static const unsigned char cls_ID3D12CommandQueue_7[] = { CA_RIID, CA_PPV_OUT };
static const unsigned char cls_ID3D12CommandQueue_8[] = { CA_IFACE_IN, CA_PASS, CA_PASS, CA_PASS, CA_IFACE_IN, CA_PASS, CA_PASS, CA_PASS, CA_PASS, CA_PASS };
static const unsigned char cls_ID3D12CommandQueue_9[] = { CA_IFACE_IN, CA_PASS, CA_IFACE_IN, CA_PASS, CA_PASS, CA_PASS };
static const unsigned char cls_ID3D12CommandQueue_10[] = { CA_PASS, CA_IFACE_ARR_IN };
static const unsigned char cls_ID3D12CommandQueue_14[] = { CA_IFACE_IN, CA_PASS };
static const unsigned char cls_ID3D12CommandQueue_15[] = { CA_IFACE_IN, CA_PASS };
static const unsigned char cls_ID3D12CommandQueue_18[] = { CA_RET_PTR };
static const struct d3d12_com_slot slots_ID3D12CommandQueue[19] =
{
    { "IUnknown::QueryInterface", NULL, NULL, 3, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "ID3D12Object::GetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateDataInterface", NULL, cls_ID3D12CommandQueue_5, 3, 0, 0, 0 },
    { "ID3D12Object::SetName", NULL, NULL, 2, 0, 0, 0 },
    { "ID3D12DeviceChild::GetDevice", NULL, cls_ID3D12CommandQueue_7, 3, 0, 0, 0 },
    { "ID3D12CommandQueue::UpdateTileMappings", NULL, cls_ID3D12CommandQueue_8, 11, 1, 0, 0 },
    { "ID3D12CommandQueue::CopyTileMappings", NULL, cls_ID3D12CommandQueue_9, 7, 1, 0, 0 },
    { "ID3D12CommandQueue::ExecuteCommandLists", NULL, cls_ID3D12CommandQueue_10, 3, 1, 0, 0 },
    { "ID3D12CommandQueue::SetMarker", NULL, NULL, 4, 1, 0, 0 },
    { "ID3D12CommandQueue::BeginEvent", NULL, NULL, 4, 1, 0, 0 },
    { "ID3D12CommandQueue::EndEvent", NULL, NULL, 1, 1, 0, 0 },
    { "ID3D12CommandQueue::Signal", NULL, cls_ID3D12CommandQueue_14, 3, 0, 0, 0 },
    { "ID3D12CommandQueue::Wait", NULL, cls_ID3D12CommandQueue_15, 3, 0, 0, 0 },
    { "ID3D12CommandQueue::GetTimestampFrequency", NULL, NULL, 2, 0, 0, 0 },
    { "ID3D12CommandQueue::GetClockCalibration", NULL, NULL, 3, 0, 0, 0 },
    { "ID3D12CommandQueue::GetDesc", NULL, cls_ID3D12CommandQueue_18, 2, 2, 0, 0 },
};

static const unsigned char cls_ID3D12DescriptorHeap_5[] = { CA_PASS, CA_IFACE_IN };
static const unsigned char cls_ID3D12DescriptorHeap_7[] = { CA_RIID, CA_PPV_OUT };
static const unsigned char cls_ID3D12DescriptorHeap_8[] = { CA_RET_PTR };
static const unsigned char cls_ID3D12DescriptorHeap_9[] = { CA_RET_PTR };
static const unsigned char cls_ID3D12DescriptorHeap_10[] = { CA_RET_PTR };
static const struct d3d12_com_slot slots_ID3D12DescriptorHeap[11] =
{
    { "IUnknown::QueryInterface", NULL, NULL, 3, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "ID3D12Object::GetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateDataInterface", NULL, cls_ID3D12DescriptorHeap_5, 3, 0, 0, 0 },
    { "ID3D12Object::SetName", NULL, NULL, 2, 0, 0, 0 },
    { "ID3D12DeviceChild::GetDevice", NULL, cls_ID3D12DescriptorHeap_7, 3, 0, 0, 0 },
    { "ID3D12DescriptorHeap::GetDesc", NULL, cls_ID3D12DescriptorHeap_8, 2, 2, 0, 0 },
    { "ID3D12DescriptorHeap::GetCPUDescriptorHandleForHeapStart", NULL, cls_ID3D12DescriptorHeap_9, 2, 2, 0, 0 },
    { "ID3D12DescriptorHeap::GetGPUDescriptorHandleForHeapStart", NULL, cls_ID3D12DescriptorHeap_10, 2, 2, 0, 0 },
};

static const unsigned char cls_ID3D12Device_5[] = { CA_PASS, CA_IFACE_IN };
static const unsigned char cls_ID3D12Device_8[] = { CA_PASS, CA_RIID, CA_PPV_OUT };
static const unsigned char cls_ID3D12Device_9[] = { CA_PASS, CA_RIID, CA_PPV_OUT };
static const unsigned char cls_ID3D12Device_12[] = { CA_PASS, CA_PASS, CA_IFACE_IN, CA_IFACE_IN, CA_RIID, CA_PPV_OUT };
static const unsigned char cls_ID3D12Device_14[] = { CA_PASS, CA_RIID, CA_PPV_OUT };
static const unsigned char cls_ID3D12Device_16[] = { CA_PASS, CA_PASS, CA_PASS, CA_RIID, CA_PPV_OUT };
static const unsigned char cls_ID3D12Device_18[] = { CA_IFACE_IN, CA_PASS, CA_PASS };
static const unsigned char cls_ID3D12Device_19[] = { CA_IFACE_IN, CA_IFACE_IN, CA_PASS, CA_PASS };
static const unsigned char cls_ID3D12Device_20[] = { CA_IFACE_IN, CA_PASS, CA_PASS };
static const unsigned char cls_ID3D12Device_21[] = { CA_IFACE_IN, CA_PASS, CA_PASS };
static const unsigned char cls_ID3D12Device_25[] = { CA_RET_PTR, CA_PASS, CA_PASS, CA_PASS };
static const unsigned char cls_ID3D12Device_26[] = { CA_RET_PTR, CA_PASS, CA_PASS };
static const unsigned char cls_ID3D12Device_27[] = { CA_PASS, CA_PASS, CA_PASS, CA_PASS, CA_PASS, CA_RIID, CA_PPV_OUT };
static const unsigned char cls_ID3D12Device_28[] = { CA_PASS, CA_RIID, CA_PPV_OUT };
static const unsigned char cls_ID3D12Device_29[] = { CA_IFACE_IN, CA_PASS, CA_PASS, CA_PASS, CA_PASS, CA_RIID, CA_PPV_OUT };
static const unsigned char cls_ID3D12Device_30[] = { CA_PASS, CA_PASS, CA_PASS, CA_RIID, CA_PPV_OUT };
static const unsigned char cls_ID3D12Device_31[] = { CA_IFACE_IN, CA_PASS, CA_PASS, CA_PASS, CA_PASS };
static const unsigned char cls_ID3D12Device_32[] = { CA_PASS, CA_RIID, CA_PPV_OUT };
static const unsigned char cls_ID3D12Device_34[] = { CA_PASS, CA_IFACE_ARR_IN };
static const unsigned char cls_ID3D12Device_35[] = { CA_PASS, CA_IFACE_ARR_IN };
static const unsigned char cls_ID3D12Device_36[] = { CA_PASS, CA_PASS, CA_RIID, CA_PPV_OUT };
static const unsigned char cls_ID3D12Device_39[] = { CA_PASS, CA_RIID, CA_PPV_OUT };
static const unsigned char cls_ID3D12Device_41[] = { CA_PASS, CA_IFACE_IN, CA_RIID, CA_PPV_OUT };
static const unsigned char cls_ID3D12Device_42[] = { CA_IFACE_IN, CA_PASS, CA_PASS, CA_PASS, CA_PASS, CA_PASS, CA_PASS };
static const unsigned char cls_ID3D12Device_43[] = { CA_RET_PTR };
static const struct d3d12_com_slot slots_ID3D12Device[44] =
{
    { "IUnknown::QueryInterface", NULL, NULL, 3, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "ID3D12Object::GetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateDataInterface", NULL, cls_ID3D12Device_5, 3, 0, 0, 0 },
    { "ID3D12Object::SetName", NULL, NULL, 2, 0, 0, 0 },
    { "ID3D12Device::GetNodeCount", NULL, NULL, 1, 0, 0, 0 },
    { "ID3D12Device::CreateCommandQueue", NULL, cls_ID3D12Device_8, 4, 0, 1, 0 },
    { "ID3D12Device::CreateCommandAllocator", NULL, cls_ID3D12Device_9, 4, 0, 1, 0 },
    { "ID3D12Device::CreateGraphicsPipelineState",
      "ID3D12Device::CreateGraphicsPipelineState: D3D12_GRAPHICS_PIPELINE_STATE_DESC carries interface pointers inside a struct and has no hand-written walker yet",
      NULL, 4, 0, 0, 0 },
    { "ID3D12Device::CreateComputePipelineState", NULL, NULL, 4, 4, 1, 0 },
    { "ID3D12Device::CreateCommandList", NULL, cls_ID3D12Device_12, 7, 0, 4, 0 },
    { "ID3D12Device::CheckFeatureSupport", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Device::CreateDescriptorHeap", NULL, cls_ID3D12Device_14, 4, 0, 1, 0 },
    { "ID3D12Device::GetDescriptorHandleIncrementSize", NULL, NULL, 2, 0, 0, 0 },
    { "ID3D12Device::CreateRootSignature", NULL, cls_ID3D12Device_16, 6, 0, 3, 0 },
    { "ID3D12Device::CreateConstantBufferView", NULL, NULL, 3, 1, 0, 0 },
    { "ID3D12Device::CreateShaderResourceView", NULL, cls_ID3D12Device_18, 4, 1, 0, 0 },
    { "ID3D12Device::CreateUnorderedAccessView", NULL, cls_ID3D12Device_19, 5, 1, 0, 0 },
    { "ID3D12Device::CreateRenderTargetView", NULL, cls_ID3D12Device_20, 4, 1, 0, 0 },
    { "ID3D12Device::CreateDepthStencilView", NULL, cls_ID3D12Device_21, 4, 1, 0, 0 },
    { "ID3D12Device::CreateSampler", NULL, NULL, 3, 1, 0, 0 },
    { "ID3D12Device::CopyDescriptors", NULL, NULL, 8, 1, 0, 0 },
    { "ID3D12Device::CopyDescriptorsSimple", NULL, NULL, 5, 1, 0, 0 },
    { "ID3D12Device::GetResourceAllocationInfo", NULL, cls_ID3D12Device_25, 5, 2, 0, 0 },
    { "ID3D12Device::GetCustomHeapProperties", NULL, cls_ID3D12Device_26, 4, 2, 0, 0 },
    { "ID3D12Device::CreateCommittedResource", NULL, cls_ID3D12Device_27, 8, 0, 5, 0 },
    { "ID3D12Device::CreateHeap", NULL, cls_ID3D12Device_28, 4, 0, 1, 0 },
    { "ID3D12Device::CreatePlacedResource", NULL, cls_ID3D12Device_29, 8, 0, 5, 0 },
    { "ID3D12Device::CreateReservedResource", NULL, cls_ID3D12Device_30, 6, 0, 3, 0 },
    { "ID3D12Device::CreateSharedHandle", NULL, cls_ID3D12Device_31, 6, 0, 0, 0 },
    { "ID3D12Device::OpenSharedHandle", NULL, cls_ID3D12Device_32, 4, 0, 1, 0 },
    { "ID3D12Device::OpenSharedHandleByName", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Device::MakeResident", NULL, cls_ID3D12Device_34, 3, 0, 0, 0 },
    { "ID3D12Device::Evict", NULL, cls_ID3D12Device_35, 3, 0, 0, 0 },
    { "ID3D12Device::CreateFence", NULL, cls_ID3D12Device_36, 5, 0, 2, 0 },
    { "ID3D12Device::GetDeviceRemovedReason", NULL, NULL, 1, 0, 0, 0 },
    { "ID3D12Device::GetCopyableFootprints", NULL, NULL, 9, 1, 0, 0 },
    { "ID3D12Device::CreateQueryHeap", NULL, cls_ID3D12Device_39, 4, 0, 1, 0 },
    { "ID3D12Device::SetStablePowerState", NULL, NULL, 2, 0, 0, 0 },
    { "ID3D12Device::CreateCommandSignature", NULL, cls_ID3D12Device_41, 5, 0, 2, 0 },
    { "ID3D12Device::GetResourceTiling", NULL, cls_ID3D12Device_42, 8, 1, 0, 0 },
    { "ID3D12Device::GetAdapterLuid", NULL, cls_ID3D12Device_43, 2, 2, 0, 0 },
};

static const unsigned char cls_ID3D12DeviceChild_5[] = { CA_PASS, CA_IFACE_IN };
static const unsigned char cls_ID3D12DeviceChild_7[] = { CA_RIID, CA_PPV_OUT };
static const struct d3d12_com_slot slots_ID3D12DeviceChild[8] =
{
    { "IUnknown::QueryInterface", NULL, NULL, 3, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "ID3D12Object::GetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateDataInterface", NULL, cls_ID3D12DeviceChild_5, 3, 0, 0, 0 },
    { "ID3D12Object::SetName", NULL, NULL, 2, 0, 0, 0 },
    { "ID3D12DeviceChild::GetDevice", NULL, cls_ID3D12DeviceChild_7, 3, 0, 0, 0 },
};

static const unsigned char cls_ID3D12Fence_5[] = { CA_PASS, CA_IFACE_IN };
static const unsigned char cls_ID3D12Fence_7[] = { CA_RIID, CA_PPV_OUT };
static const unsigned char cls_ID3D12Fence_9[] = { CA_PASS, CA_EVENT };
static const struct d3d12_com_slot slots_ID3D12Fence[11] =
{
    { "IUnknown::QueryInterface", NULL, NULL, 3, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "ID3D12Object::GetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateDataInterface", NULL, cls_ID3D12Fence_5, 3, 0, 0, 0 },
    { "ID3D12Object::SetName", NULL, NULL, 2, 0, 0, 0 },
    { "ID3D12DeviceChild::GetDevice", NULL, cls_ID3D12Fence_7, 3, 0, 0, 0 },
    { "ID3D12Fence::GetCompletedValue", NULL, NULL, 1, 0, 0, 0 },
    { "ID3D12Fence::SetEventOnCompletion", NULL, cls_ID3D12Fence_9, 3, 0, 0, 0 },
    { "ID3D12Fence::Signal", NULL, NULL, 2, 0, 0, 0 },
};

static const unsigned char cls_ID3D12GraphicsCommandList_5[] = { CA_PASS, CA_IFACE_IN };
static const unsigned char cls_ID3D12GraphicsCommandList_7[] = { CA_RIID, CA_PPV_OUT };
static const unsigned char cls_ID3D12GraphicsCommandList_10[] = { CA_IFACE_IN, CA_IFACE_IN };
static const unsigned char cls_ID3D12GraphicsCommandList_11[] = { CA_IFACE_IN };
static const unsigned char cls_ID3D12GraphicsCommandList_15[] = { CA_IFACE_IN, CA_PASS, CA_IFACE_IN, CA_PASS, CA_PASS };
static const unsigned char cls_ID3D12GraphicsCommandList_17[] = { CA_IFACE_IN, CA_IFACE_IN };
static const unsigned char cls_ID3D12GraphicsCommandList_18[] = { CA_IFACE_IN, CA_PASS, CA_PASS, CA_IFACE_IN, CA_PASS, CA_PASS };
static const unsigned char cls_ID3D12GraphicsCommandList_19[] = { CA_IFACE_IN, CA_PASS, CA_IFACE_IN, CA_PASS, CA_PASS };
static const unsigned char cls_ID3D12GraphicsCommandList_25[] = { CA_IFACE_IN };
static const unsigned char cls_ID3D12GraphicsCommandList_27[] = { CA_IFACE_IN };
static const unsigned char cls_ID3D12GraphicsCommandList_28[] = { CA_PASS, CA_IFACE_ARR_IN };
static const unsigned char cls_ID3D12GraphicsCommandList_29[] = { CA_IFACE_IN };
static const unsigned char cls_ID3D12GraphicsCommandList_30[] = { CA_IFACE_IN };
static const unsigned char cls_ID3D12GraphicsCommandList_49[] = { CA_PASS, CA_PASS, CA_IFACE_IN, CA_PASS, CA_PASS, CA_PASS };
static const unsigned char cls_ID3D12GraphicsCommandList_50[] = { CA_PASS, CA_PASS, CA_IFACE_IN, CA_PASS, CA_PASS, CA_PASS };
static const unsigned char cls_ID3D12GraphicsCommandList_51[] = { CA_IFACE_IN, CA_PASS };
static const unsigned char cls_ID3D12GraphicsCommandList_52[] = { CA_IFACE_IN, CA_PASS, CA_PASS };
static const unsigned char cls_ID3D12GraphicsCommandList_53[] = { CA_IFACE_IN, CA_PASS, CA_PASS };
static const unsigned char cls_ID3D12GraphicsCommandList_54[] = { CA_IFACE_IN, CA_PASS, CA_PASS, CA_PASS, CA_IFACE_IN, CA_PASS };
static const unsigned char cls_ID3D12GraphicsCommandList_55[] = { CA_IFACE_IN, CA_PASS, CA_PASS };
static const unsigned char cls_ID3D12GraphicsCommandList_59[] = { CA_IFACE_IN, CA_PASS, CA_IFACE_IN, CA_PASS, CA_IFACE_IN, CA_PASS };
static const struct d3d12_com_slot slots_ID3D12GraphicsCommandList[60] =
{
    { "IUnknown::QueryInterface", NULL, NULL, 3, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "ID3D12Object::GetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateDataInterface", NULL, cls_ID3D12GraphicsCommandList_5, 3, 0, 0, 0 },
    { "ID3D12Object::SetName", NULL, NULL, 2, 0, 0, 0 },
    { "ID3D12DeviceChild::GetDevice", NULL, cls_ID3D12GraphicsCommandList_7, 3, 0, 0, 0 },
    { "ID3D12CommandList::GetType", NULL, NULL, 1, 0, 0, 0 },
    { "ID3D12GraphicsCommandList::Close", NULL, NULL, 1, 0, 0, 0 },
    { "ID3D12GraphicsCommandList::Reset", NULL, cls_ID3D12GraphicsCommandList_10, 3, 0, 0, 0 },
    { "ID3D12GraphicsCommandList::ClearState", NULL, cls_ID3D12GraphicsCommandList_11, 2, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::DrawInstanced", NULL, NULL, 5, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::DrawIndexedInstanced", NULL, NULL, 6, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::Dispatch", NULL, NULL, 4, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::CopyBufferRegion", NULL, cls_ID3D12GraphicsCommandList_15, 6, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::CopyTextureRegion",
      "ID3D12GraphicsCommandList::CopyTextureRegion: D3D12_TEXTURE_COPY_LOCATION carries interface pointers inside a struct and has no hand-written walker yet",
      NULL, 7, 0, 0, 0 },
    { "ID3D12GraphicsCommandList::CopyResource", NULL, cls_ID3D12GraphicsCommandList_17, 3, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::CopyTiles", NULL, cls_ID3D12GraphicsCommandList_18, 7, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::ResolveSubresource", NULL, cls_ID3D12GraphicsCommandList_19, 6, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::IASetPrimitiveTopology", NULL, NULL, 2, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::RSSetViewports", NULL, NULL, 3, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::RSSetScissorRects", NULL, NULL, 3, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::OMSetBlendFactor", NULL, NULL, 2, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::OMSetStencilRef", NULL, NULL, 2, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::SetPipelineState", NULL, cls_ID3D12GraphicsCommandList_25, 2, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::ResourceBarrier", NULL, NULL, 3, 4, 0, 0 },
    { "ID3D12GraphicsCommandList::ExecuteBundle", NULL, cls_ID3D12GraphicsCommandList_27, 2, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::SetDescriptorHeaps", NULL, cls_ID3D12GraphicsCommandList_28, 3, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::SetComputeRootSignature", NULL, cls_ID3D12GraphicsCommandList_29, 2, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::SetGraphicsRootSignature", NULL, cls_ID3D12GraphicsCommandList_30, 2, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::SetComputeRootDescriptorTable", NULL, NULL, 3, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::SetGraphicsRootDescriptorTable", NULL, NULL, 3, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::SetComputeRoot32BitConstant", NULL, NULL, 4, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::SetGraphicsRoot32BitConstant", NULL, NULL, 4, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::SetComputeRoot32BitConstants", NULL, NULL, 5, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::SetGraphicsRoot32BitConstants", NULL, NULL, 5, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::SetComputeRootConstantBufferView", NULL, NULL, 3, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::SetGraphicsRootConstantBufferView", NULL, NULL, 3, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::SetComputeRootShaderResourceView", NULL, NULL, 3, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::SetGraphicsRootShaderResourceView", NULL, NULL, 3, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::SetComputeRootUnorderedAccessView", NULL, NULL, 3, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::SetGraphicsRootUnorderedAccessView", NULL, NULL, 3, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::IASetIndexBuffer", NULL, NULL, 2, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::IASetVertexBuffers", NULL, NULL, 4, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::SOSetTargets", NULL, NULL, 4, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::OMSetRenderTargets", NULL, NULL, 5, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::ClearDepthStencilView",
      "ID3D12GraphicsCommandList::ClearDepthStencilView is float-class and has no hand-written stub; the uint64_t transport would read an unrelated register",
      NULL, 7, 0, 0, 0 },
    { "ID3D12GraphicsCommandList::ClearRenderTargetView", NULL, NULL, 5, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::ClearUnorderedAccessViewUint", NULL, cls_ID3D12GraphicsCommandList_49, 7, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::ClearUnorderedAccessViewFloat", NULL, cls_ID3D12GraphicsCommandList_50, 7, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::DiscardResource", NULL, cls_ID3D12GraphicsCommandList_51, 3, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::BeginQuery", NULL, cls_ID3D12GraphicsCommandList_52, 4, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::EndQuery", NULL, cls_ID3D12GraphicsCommandList_53, 4, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::ResolveQueryData", NULL, cls_ID3D12GraphicsCommandList_54, 7, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::SetPredication", NULL, cls_ID3D12GraphicsCommandList_55, 4, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::SetMarker", NULL, NULL, 4, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::BeginEvent", NULL, NULL, 4, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::EndEvent", NULL, NULL, 1, 1, 0, 0 },
    { "ID3D12GraphicsCommandList::ExecuteIndirect", NULL, cls_ID3D12GraphicsCommandList_59, 7, 1, 0, 0 },
};

static const unsigned char cls_ID3D12Heap_5[] = { CA_PASS, CA_IFACE_IN };
static const unsigned char cls_ID3D12Heap_7[] = { CA_RIID, CA_PPV_OUT };
static const unsigned char cls_ID3D12Heap_8[] = { CA_RET_PTR };
static const struct d3d12_com_slot slots_ID3D12Heap[9] =
{
    { "IUnknown::QueryInterface", NULL, NULL, 3, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "ID3D12Object::GetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateDataInterface", NULL, cls_ID3D12Heap_5, 3, 0, 0, 0 },
    { "ID3D12Object::SetName", NULL, NULL, 2, 0, 0, 0 },
    { "ID3D12DeviceChild::GetDevice", NULL, cls_ID3D12Heap_7, 3, 0, 0, 0 },
    { "ID3D12Heap::GetDesc", NULL, cls_ID3D12Heap_8, 2, 2, 0, 0 },
};

static const unsigned char cls_ID3D12Object_5[] = { CA_PASS, CA_IFACE_IN };
static const struct d3d12_com_slot slots_ID3D12Object[7] =
{
    { "IUnknown::QueryInterface", NULL, NULL, 3, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "ID3D12Object::GetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateDataInterface", NULL, cls_ID3D12Object_5, 3, 0, 0, 0 },
    { "ID3D12Object::SetName", NULL, NULL, 2, 0, 0, 0 },
};

static const unsigned char cls_ID3D12Pageable_5[] = { CA_PASS, CA_IFACE_IN };
static const unsigned char cls_ID3D12Pageable_7[] = { CA_RIID, CA_PPV_OUT };
static const struct d3d12_com_slot slots_ID3D12Pageable[8] =
{
    { "IUnknown::QueryInterface", NULL, NULL, 3, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "ID3D12Object::GetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateDataInterface", NULL, cls_ID3D12Pageable_5, 3, 0, 0, 0 },
    { "ID3D12Object::SetName", NULL, NULL, 2, 0, 0, 0 },
    { "ID3D12DeviceChild::GetDevice", NULL, cls_ID3D12Pageable_7, 3, 0, 0, 0 },
};

static const unsigned char cls_ID3D12PipelineState_5[] = { CA_PASS, CA_IFACE_IN };
static const unsigned char cls_ID3D12PipelineState_7[] = { CA_RIID, CA_PPV_OUT };
static const struct d3d12_com_slot slots_ID3D12PipelineState[9] =
{
    { "IUnknown::QueryInterface", NULL, NULL, 3, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "ID3D12Object::GetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateDataInterface", NULL, cls_ID3D12PipelineState_5, 3, 0, 0, 0 },
    { "ID3D12Object::SetName", NULL, NULL, 2, 0, 0, 0 },
    { "ID3D12DeviceChild::GetDevice", NULL, cls_ID3D12PipelineState_7, 3, 0, 0, 0 },
    { "ID3D12PipelineState::GetCachedBlob", NULL, NULL, 2, 0, 0, 0 },
};

static const unsigned char cls_ID3D12Resource_5[] = { CA_PASS, CA_IFACE_IN };
static const unsigned char cls_ID3D12Resource_7[] = { CA_RIID, CA_PPV_OUT };
static const unsigned char cls_ID3D12Resource_10[] = { CA_RET_PTR };
static const struct d3d12_com_slot slots_ID3D12Resource[15] =
{
    { "IUnknown::QueryInterface", NULL, NULL, 3, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "ID3D12Object::GetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateDataInterface", NULL, cls_ID3D12Resource_5, 3, 0, 0, 0 },
    { "ID3D12Object::SetName", NULL, NULL, 2, 0, 0, 0 },
    { "ID3D12DeviceChild::GetDevice", NULL, cls_ID3D12Resource_7, 3, 0, 0, 0 },
    { "ID3D12Resource::Map", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Resource::Unmap", NULL, NULL, 3, 1, 0, 0 },
    { "ID3D12Resource::GetDesc", NULL, cls_ID3D12Resource_10, 2, 2, 0, 0 },
    { "ID3D12Resource::GetGPUVirtualAddress", NULL, NULL, 1, 0, 0, 0 },
    { "ID3D12Resource::WriteToSubresource", NULL, NULL, 6, 0, 0, 0 },
    { "ID3D12Resource::ReadFromSubresource", NULL, NULL, 6, 0, 0, 0 },
    { "ID3D12Resource::GetHeapProperties", NULL, NULL, 3, 0, 0, 0 },
};

static const unsigned char cls_ID3D12RootSignature_5[] = { CA_PASS, CA_IFACE_IN };
static const unsigned char cls_ID3D12RootSignature_7[] = { CA_RIID, CA_PPV_OUT };
static const struct d3d12_com_slot slots_ID3D12RootSignature[8] =
{
    { "IUnknown::QueryInterface", NULL, NULL, 3, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "ID3D12Object::GetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateData", NULL, NULL, 4, 0, 0, 0 },
    { "ID3D12Object::SetPrivateDataInterface", NULL, cls_ID3D12RootSignature_5, 3, 0, 0, 0 },
    { "ID3D12Object::SetName", NULL, NULL, 2, 0, 0, 0 },
    { "ID3D12DeviceChild::GetDevice", NULL, cls_ID3D12RootSignature_7, 3, 0, 0, 0 },
};

static const struct d3d12_com_slot slots_ID3D12RootSignatureDeserializer[4] =
{
    { "IUnknown::QueryInterface", NULL, NULL, 3, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "ID3D12RootSignatureDeserializer::GetRootSignatureDesc", NULL, NULL, 1, 0, 0, 0 },
};

static const struct d3d12_com_slot slots_ID3D12VersionedRootSignatureDeserializer[5] =
{
    { "IUnknown::QueryInterface", NULL, NULL, 3, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "ID3D12VersionedRootSignatureDeserializer::GetRootSignatureDescAtVersion", NULL, NULL, 3, 0, 0, 0 },
    { "ID3D12VersionedRootSignatureDeserializer::GetUnconvertedRootSignatureDesc", NULL, NULL, 1, 0, 0, 0 },
};

static const struct d3d12_com_slot slots_IUnknown[3] =
{
    { "IUnknown::QueryInterface", NULL, NULL, 3, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, 1, 0, 0, 0 },  /* runtime */
};

static const struct d3d12_com_iface d3d12_com_ifaces[D3D12_IFACE_COUNT] =
{
    { "ID3D10Blob", {0x8ba5fb08,0x5195,0x40e2,{0xac,0x58,0x0d,0x98,0x9c,0x3a,0x01,0x02}},
      5, slots_ID3D10Blob },
    { "ID3D12ApplicationIdentity", {0x82dc6c85,0x727b,0x4a8d,{0x91,0x69,0xdb,0x6c,0xe3,0xe9,0x75,0xa0}},
      4, NULL },
    { "ID3D12CommandAllocator", {0x6102dee4,0xaf59,0x4b09,{0xb9,0x99,0xb4,0x4d,0x73,0xf0,0x9b,0x24}},
      9, slots_ID3D12CommandAllocator },
    { "ID3D12CommandList", {0x7116d91c,0xe7e4,0x47ce,{0xb8,0xc6,0xec,0x81,0x68,0xf4,0x37,0xe5}},
      9, slots_ID3D12CommandList },
    { "ID3D12CommandQueue", {0x0ec870a6,0x5d7e,0x4c22,{0x8c,0xfc,0x5b,0xaa,0xe0,0x76,0x16,0xed}},
      19, slots_ID3D12CommandQueue },
    { "ID3D12CommandSignature", {0xc36a797c,0xec80,0x4f0a,{0x89,0x85,0xa7,0xb2,0x47,0x50,0x82,0xd1}},
      8, NULL },
    { "ID3D12DescriptorHeap", {0x8efb471d,0x616c,0x4f49,{0x90,0xf7,0x12,0x7b,0xb7,0x63,0xfa,0x51}},
      11, slots_ID3D12DescriptorHeap },
    { "ID3D12Device", {0x189819f1,0x1db6,0x4b57,{0xbe,0x54,0x18,0x21,0x33,0x9b,0x85,0xf7}},
      44, slots_ID3D12Device },
    { "ID3D12Device1", {0x77acce80,0x638e,0x4e65,{0x88,0x95,0xc1,0xf2,0x33,0x86,0x86,0x3e}},
      47, NULL },
    { "ID3D12Device10", {0x517f8718,0xaa66,0x49f9,{0xb0,0x2b,0xa7,0xab,0x89,0xc0,0x60,0x31}},
      79, NULL },
    { "ID3D12Device11", {0x5405c344,0xd457,0x444e,{0xb4,0xdd,0x23,0x66,0xe4,0x5a,0xee,0x39}},
      80, NULL },
    { "ID3D12Device12", {0x5af5c532,0x4c91,0x4cd0,{0xb5,0x41,0x15,0xa4,0x05,0x39,0x5f,0xc5}},
      81, NULL },
    { "ID3D12Device13", {0x14eecffc,0x4df8,0x40f7,{0xa1,0x18,0x5c,0x81,0x6f,0x45,0x69,0x5e}},
      82, NULL },
    { "ID3D12Device14", {0x5f6e592d,0xd895,0x44c2,{0x8e,0x4a,0x88,0xad,0x49,0x26,0xd3,0x23}},
      83, NULL },
    { "ID3D12Device15", {0x76cff76f,0x1e9b,0x4450,{0x8c,0xdc,0x34,0xf1,0xaf,0x78,0x8e,0x5b}},
      94, NULL },
    { "ID3D12Device2", {0x30baa41e,0xb15b,0x475c,{0xa0,0xbb,0x1a,0xf5,0xc5,0xb6,0x43,0x28}},
      48, NULL },
    { "ID3D12Device3", {0x81dadc15,0x2bad,0x4392,{0x93,0xc5,0x10,0x13,0x45,0xc4,0xaa,0x98}},
      51, NULL },
    { "ID3D12Device4", {0xe865df17,0xa9ee,0x46f9,{0xa4,0x63,0x30,0x98,0x31,0x5a,0xa2,0xe5}},
      57, NULL },
    { "ID3D12Device5", {0x8b4f173b,0x2fea,0x4b80,{0x8f,0x58,0x43,0x07,0x19,0x1a,0xb9,0x5d}},
      65, NULL },
    { "ID3D12Device6", {0xc70b221b,0x40e4,0x4a17,{0x89,0xaf,0x02,0x5a,0x07,0x27,0xa6,0xdc}},
      66, NULL },
    { "ID3D12Device7", {0x5c014b53,0x68a1,0x4b9b,{0x8b,0xd1,0xdd,0x60,0x46,0xb9,0x35,0x8b}},
      68, NULL },
    { "ID3D12Device8", {0x9218e6bb,0xf944,0x4f7e,{0xa7,0x5c,0xb1,0xb2,0xc7,0xb7,0x01,0xf3}},
      73, NULL },
    { "ID3D12Device9", {0x4c80e962,0xf032,0x4f60,{0xbc,0x9e,0xeb,0xc2,0xcf,0xa1,0xd8,0x3c}},
      76, NULL },
    { "ID3D12DeviceChild", {0x905db94b,0xa00c,0x4140,{0x9d,0xf5,0x2b,0x64,0xca,0x9e,0xa3,0x57}},
      8, slots_ID3D12DeviceChild },
    { "ID3D12DeviceConfiguration", {0x78dbf87b,0xf766,0x422b,{0xa6,0x1c,0xc8,0xc4,0x46,0xbd,0xb9,0xad}},
      7, NULL },
    { "ID3D12DeviceConfiguration1", {0xed342442,0x6343,0x4e16,{0xbb,0x82,0xa3,0xa5,0x77,0x87,0x4e,0x56}},
      8, NULL },
    { "ID3D12DeviceFactory", {0x61f307d3,0xd34e,0x4e7c,{0x83,0x74,0x3b,0xa4,0xde,0x23,0xcc,0xcb}},
      10, NULL },
    { "ID3D12DeviceRemovedExtendedData", {0x98931d33,0x5ae8,0x4791,{0xaa,0x3c,0x1a,0x73,0xa2,0x93,0x4e,0x71}},
      5, NULL },
    { "ID3D12DeviceRemovedExtendedDataSettings", {0x82bc481c,0x6b9b,0x4030,{0xae,0xdb,0x7e,0xe3,0xd1,0xdf,0x1e,0x63}},
      6, NULL },
    { "ID3D12DeviceRemovedExtendedDataSettings1", {0xdbd5ae51,0x3317,0x4f0a,{0xad,0xf9,0x1d,0x7c,0xed,0xca,0xae,0x0b}},
      7, NULL },
    { "ID3D12DeviceRemovedExtendedDataSettings2", {0x61552388,0x01ab,0x4008,{0xa4,0x36,0x83,0xdb,0x18,0x95,0x66,0xea}},
      8, NULL },
    { "ID3D12Fence", {0x0a753dcf,0xc4d8,0x4b91,{0xad,0xf6,0xbe,0x5a,0x60,0xd9,0x5a,0x76}},
      11, slots_ID3D12Fence },
    { "ID3D12Fence1", {0x433685fe,0xe22b,0x4ca0,{0xa8,0xdb,0xb5,0xb4,0xf4,0xdd,0x0e,0x4a}},
      12, NULL },
    { "ID3D12GraphicsCommandList", {0x5b160d0f,0xac1b,0x4185,{0x8b,0xa8,0xb3,0xae,0x42,0xa5,0xa4,0x55}},
      60, slots_ID3D12GraphicsCommandList },
    { "ID3D12GraphicsCommandList1", {0x553103fb,0x1fe7,0x4557,{0xbb,0x38,0x94,0x6d,0x7d,0x0e,0x7c,0xa7}},
      66, NULL },
    { "ID3D12GraphicsCommandList10", {0x7013c015,0xd161,0x4b63,{0xa0,0x8c,0x23,0x85,0x52,0xdd,0x8a,0xcc}},
      86, NULL },
    { "ID3D12GraphicsCommandList2", {0x38c3e585,0xff17,0x412c,{0x91,0x50,0x4f,0xc6,0xf9,0xd7,0x2a,0x28}},
      67, NULL },
    { "ID3D12GraphicsCommandList3", {0x6fda83a7,0xb84c,0x4e38,{0x9a,0xc8,0xc7,0xbd,0x22,0x01,0x6b,0x3d}},
      68, NULL },
    { "ID3D12GraphicsCommandList4", {0x8754318e,0xd3a9,0x4541,{0x98,0xcf,0x64,0x5b,0x50,0xdc,0x48,0x74}},
      77, NULL },
    { "ID3D12GraphicsCommandList5", {0x55050859,0x4024,0x474c,{0x87,0xf5,0x64,0x72,0xea,0xee,0x44,0xea}},
      79, NULL },
    { "ID3D12GraphicsCommandList6", {0xc3827890,0xe548,0x4cfa,{0x96,0xcf,0x56,0x89,0xa9,0x37,0x0f,0x80}},
      80, NULL },
    { "ID3D12GraphicsCommandList7", {0xdd171223,0x8b61,0x4769,{0x90,0xe3,0x16,0x0c,0xcd,0xe4,0xe2,0xc1}},
      81, NULL },
    { "ID3D12GraphicsCommandList8", {0xee936ef9,0x599d,0x4d28,{0x93,0x8e,0x23,0xc4,0xad,0x05,0xce,0x51}},
      82, NULL },
    { "ID3D12GraphicsCommandList9", {0x34ed2808,0xffe6,0x4c2b,{0xb1,0x1a,0xca,0xbd,0x2b,0x0c,0x59,0xe1}},
      84, NULL },
    { "ID3D12Heap", {0x6b3b2502,0x6e51,0x45b3,{0x90,0xee,0x98,0x84,0x26,0x5e,0x8d,0xf3}},
      9, slots_ID3D12Heap },
    { "ID3D12Heap1", {0x572f7389,0x2168,0x49e3,{0x96,0x93,0xd6,0xdf,0x58,0x71,0xbf,0x6d}},
      10, NULL },
    { "ID3D12LifetimeOwner", {0xe667af9f,0xcd56,0x4f46,{0x83,0xce,0x03,0x2e,0x59,0x5d,0x70,0xa8}},
      4, NULL },
    { "ID3D12LifetimeTracker", {0x3fd03d36,0x4eb1,0x424a,{0xa5,0x82,0x49,0x4e,0xcb,0x8b,0xa8,0x13}},
      4, NULL },
    { "ID3D12MetaCommand", {0xdbb84c27,0x36ce,0x4fc9,{0xb8,0x01,0xf0,0x48,0xc4,0x6a,0xc5,0x70}},
      9, NULL },
    { "ID3D12Object", {0xc4fec28f,0x7966,0x4e95,{0x9f,0x94,0xf4,0x31,0xcb,0x56,0xc3,0xb8}},
      7, slots_ID3D12Object },
    { "ID3D12Pageable", {0x63ee58fb,0x1268,0x4835,{0x86,0xda,0xf0,0x08,0xce,0x62,0xf0,0xd6}},
      8, slots_ID3D12Pageable },
    { "ID3D12PipelineLibrary", {0xc64226a8,0x9201,0x46af,{0xb4,0xcc,0x53,0xfb,0x9f,0xf7,0x41,0x4f}},
      13, NULL },
    { "ID3D12PipelineLibrary1", {0x80eabf42,0x2568,0x4e5e,{0xbd,0x82,0xc3,0x7f,0x86,0x96,0x1d,0xc3}},
      14, NULL },
    { "ID3D12PipelineState", {0x765a30f3,0xf624,0x4c6f,{0xa8,0x28,0xac,0xe9,0x48,0x62,0x24,0x45}},
      9, slots_ID3D12PipelineState },
    { "ID3D12ProtectedResourceSession", {0x6cd696f4,0xf289,0x40cc,{0x80,0x91,0x5a,0x6c,0x0a,0x09,0x9c,0x3d}},
      11, NULL },
    { "ID3D12ProtectedResourceSession1", {0xd6f12dd6,0x76fb,0x406e,{0x89,0x61,0x42,0x96,0xee,0xfc,0x04,0x09}},
      12, NULL },
    { "ID3D12ProtectedSession", {0xa1533d18,0x0ac1,0x4084,{0x85,0xb9,0x89,0xa9,0x61,0x16,0x80,0x6b}},
      10, NULL },
    { "ID3D12QueryHeap", {0x0d9658ae,0xed45,0x469e,{0xa6,0x1d,0x97,0x0e,0xc5,0x83,0xca,0xb4}},
      8, NULL },
    { "ID3D12Resource", {0x696442be,0xa72e,0x4059,{0xbc,0x79,0x5b,0x5c,0x98,0x04,0x0f,0xad}},
      15, slots_ID3D12Resource },
    { "ID3D12Resource1", {0x9d5e227a,0x4430,0x4161,{0x88,0xb3,0x3e,0xca,0x6b,0xb1,0x6e,0x19}},
      16, NULL },
    { "ID3D12Resource2", {0xbe36ec3b,0xea85,0x4aeb,{0xa4,0x5a,0xe9,0xd7,0x64,0x04,0xa4,0x95}},
      17, NULL },
    { "ID3D12RootSignature", {0xc54a6b66,0x72df,0x4ee8,{0x8b,0xe5,0xa9,0x46,0xa1,0x42,0x92,0x14}},
      8, slots_ID3D12RootSignature },
    { "ID3D12RootSignatureDeserializer", {0x34ab647b,0x3cc8,0x46ac,{0x84,0x1b,0xc0,0x96,0x56,0x45,0xc0,0x46}},
      4, slots_ID3D12RootSignatureDeserializer },
    { "ID3D12SDKConfiguration", {0xe9eb5314,0x33aa,0x42b2,{0xa7,0x18,0xd7,0x7f,0x58,0xb1,0xf1,0xc7}},
      4, NULL },
    { "ID3D12SDKConfiguration1", {0x8aaf9303,0xad25,0x48b9,{0x9a,0x57,0xd9,0xc3,0x7e,0x00,0x9d,0x9f}},
      6, NULL },
    { "ID3D12StateObject", {0x47016943,0xfca8,0x4594,{0x93,0xea,0xaf,0x25,0x8b,0x55,0x34,0x6d}},
      8, NULL },
    { "ID3D12StateObjectProperties", {0xde5fa827,0x9bf9,0x4f26,{0x89,0xff,0xd7,0xf5,0x6f,0xde,0x38,0x60}},
      7, NULL },
    { "ID3D12StateObjectProperties1", {0x460caac7,0x1d24,0x446a,{0xa1,0x84,0xca,0x67,0xdb,0x49,0x41,0x38}},
      8, NULL },
    { "ID3D12SwapChainAssistant", {0xf1df64b6,0x57fd,0x49cd,{0x88,0x07,0xc0,0xeb,0x88,0xb4,0x5c,0x8f}},
      7, NULL },
    { "ID3D12Tools", {0x7071e1f0,0xe84b,0x4b33,{0x97,0x4f,0x12,0xfa,0x49,0xde,0x65,0xc5}},
      5, NULL },
    { "ID3D12VersionedRootSignatureDeserializer", {0x7f91ce67,0x090c,0x4bb7,{0xb7,0x8e,0xed,0x8f,0xf2,0xe3,0x1d,0xa0}},
      5, slots_ID3D12VersionedRootSignatureDeserializer },
    { "ID3D12WorkGraphProperties", {0x065acf71,0xf863,0x4b89,{0x82,0xf4,0x02,0xe4,0xd5,0x88,0x67,0x57}},
      16, NULL },
    { "ID3DDestructionNotifier", {0xa06eb39a,0x50da,0x425b,{0x8c,0x31,0x4e,0xec,0xd6,0xc2,0x70,0xf3}},
      5, NULL },
    { "IDXGIAdapter", {0x2411e7e1,0x12ac,0x4ccf,{0xbd,0x14,0x97,0x98,0xe8,0x53,0x4d,0xc0}},
      10, NULL },
    { "IDXGIAdapter1", {0x29038f61,0x3839,0x4626,{0x91,0xfd,0x08,0x68,0x79,0x01,0x1a,0x05}},
      11, NULL },
    { "IDXGIAdapter2", {0x0aa1ae0a,0xfa0e,0x4b84,{0x86,0x44,0xe0,0x5f,0xf8,0xe5,0xac,0xb5}},
      12, NULL },
    { "IDXGIAdapter3", {0x645967a4,0x1392,0x4310,{0xa7,0x98,0x80,0x53,0xce,0x3e,0x93,0xfd}},
      18, NULL },
    { "IDXGIAdapter4", {0x3c8d99d1,0x4fbf,0x4181,{0xa8,0x2c,0xaf,0x66,0xbf,0x7b,0xd2,0x4e}},
      19, NULL },
    { "IDXGIDecodeSwapChain", {0x2633066b,0x4514,0x4c7a,{0x8f,0xd8,0x12,0xea,0x98,0x05,0x9d,0x18}},
      12, NULL },
    { "IDXGIDevice", {0x54ec77fa,0x1377,0x44e6,{0x8c,0x32,0x88,0xfd,0x5f,0x44,0xc8,0x4c}},
      12, NULL },
    { "IDXGIDevice1", {0x77db970f,0x6276,0x48ba,{0xba,0x28,0x07,0x01,0x43,0xb4,0x39,0x2c}},
      14, NULL },
    { "IDXGIDevice2", {0x05008617,0xfbfd,0x4051,{0xa7,0x90,0x14,0x48,0x84,0xb4,0xf6,0xa9}},
      17, NULL },
    { "IDXGIDevice3", {0x6007896c,0x3244,0x4afd,{0xbf,0x18,0xa6,0xd3,0xbe,0xda,0x50,0x23}},
      18, NULL },
    { "IDXGIDevice4", {0x95b4f95f,0xd8da,0x4ca4,{0x9e,0xe6,0x3b,0x76,0xd5,0x96,0x8a,0x10}},
      20, NULL },
    { "IDXGIDeviceSubObject", {0x3d3e0379,0xf9de,0x4d58,{0xbb,0x6c,0x18,0xd6,0x29,0x92,0xf1,0xa6}},
      8, NULL },
    { "IDXGIDisplayControl", {0xea9dbf1a,0xc88e,0x4486,{0x85,0x4a,0x98,0xaa,0x01,0x38,0xf3,0x0c}},
      5, NULL },
    { "IDXGIFactory", {0x7b7166ec,0x21c7,0x44ae,{0xb2,0x1a,0xc9,0xae,0x32,0x1a,0xe3,0x69}},
      12, NULL },
    { "IDXGIFactory1", {0x770aae78,0xf26f,0x4dba,{0xa8,0x29,0x25,0x3c,0x83,0xd1,0xb3,0x87}},
      14, NULL },
    { "IDXGIFactory2", {0x50c83a1c,0xe072,0x4c48,{0x87,0xb0,0x36,0x30,0xfa,0x36,0xa6,0xd0}},
      25, NULL },
    { "IDXGIFactory3", {0x25483823,0xcd46,0x4c7d,{0x86,0xca,0x47,0xaa,0x95,0xb8,0x37,0xbd}},
      26, NULL },
    { "IDXGIFactory4", {0x1bc6ea02,0xef36,0x464f,{0xbf,0x0c,0x21,0xca,0x39,0xe5,0x16,0x8a}},
      28, NULL },
    { "IDXGIFactory5", {0x7632e1f5,0xee65,0x4dca,{0x87,0xfd,0x84,0xcd,0x75,0xf8,0x83,0x8d}},
      29, NULL },
    { "IDXGIFactory6", {0xc1b6694f,0xff09,0x44a9,{0xb0,0x3c,0x77,0x90,0x0a,0x0a,0x1d,0x17}},
      30, NULL },
    { "IDXGIFactory7", {0xa4966eed,0x76db,0x44da,{0x84,0xc1,0xee,0x9a,0x7a,0xfb,0x20,0xa8}},
      32, NULL },
    { "IDXGIFactoryMedia", {0x41e7d1f2,0xa591,0x4f7b,{0xa2,0xe5,0xfa,0x9c,0x84,0x3e,0x1c,0x12}},
      5, NULL },
    { "IDXGIKeyedMutex", {0x9d8e1289,0xd7b3,0x465f,{0x81,0x26,0x25,0x0e,0x34,0x9a,0xf8,0x5d}},
      10, NULL },
    { "IDXGIObject", {0xaec22fb8,0x76f3,0x4639,{0x9b,0xe0,0x28,0xeb,0x43,0xa6,0x7a,0x2e}},
      7, NULL },
    { "IDXGIOutput", {0xae02eedb,0xc735,0x4690,{0x8d,0x52,0x5a,0x8d,0xc2,0x02,0x13,0xaa}},
      19, NULL },
    { "IDXGIOutput1", {0x00cddea8,0x939b,0x4b83,{0xa3,0x40,0xa6,0x85,0x22,0x66,0x66,0xcc}},
      23, NULL },
    { "IDXGIOutput2", {0x595e39d1,0x2724,0x4663,{0x99,0xb1,0xda,0x96,0x9d,0xe2,0x83,0x64}},
      24, NULL },
    { "IDXGIOutput3", {0x8a6bb301,0x7e7e,0x41f4,{0xa8,0xe0,0x5b,0x32,0xf7,0xf9,0x9b,0x18}},
      25, NULL },
    { "IDXGIOutput4", {0xdc7dca35,0x2196,0x414d,{0x9f,0x53,0x61,0x78,0x84,0x03,0x2a,0x60}},
      26, NULL },
    { "IDXGIOutput5", {0x80a07424,0xab52,0x42eb,{0x83,0x3c,0x0c,0x42,0xfd,0x28,0x2d,0x98}},
      27, NULL },
    { "IDXGIOutput6", {0x068346e8,0xaaec,0x4b84,{0xad,0xd7,0x13,0x7f,0x51,0x3f,0x77,0xa1}},
      29, NULL },
    { "IDXGIOutputDuplication", {0x191cfac3,0xa341,0x470d,{0xb2,0x6e,0xa8,0x64,0xf4,0x28,0x31,0x9c}},
      15, NULL },
    { "IDXGIResource", {0x035f3ab4,0x482e,0x4e50,{0xb4,0x1f,0x8a,0x7f,0x8b,0xd8,0x96,0x0b}},
      12, NULL },
    { "IDXGIResource1", {0x30961379,0x4609,0x4a41,{0x99,0x8e,0x54,0xfe,0x56,0x7e,0xe0,0xc1}},
      14, NULL },
    { "IDXGISurface", {0xcafcb56c,0x6ac3,0x4889,{0xbf,0x47,0x9e,0x23,0xbb,0xd2,0x60,0xec}},
      11, NULL },
    { "IDXGISurface1", {0x4ae63092,0x6327,0x4c1b,{0x80,0xae,0xbf,0xe1,0x2e,0xa3,0x2b,0x86}},
      13, NULL },
    { "IDXGISurface2", {0xaba496dd,0xb617,0x4cb8,{0xa8,0x66,0xbc,0x44,0xd7,0xeb,0x1f,0xa2}},
      14, NULL },
    { "IDXGISwapChain", {0x310d36a0,0xd2e7,0x4c0a,{0xaa,0x04,0x6a,0x9d,0x23,0xb8,0x88,0x6a}},
      18, NULL },
    { "IDXGISwapChain1", {0x790a45f7,0x0d42,0x4876,{0x98,0x3a,0x0a,0x55,0xcf,0xe6,0xf4,0xaa}},
      29, NULL },
    { "IDXGISwapChain2", {0xa8be2ac4,0x199f,0x4946,{0xb3,0x31,0x79,0x59,0x9f,0xb9,0x8d,0xe7}},
      36, NULL },
    { "IDXGISwapChain3", {0x94d99bdb,0xf1f8,0x4ab0,{0xb2,0x36,0x7d,0xa0,0x17,0x0e,0xda,0xb1}},
      40, NULL },
    { "IDXGISwapChain4", {0x3d585d5a,0xbd4a,0x489e,{0xb1,0xf4,0x3d,0xbc,0xb6,0x45,0x2f,0xfb}},
      41, NULL },
    { "IDXGISwapChainMedia", {0xdd95b90b,0xf05f,0x4f6a,{0xbd,0x65,0x25,0xbf,0xb2,0x64,0xbd,0x84}},
      6, NULL },
    { "IUnknown", {0x00000000,0x0000,0x0000,{0xc0,0x00,0x00,0x00,0x00,0x00,0x00,0x46}},
      3, slots_IUnknown },
};

/* 187 slot(s) marshalled, 3 refused pending later steps, across the
 * 18 subset interface(s); 99 interface(s) carry identity rows only. */
