#!/usr/bin/env python3
"""Emit the winecom marshal tables for the d3d12 (vkd3d-proton) surface.

  ./gen_winecom.py --out ../../dlls/d3d12/d3d12_marshal.h
  ./gen_winecom.py --report        # what is marshalled, what is refused, why
  ./gen_winecom.py --check ../../dlls/d3d12/d3d12_marshal.h

INPUT is interfaces_d3d12.json -- the ONE roster, the same file
dlls/d3d12/d3d12.thunks hands spec2thunk to build the guest trap module.
Both generators sort by interface name, and libs/winecom cross-checks every
IID and slot count at attach as the last line of defence.

OUTPUT is a header of `struct winecom_slot` / `struct winecom_iface` tables
(include/wine/winecom.h), consumed by dlls/d3d12/main.c.

HISTORY, because it explains the shape of this file: d3d12 was the FIRST
winecom surface and its marshal table was generated by a script that lived in
the dxvk-ppc64le clone and no longer exists anywhere.  That script only
emitted tables for the 21 interfaces its smoke test touched; the other 96 --
ID3D12Device1 through Device15 among them -- got NULL identity rows, so every
call through a Device4 proxy answered "no marshal plan".  Cyberpunk 2077 hit
exactly that: CreateCommittedResource1 and CreateHeap1 refused, the game
Reset() the command list it never checked.  This generator is the lane's
re-entry into the gen_winecom.py family (mf/audio/dxvk are the siblings; the
mf copy is the closest ancestor): every rostered interface now gets a real
table, and a slot refuses only for a reason this file can name.

WHAT IS DIFFERENT ON THIS SURFACE, each with the measurement behind it:

  * WCHAR crosses.  vkd3d's own vkd3d_windows.h line 89 says
    `typedef unsigned short WCHAR;`, the guest PE's WCHAR is two bytes too --
    unlike the DXVK lane, where dxvk-native's four-byte wchar_t made GetDesc
    answer "A" and zeros (dxvk-patches/0005).  SetName and the LPCWSTR family
    pass.
  * HANDLE mostly crosses AS A NUMBER the native side will not understand,
    and that is the committed policy, not an accident: vkd3d's unix side has
    no Wine handle table, so OpenSharedHandle-family slots pass the value and
    vkd3d answers its own E_NOTIMPL.  The exception is the completion-event
    slots (EVENT_SLOTS below): a real Wine event handle passed there would be
    WAITED ON natively, so those are classed WINECOM_CA_EVENT and the runtime
    refuses a non-NULL event until the eventfd relay exists.  A NULL event --
    the blocking form of SetEventOnCompletion -- is served, and is what the
    fence gates use.
  * HWND crosses.  There is one window-handle namespace in the process and
    this lane presents through win32u (unix_win32u.c), the same reasoning
    that put HWND back on the DXVK surface.
  * widl's aggregate returns (`GetDesc(D3D12_HEAP_DESC *__ret)`) are classed
    WINECOM_CA_RET_PTR with WINECOM_F_RET_VIA_ARG, the shape the runtime has
    served since the first commit of this lane.
  * NO WINECOM_F_REV, ever.  The invoker crosses a unixlib
    (dlls/d3d12/unix.c) and the surface deliberately lacks WINECOM_SF_REVERSE
    -- a reverse proxy is a PE-side object the unix side would call as data.
    A by-value float is therefore a plain refusal here (ClearDepthStencilView
    keeps the refusal the old table had), not a reverse-only row.

The struct scan below brace-matches instead of borrowing the siblings' crude
regex, and that is load-bearing: these headers spell D3D12_RESOURCE_BARRIER
and D3D12_TEXTURE_COPY_LOCATION with NESTED NAMELESS UNIONS, which the
non-greedy regex mis-parses so badly that D3D12_RESOURCE_BARRIER never enters
the bearing set at all -- and a struct the scan never saw is passed through,
which is the one outcome this generator exists to prevent.

Copyright 2026 the ppc64le port authors

This library is free software; you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the GNU
Free Software Foundation; either version 2.1 of the License, or (at your
option) any later version.
"""

import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# --------------------------------------------------------------------------
# by-value types that cross as an integer register and are the same width on
# both sides.  ANYTHING NOT LISTED BECOMES A NAMED REFUSAL -- see the banner.
# The roster's enum names are added to this set at run time; an enum is
# `int`-class in both ABIs.
# --------------------------------------------------------------------------
BYVAL_INTEGER = frozenset("""
    UINT INT LONG ULONG DWORD WORD BYTE BOOL WINBOOL UINT8 UINT16 UINT32
    UINT64 INT8 INT16 INT32 INT64 SIZE_T SSIZE_T LONGLONG ULONGLONG
    ULONG64 LONG64 QWORD HANDLE HWND HMODULE HMONITOR HRESULT
    ULONG_PTR DWORD_PTR UINT_PTR LONG_PTR INT_PTR
    SHORT USHORT CHAR UCHAR BOOLEAN
    unsigned int short char long
""".split())

# Integer typedefs these headers spell under their own names.  Each entry was
# read in the header, not assumed.
TYPEDEF_INTEGER = {
    "D3D12_GPU_VIRTUAL_ADDRESS": "typedef UINT64 (vkd3d_d3d12.h)",
    "DXGI_USAGE":                "typedef UINT (vkd3d_dxgi.h:231)",
}

# FOUR-BYTE by-value types, split by signedness -- winecom_slot::dwordmask /
# dwordsign.  A 32-bit argument is clean in a register (x86-64 zero-extends
# 32-bit register writes) but NOT on the stack, where the guest's 32-bit
# store leaves the slot's upper half stale.  [MEASURED] on THIS surface:
# ID3D12Device::CopyDescriptors passes the descriptor heap type as argument
# seven -- a stack slot -- and vkd3d's 64-bit switch missed an enum whose low
# half said 0, printing "Unhandled descriptor heap type 0" 32768 times per
# scene while every descriptor copy silently did nothing.  The roster's enums
# join the dword CLASS at run time; their SIGNEDNESS is asked of clang per
# declared type, never assumed -- see below.
#
# THE SIGN COLUMN IS CLANG'S, NOT THESE LISTS'.  The two name lists decide
# only that a type is dword-WIDE (and crosscheck_width64 makes clang confirm
# both the width and the sign they imply); whether the runtime sign- or
# zero-extends comes from the oracle's own probe of the declared type,
# exactly the way the widths are derived.  "An enum is int underneath" was a
# lie this file used to tell: DXGI_COLOR_SPACE_TYPE carries the enumerator
# DXGI_COLOR_SPACE_CUSTOM = 0xffffffff, which forces its underlying type
# UNSIGNED in GNU C -- the C the native callee is compiled as -- so the
# ELFv2 callee is entitled to a ZERO-extended register, and the blanket
# sign-extension handed vkd3d 0xFFFFFFFFFFFFFFFF where the ABI demands
# 0x00000000FFFFFFFF (IDXGISwapChain3::SetColorSpace1).  An enum whose
# underlying type really is signed (a negative enumerator) still
# sign-extends, because clang says so, not because a rule guessed.
#
# BOOL and WINBOOL sit in the SIGNED list: both are `typedef int` underneath,
# clang measures them signed, and the dxvk sibling surface has always
# sign-extended them -- identical for every value a well-formed BOOL holds,
# and the ELFv2-correct extension for any other int value.
#
# Every by-value type must land in exactly one of: NARROW_BYVAL, these two,
# QWORD_BYVAL, BYVAL_AGGREGATE -- a byval_ok type with no width is refused,
# because "probably 32 bits" is how a stack slot's stale upper half reaches a
# callee that trusts it.
DWORD_UNSIGNED = frozenset("""
    UINT ULONG DWORD UINT32 DXGI_USAGE unsigned
""".split())
DWORD_SIGNED = frozenset("""
    INT LONG INT32 HRESULT BOOL WINBOOL int long
""".split())
QWORD_BYVAL = frozenset("""
    UINT64 INT64 SIZE_T SSIZE_T LONGLONG ULONGLONG ULONG64 LONG64 QWORD
    HANDLE HWND HMODULE HMONITOR ULONG_PTR DWORD_PTR UINT_PTR LONG_PTR
    INT_PTR D3D12_GPU_VIRTUAL_ADDRESS
""".split())

# By-value integers NARROWER THAN 32 BITS: (bytes, signed).  MS-x64 leaves
# the upper bits of the register UNDEFINED and makes ignoring them the
# CALLEE's job; ELFv2 makes extending them the CALLER's job and a ppc64
# callee trusts that it happened.  The runtime does the extension
# (struct winecom_slot::narrowmask); this table tells it width and
# signedness.  [MEASURED] on the MF surface: IWMSyncReader::GetStreamSelected
# read a guest-passed WORD 1 as 0x40000001.  This roster has UINT8 parameters
# (ID3D12StateObjectProperties1 and friends), so unlike the DXVK copy the
# masks are emitted here, not merely recognised.
NARROW_BYVAL = {
    "WORD":    (2, False), "USHORT": (2, False), "UINT16":  (2, False),
    "SHORT":   (2, True),  "INT16":  (2, True),
    "BYTE":    (1, False), "UCHAR":  (1, False), "UINT8":   (1, False),
    "BOOLEAN": (1, False),
    "CHAR":    (1, True),  "INT8":   (1, True),
}

NARROW_RAW = (
    (r'\bunsigned\s+short\b',  (2, False)),
    (r'\bsigned\s+short\b',    (2, True)),
    (r'\bunsigned\s+char\b',   (1, False)),
    (r'\bsigned\s+char\b',     (1, True)),
    (r'\bshort\b',              (2, True)),
    (r'\bchar\b',               (1, True)),
)


def narrow_of(p):
    """(bytes, signed) for a by-value parameter narrower than 32 bits, else None."""
    if p.base in NARROW_BYVAL:
        return NARROW_BYVAL[p.base]
    for pat, w in NARROW_RAW:
        if re.search(pat, p.raw):
            return w
    return None


# --------------------------------------------------------------------------
# the i386 width oracle -- what the OTHER guest's ABI says each by-value
# type measures.
#
# The 64-bit masks above answer "how wide is this argument on the x86-64
# guest", and they can afford to be name lists because every name was checked
# against that one ABI.  The i386 guest gets no such shortcut: the 8-byte
# class SPLITS over there.  HANDLE, HWND, SIZE_T, ULONG_PTR and every pointer
# shrink to 4 bytes -- ONE stdcall stack slot -- while UINT64 and
# D3D12_GPU_VIRTUAL_ADDRESS stay 8 bytes and TWO, so ID3D11Fence::Signal's
# value sits at a different stack offset than any pointer-taking neighbour,
# and a lane that guessed from the 64-bit tables would read half fence-value,
# half whatever came next: plausible, wrong, silent.  A name list is exactly
# how those two widths ended up in one bucket, so the widths are asked of
# clang itself, per declared type, for BOTH guest targets -- the
# ppc64le/dxvk/layout32.py mechanism: compile a sizeof array with -S, read
# the .long values back out of the assembly, never execute anything.  The
# x86-64 answers double as a lie detector for the name lists above: any
# disagreement stops generation, because it would mean the committed 64-bit
# tables were already wrong.
#
# The oracle publishes into `struct winecom_slot::qwordmask` (bit i: that
# parameter is TWO 4-byte slots) and WINECOM_F_RET_QWORD (the return is
# EDX:EAX, not EAX), both guarded by WINECOM_F_I386_GEOM -- the xmask rule: a
# table that predates the field reads as "no geometry", never as "all
# narrow".  And the emitted geometry is CHECKED against a second opinion
# before it may be written: every covered slot is re-declared
# __attribute__((stdcall)) verbatim from the roster and clang's own @N symbol
# decoration -- the callee-popped byte count, computed by clang laying out
# the whole frame -- must equal what argc and qwordmask predict.
# --------------------------------------------------------------------------

I386_TARGET = "i386-windows-gnu"
AMD64_TARGET = "x86_64-windows-gnu"

# Tokens that can end a multi-word builtin type, so the name stripper below
# knows "unsigned int" carries no parameter name while "UINT64 value" does.
C_TYPE_TAIL = frozenset(
    "int char short long unsigned signed float double".split())


def byval_spelling(raw):
    """The C type expression of a star-free, bracket-free declaration: the
    declared text with qualifiers and the parameter NAME stripped.  The
    result is handed to clang, which ERRORS on anything this got wrong
    rather than mis-measuring it -- the stripper cannot silently lie."""
    t = re.sub(r'\b(const|volatile)\b', ' ', " ".join(raw.split()))
    toks = t.split()
    if len(toks) > 1 and toks[-1] not in C_TYPE_TAIL:
        toks = toks[:-1]
    return " ".join(toks)


class I386Oracle:
    """sizeof/signedness/floating-point-ness per type spelling, per guest
    target, from clang.

    `sign_names`: single-token spellings signedness may be asked of (the
    integer-class roster); a struct cannot be cast from -1, so everything
    else gets a constant 0 in the sign column and nobody reads it.  The
    FP column has no such gate: it is a _Generic over an unevaluated
    dereference, which compiles for any object type and answers 1 only for
    float/double/long double -- the types i386 returns in x87 ST(0) rather
    than EAX, which is why slot_geometry refuses to publish a return
    register class for them.

    `fallback_prelude`: a SECOND header world for names the surface's own
    headers never declare.  The d3d12 roster's DXGI rows carry enums
    (DXGI_MEMORY_SEGMENT_GROUP and friends) that exist in Wine's dxgi
    headers but in no vkd3d header; the two worlds cannot share one
    translation unit (both define the interfaces), so a name the first TU
    reports UNDECLARED is retried in the second, and a name neither world
    declares stops generation.  Nothing is ever guessed on the way."""

    def __init__(self, clang, prelude, incdirs, sign_names, tag,
                 fallback_prelude="", fallback_incdirs=None):
        self.clang = clang
        self.prelude = prelude
        self.fallback_prelude = fallback_prelude
        self.incdirs = [d for d in incdirs if d]
        self.fallback_incdirs = ([d for d in fallback_incdirs if d]
                                 if fallback_incdirs else self.incdirs)
        self.sign_names = set(sign_names)
        self.tag = tag
        self.cache = {}          # spelling -> (w32, w64, signed, fp)
        self.fallback_ids = set()   # identifiers only the fallback declares

    def _sign_ok(self, s):
        toks = s.split()
        return (all(t in C_TYPE_TAIL for t in toks)
                or (len(toks) == 1 and toks[0] in self.sign_names))

    UNDECLARED = re.compile(
        r"(?:use of undeclared identifier|unknown type name)\s+'(\w+)'")

    def _run(self, src_text, target, what, fatal=True, incdirs=None):
        """-> assembly text, or (None, stderr) with fatal=False."""
        import subprocess
        import tempfile
        with tempfile.TemporaryDirectory() as td:
            c = os.path.join(td, "winecom_%s.c" % what)
            with open(c, "w") as fh:
                fh.write(src_text)
            asm = c[:-2] + ".s"
            cmd = ([self.clang, "-target", target, "-O0", "-S", "-o", asm,
                    "-nostdlibinc"]
                   + ["-I" + d for d in (incdirs or self.incdirs)] + [c])
            r = subprocess.run(cmd, capture_output=True, text=True)
            if r.returncode:
                if not fatal:
                    return None, r.stderr
                sys.exit("gen_winecom: the %s %s probe does not compile for "
                         "%s, and a width that cannot be measured must not "
                         "be guessed.\ncommand: %s\n%s"
                         % (self.tag, what, target, " ".join(cmd),
                            r.stderr[:4000]))
            with open(asm) as fh:
                return fh.read(), None

    def _width_src(self, spellings, prelude):
        src = prelude + "const unsigned int winecom_probe[] = {\n"
        for s in spellings:
            sign = ("(unsigned int)((%s)-1 < (%s)0)" % (s, s)
                    if self._sign_ok(s) else "0u")
            # The dereference is UNEVALUATED (_Generic reads only the type),
            # so this compiles for any object type -- structs included --
            # and cannot be fooled by a typedef the way a name list can.
            fp = ("(unsigned int)_Generic(*(%s *)0, float: 1, double: 1, "
                  "long double: 1, default: 0)" % s)
            src += "    (unsigned int)sizeof(%s), %s, %s,\n" % (s, sign, fp)
        src += "};\n"
        return src

    def _measure_batch(self, todo, prelude, incdirs=None):
        vals = {}
        for target in (I386_TARGET, AMD64_TARGET):
            text, _ = self._run(self._width_src(todo, prelude), target,
                                "width", incdirs=incdirs)
            m = re.search(r'^_?winecom_probe:\n((?:\s+\.long\s+\d+[^\n]*\n)+)',
                          text, re.M)
            got = ([int(x) for x in re.findall(r'\.long\s+(\d+)', m.group(1))]
                   if m else [])
            if len(got) != 3 * len(todo):
                sys.exit("gen_winecom: read %d width-probe values for %d "
                         "types from the %s %s assembly; the compiler did "
                         "not answer what the source asked"
                         % (len(got), len(todo), self.tag, target))
            vals[target] = got
        for i, s in enumerate(todo):
            s32, g32, f32 = vals[I386_TARGET][3 * i:3 * i + 3]
            s64, g64, f64 = vals[AMD64_TARGET][3 * i:3 * i + 3]
            if g32 != g64:
                sys.exit("gen_winecom: %s is signed on one guest and "
                         "unsigned on the other; no marshal class expresses "
                         "that and this generator will not pick a side" % s)
            if f32 != f64:
                sys.exit("gen_winecom: %s is floating-point on one guest "
                         "and not the other, which cannot happen for a type "
                         "both targets parse; the probe is broken, not the "
                         "type" % s)
            self.cache[s] = (s32, s64, bool(g32), bool(f32))

    def measure(self, spellings):
        todo = sorted(set(spellings) - set(self.cache))
        if not todo:
            return
        # Partition: names the surface headers do not declare move to the
        # fallback world.  The trial compile is i386-only and non-fatal; the
        # real measurements below are fatal, so nothing unmeasured survives.
        main_set = list(todo)
        fb_set = []
        for _ in range(8):
            _, err = self._run(self._width_src(main_set, self.prelude),
                               I386_TARGET, "width", fatal=False)
            if err is None:
                break
            missing = set(self.UNDECLARED.findall(err))
            moved = [s for s in main_set
                     if missing & set(re.findall(r'\w+', s))]
            if not missing or not moved or not self.fallback_prelude:
                sys.exit("gen_winecom: the %s width probe does not compile "
                         "and no fallback header world declares what is "
                         "missing:\n%s" % (self.tag, err[:4000]))
            self.fallback_ids |= missing
            fb_set += moved
            main_set = [s for s in main_set if s not in moved]
        if main_set:
            self._measure_batch(main_set, self.prelude)
        if fb_set:
            self._measure_batch(sorted(fb_set), self.fallback_prelude,
                                self.fallback_incdirs)

    def width32(self, s):
        return self.cache[s][0]

    def width64(self, s):
        return self.cache[s][1]

    def is_signed(self, s):
        return self.cache[s][2]

    def is_fp(self, s):
        return self.cache[s][3]

    def check_stdcall_frames(self, entries, alias_map):
        """entries: (key, params, argc, qwordmask) for every slot whose
        geometry will be published.  Declares each one stdcall, verbatim
        from the roster, and requires clang's @N callee-pop decoration to
        equal 4*argc + 4*popcount(qwordmask).  Any disagreement stops
        generation: two independent derivations of the same frame may not
        differ and both still be trusted."""
        if not entries:
            return 0

        def decl_lines(batch, prelude):
            lines = [prelude]
            for n, (key, params, argc, qm) in enumerate(batch):
                ptext = ""
                for praw in params:
                    praw = " ".join(praw.split())
                    for old, new in alias_map.items():
                        praw = re.sub(r'\b%s\b' % re.escape(old), new, praw)
                    ptext += ", " + praw
                lines.append("void __attribute__((stdcall)) winecom_chk_%d"
                             "(void *wcthis%s);" % (n, ptext))
            lines.append("const void *winecom_chk_refs[] = {")
            lines += ["    (const void *)&winecom_chk_%d," % n
                      for n in range(len(batch))]
            lines.append("};")
            return "\n".join(lines) + "\n"

        # Slots spelled with names only the fallback world declares are
        # checked THERE -- same ABI, different header copy.  The partition
        # is discovered the same way measure() discovers it: clang says
        # which identifiers the main world lacks, and the entries naming
        # them move over; nothing unmoved is left unchecked.
        main_e = list(entries)
        fb_e = [e for e in main_e
                if set(re.findall(r'\w+', " ".join(e[1])))
                & self.fallback_ids]
        main_e = [e for e in main_e if e not in fb_e]
        text = None
        for _ in range(8):
            if not main_e:
                text = ""
                break
            text, err = self._run(decl_lines(main_e, self.prelude),
                                  I386_TARGET, "frame", fatal=False)
            if err is None:
                break
            missing = set(self.UNDECLARED.findall(err))
            moved = [e for e in main_e
                     if missing & set(re.findall(r'\w+', " ".join(e[1])))]
            if not missing or not moved or not self.fallback_prelude:
                sys.exit("gen_winecom: the %s frame probe does not compile "
                         "and no fallback header world declares what is "
                         "missing:\n%s" % (self.tag, err[:4000]))
            fb_e += moved
            main_e = [e for e in main_e if e not in moved]
        found = {}
        for batch, text_ready, prelude, what, incs in (
                (main_e, text, self.prelude, "frame", None),
                (fb_e, None, self.fallback_prelude, "frame_fb",
                 self.fallback_incdirs)):
            if not batch:
                continue
            if text_ready is None:
                text_ready, _ = self._run(decl_lines(batch, prelude),
                                          I386_TARGET, what, incdirs=incs)
            got = {int(a): int(b)
                   for a, b in re.findall(r'winecom_chk_(\d+)@(\d+)',
                                          text_ready)}
            for n, e in enumerate(batch):
                found[id(e)] = got.get(n)
        bad = []
        for e in entries:
            key, params, argc, qm = e
            want = 4 * argc + 4 * bin(qm).count("1")
            got = found.get(id(e))
            if got != want:
                bad.append("  %s: table geometry says the callee pops %d "
                           "bytes, clang's stdcall decoration says %s"
                           % (key, want, got))
        if bad:
            sys.exit("gen_winecom: the emitted i386 geometry DISAGREES with "
                     "clang's own frame layout for %d slot(s); refusing to "
                     "write a table either half of the toolchain would "
                     "contradict:\n%s" % (len(bad), "\n".join(bad)))
        return len(entries)


def slot_geometry(slot, oracle):
    """-> (qwordmask, ret_qword, unproven_reason).  The i386 stdcall frame of
    one slot, independent of its marshal classification: EVERY slot needs
    geometry -- a refused slot still has to pop the right number of bytes
    before it can so much as answer E_NOTIMPL.  An 8-byte parameter past bit
    15 of qwordmask stops generation outright: the alternative is a silently
    truncated mask, the exact bug class this field exists to prevent."""
    qm = 0
    unproven = None
    for i, praw in enumerate(slot["params"]):
        p = Param(praw)
        if p.stars:              # pointers and decayed arrays: one 4-byte slot
            continue
        w = oracle.width32(byval_spelling(p.raw))
        if w == 8:
            if i >= 16:
                sys.exit("gen_winecom: %s::%s has an 8-byte by-value "
                         "parameter in argument position %d, past the "
                         "sixteen bits qwordmask covers.  Widen the mask; "
                         "truncating it silently is not an option."
                         % (slot["owner"], slot["name"], i + 1))
            qm |= 1 << i
        elif w not in (1, 2, 4):
            unproven = ("by-value %s measures %d bytes on the i386 guest, "
                        "which qwordmask cannot spell (one or two 4-byte "
                        "slots)" % (byval_spelling(p.raw), w))
    ret_q = False
    rraw = slot["ret"]
    if rraw != "void" and not slot.get("aggregate_return"):
        rp = Param(rraw)
        if rp.stars == 0:
            rsp = byval_spelling(rraw)
            if oracle.is_fp(rsp):
                # i386 returns float and double in x87 ST(0).  The contract
                # these fields publish can spell EAX and EDX:EAX and nothing
                # else, so an FP return gets NO geometry and a 32-bit lane
                # fails closed on it -- the alternative is a consumer that
                # reads garbage out of EAX and leaves ST(0) unpopped, NaN
                # after eight calls.  Asked of clang (the _Generic probe),
                # not of a token list: a typedef spelling of float must not
                # slip through as "EAX".
                unproven = ("the %s return value is floating-point, which "
                            "i386 returns in x87 ST(0); neither EAX nor "
                            "EDX:EAX describes it, so no geometry is "
                            "published and a 32-bit lane must fail closed"
                            % rsp)
            else:
                rw = oracle.width32(rsp)
                if rw == 8:
                    ret_q = True
                elif rw not in (1, 2, 4):
                    unproven = ("the %s return value measures %d bytes on "
                                "the i386 guest, which is neither EAX nor "
                                "EDX:EAX" % (rsp, rw))
    return qm, ret_q, unproven


def collect_spellings(ifaces):
    """Every by-value parameter and by-value return spelling in the roster,
    so the oracle can measure them in one batch."""
    sp = set()
    for iface in ifaces.values():
        for s in iface["slots"] or ():
            for praw in s["params"]:
                p = Param(praw)
                if not p.stars:
                    sp.add(byval_spelling(p.raw))
            rraw = s["ret"]
            if rraw != "void" and not s.get("aggregate_return"):
                if Param(rraw).stars == 0:
                    sp.add(byval_spelling(rraw))
    return sp


def crosscheck_width64(ifaces, oracle, dword_class):
    """The lie detector: every by-value parameter the NAME LISTS above claim
    a 64-bit width for must measure exactly that under clang's
    x86_64-windows-gnu -- AND every name the two sign lists claim a
    signedness for must measure exactly that signedness.  The width half
    caught nothing for years while the sign half did not exist, and the
    DXGI_COLOR_SPACE_TYPE sign lie stood certified; now a name misfiled in
    DWORD_SIGNED/DWORD_UNSIGNED stops generation the same way a misfiled
    width does.  (Enums make no name-list sign claim at all -- their
    signedness is read straight off clang, so there is nothing to
    cross-check; the g32==g64 gate in the oracle already pins it per
    target.)  A disagreement means the committed 64-bit tables were already
    wrong, and generation stops rather than perpetuating it.  Mirrors
    classify()'s own precedence: narrow, `long long`, dword, qword,
    aggregate."""
    bad = []
    for iface in ifaces.values():
        for s in iface["slots"] or ():
            for i, praw in enumerate(s["params"]):
                p = Param(praw)
                if p.stars:
                    continue
                narrow = narrow_of(p)
                if narrow:
                    expected = narrow[0]
                elif re.search(r'\blong\s+long\b', p.raw):
                    expected = 8
                elif p.base in dword_class:
                    expected = 4
                elif p.base in QWORD_BYVAL:
                    expected = 8
                elif p.base in BYVAL_AGGREGATE:
                    expected = 8
                else:
                    continue     # no width claim; classify() refuses these
                sp = byval_spelling(p.raw)
                got = oracle.width64(sp)
                if got != expected:
                    bad.append("  %s::%s arg %d (%s): name lists say %d "
                               "byte(s), clang's x86-64 layout says %d"
                               % (s["owner"], s["name"], i + 1, p.raw,
                                  expected, got))
                if p.base in DWORD_UNSIGNED or p.base in DWORD_SIGNED:
                    claimed = p.base in DWORD_SIGNED
                    if oracle.is_signed(sp) != claimed:
                        bad.append("  %s::%s arg %d (%s): the sign lists "
                                   "say %s, clang says %s"
                                   % (s["owner"], s["name"], i + 1, p.raw,
                                      "signed" if claimed else "unsigned",
                                      "signed" if oracle.is_signed(sp)
                                      else "unsigned"))
    if bad:
        sys.exit("gen_winecom: the 64-bit width/sign NAME LISTS disagree "
                 "with clang for %d parameter(s); the committed tables "
                 "would already be wrong and this generator will not add "
                 "to that:\n%s" % (len(bad), "\n".join(sorted(set(bad)))))


# 8-byte aggregates that are ONE integer register on both the MS-x64 and the
# ELFv2 side.  Each is here because its layout was checked in the header.
BYVAL_AGGREGATE = {
    "LUID": "{ DWORD LowPart; LONG HighPart; } -- 8 bytes, one register on "
            "both ABIs",
    "D3D12_CPU_DESCRIPTOR_HANDLE": "{ SIZE_T ptr; } -- 8 bytes, one register "
                                   "on both ABIs (vkd3d_d3d12.h:2847)",
    "D3D12_GPU_DESCRIPTOR_HANDLE": "{ UINT64 ptr; } -- 8 bytes, one register "
                                   "on both ABIs (vkd3d_d3d12.h:2850)",
}

# By-value aggregates the two ABIs pass DIFFERENTLY, refused by name with the
# mechanism rather than with the generic "not provably integer-class".
BYVAL_ABI_SPLIT = {
    "GUID":
        "takes a GUID BY VALUE, and the two ABIs disagree about how.  MS-x64 "
        "passes any aggregate that is not 1/2/4/8 bytes by a hidden POINTER "
        "to a caller-allocated temporary; ELFv2 passes 16 bytes in TWO GPRs. "
        "Needs a hand-written slot that dereferences, not a marshal class",
    "D3D12_NODE_ID":
        "takes a D3D12_NODE_ID ({ LPCWSTR Name; UINT ArrayIndex; }, 16 "
        "bytes) by value; a hidden pointer on one ABI and two registers on "
        "the other -- see the GUID case",
}

# Pointer spellings that are pointers without a `*` in the source text.
POINTER_TYPEDEFS = {
    "LPSTR": "char", "LPCSTR": "char", "LPWSTR": "WCHAR", "LPCWSTR": "WCHAR",
    "PWSTR": "WCHAR", "PCWSTR": "WCHAR",
    "LPVOID": "void", "PVOID": "void", "LPCVOID": "void",
    "REFIID": "GUID", "REFGUID": "GUID", "REFCLSID": "GUID",
}

# Interface names the headers spell differently from the roster.  ID3DBlob
# is widl's alias for ID3D10Blob -- same IID 8ba5fb08 -- and the roster
# carries the latter; without the alias every `ID3DBlob **` out-parameter
# would refuse as an unprovable pointer-to-pointer.
IFACE_ALIASES = {
    "ID3DBlob": "ID3D10Blob",
}

# Pointer-to-pointer parameters that really are blocks of plain memory, so
# CA_PASS is the right answer: the callee writes a HOST address into
# guest-visible storage, and on this port guest memory IS host memory.  An
# ALLOW-list, because the failure it guards is silent.
PLAIN_PP = {
    "void": "only reachable via VOID_PP_IS_MEMORY below",
    "D3D12_VERSIONED_ROOT_SIGNATURE_DESC":
        "the deserializer hands back a pointer to its own parsed copy -- "
        "plain data it owns",
    "DXGI_FORMAT":
        "the castable-formats arrays of the Device12 CreateCommittedResource3 "
        "family -- a const array of enums, plain data in",
}

FLOAT_TOKENS = re.compile(r'\b(FLOAT|float|double|DOUBLE)\b')

# Structs that carry an interface pointer behind a `const void *` payload the
# transitive scan below cannot see through.  Named here so a refusal states
# the mechanism.  Every rostered slot that takes one is a HAND_SLOT today
# (the stream walker and the state-object walker in dlls/d3d12/main.c); the
# dict stays so a FUTURE slot that grows one of these payloads refuses with
# the mechanism named instead of passing a hidden proxy through.
CARRIER_STRUCTS = {
    "D3D12_PIPELINE_STATE_STREAM_DESC":
        "a subobject stream whose ROOT_SIGNATURE subobject is an "
        "ID3D12RootSignature* behind a void*, invisible to any signature or "
        "struct scan; dlls/d3d12/main.c's hand_create_pipeline_state walks "
        "it for the slots that have been measured to matter",
    "D3D12_STATE_OBJECT_DESC":
        "DXR state-object subobjects hide interface pointers "
        "(D3D12_GLOBAL_ROOT_SIGNATURE, D3D12_EXISTING_COLLECTION_DESC) "
        "behind const void*; needs a hand-written walker",
}

# Function pointers a guest would pass BY VALUE: guest x86-64 code entered as
# ppc64.  Refused by name; the day one matters it needs the guest-callback
# trampoline, not a marshal class.
GUEST_CODE_BYVAL = {
    "PFN_DESTRUCTION_CALLBACK":
        "takes a guest function pointer by value; native code calling it "
        "would execute x86-64 bytes as ppc64.  Needs the guest-callback "
        "trampoline (ppc64le/thunks), not a marshal class",
}

# Completion-event slots: the by-value HANDLE is a Wine event the native side
# would WAIT ON or SIGNAL, which vkd3d's unix half cannot do.  Classed
# WINECOM_CA_EVENT -- the runtime serves the NULL (blocking) form and refuses
# a real handle with the reason, instead of corrupting.  Keyed
# "Owner::Method" so ID3D12Fence1 and every later Device inherit the class.
# IDXGIFactory2's RegisterStereoStatusEvent/RegisterOcclusionStatusEvent are
# deliberately NOT here: the committed table always passed them (vkd3d's
# swapchain ignores stereo/occlusion registration) and this regeneration
# changes no served row's meaning.
EVENT_SLOTS = frozenset((
    "ID3D12Fence::SetEventOnCompletion",
    "ID3D12Device1::SetEventOnMultipleFenceCompletion",
    "ID3D12Device6::SetBackgroundProcessingMode",
    "IDXGIAdapter3::RegisterHardwareContentProtectionTeardownStatusEvent",
    "IDXGIAdapter3::RegisterVideoMemoryBudgetChangeNotificationEvent",
    "IDXGIFactory7::RegisterAdaptersChangedEvent",
))

# --------------------------------------------------------------------------
# Hand-written slots.  Keyed "Owner::Method" so an inherited slot gets the
# same hand function in every derived interface's table -- ResourceBarrier
# at slot 26 of ID3D12GraphicsCommandList is slot 26 of GraphicsCommandList10
# too, and the hand function forwards by slot number.  The C functions live
# in dlls/d3d12/main.c and the order here IS the hand_funcs[] order there;
# the first three predate this generator and their indices are frozen.
# --------------------------------------------------------------------------
HAND_SLOTS = [
    ("ID3D12GraphicsCommandList::ResourceBarrier", "hand_resource_barrier"),
    ("ID3D12Device::CreateComputePipelineState",   "hand_create_compute_pso"),
    ("IDXGIFactory2::CreateSwapChainForHwnd",      "hand_create_swapchain_for_hwnd"),
    # D3D12_GRAPHICS_PIPELINE_STATE_DESC's one interface member is
    # pRootSignature; the walker copies the desc and unwraps it, the same
    # shape hand_create_compute_pso has.
    ("ID3D12Device::CreateGraphicsPipelineState",  "hand_create_graphics_pso"),
    # The modern PSO path: a subobject stream (see CARRIER_STRUCTS).  The
    # walker mirrors vkd3d's own vkd3d_pipeline_state_desc_from_d3d12_stream_desc
    # -- type enum, naturally-aligned payload, stride padded to pointer size
    # -- and unwraps the ROOT_SIGNATURE subobject in a copy.
    ("ID3D12Device2::CreatePipelineState",         "hand_create_pipeline_state"),
    # The texture-upload path: two D3D12_TEXTURE_COPY_LOCATIONs whose
    # pResource members are proxies; the walker copies both one-struct
    # arguments and unwraps them.
    ("ID3D12GraphicsCommandList::CopyTextureRegion", "hand_copy_texture_region"),
    # The FLOAT-by-value slot every renderer calls each frame.  The refusal
    # this replaces cost Cyberpunk 2077 its depth clears: every 3D pass then
    # tested against stale depth/HTILE and the whole scene speckled
    # ([MEASURED] 2026-08-19, the -benchmark A/B).  The walker lifts Depth
    # out of guest XMM3 and crosses it as raw bits through the unixlib's
    # typed-float call (FP_SHAPE_CLEAR_DSV).
    ("ID3D12GraphicsCommandList::ClearDepthStencilView", "hand_clear_dsv"),
    # The pipeline-library load path: the create walkers' desc walks behind
    # a library name.  Cyberpunk 2077 hits both of the first pair on every
    # boot ([MEASURED] 2026-08-19 run log); refused, its pipeline cache
    # could never load and every PSO was rebuilt.
    ("ID3D12PipelineLibrary::LoadGraphicsPipeline", "hand_load_graphics_pipeline"),
    ("ID3D12PipelineLibrary::LoadComputePipeline",  "hand_load_compute_pipeline"),
    ("ID3D12PipelineLibrary1::LoadPipeline",        "hand_load_pipeline"),
    # The remaining FLOAT-by-value frames, hand_clear_dsv's shape
    # (FP_SHAPE_DEPTH_BOUNDS / FP_SHAPE_DEPTH_BIAS).
    ("ID3D12GraphicsCommandList1::OMSetDepthBounds", "hand_om_set_depth_bounds"),
    ("ID3D12GraphicsCommandList9::RSSetDepthBias",   "hand_rs_set_depth_bias"),
    # Render passes and enhanced barriers: interface pointers inside the
    # resolve params / barrier arrays, shallow-copied and unwrapped the
    # way hand_resource_barrier always did it.
    ("ID3D12GraphicsCommandList4::BeginRenderPass",  "hand_begin_render_pass"),
    ("ID3D12GraphicsCommandList7::Barrier",          "hand_barrier_groups"),
    # The DXR state-object walker CARRIER_STRUCTS describes: subobject
    # payload copies, proxy unwraps, association-pointer remap into the
    # copy.  With these two served, VKD3D_CONFIG=nodxr stops being the only
    # honest answer on hardware whose driver exposes ray tracing.
    ("ID3D12Device5::CreateStateObject",             "hand_create_state_object"),
    ("ID3D12Device7::AddToStateObject",              "hand_add_to_state_object"),
]

# Refusals decided here rather than derived.  Keyed "Owner::Method".
REFUSALS = {}

# void** out-parameters that are blocks of memory rather than untyped
# interface pointers, checked one by one against the headers.  Everything
# else with a bare void** is refused: the default has to be the safe one.
VOID_PP_IS_MEMORY = frozenset((
    "ID3D12Resource::Map",                    # the mapped bytes
))


# --------------------------------------------------------------------------
# struct bodies -- which ones reach an interface pointer, transitively
# --------------------------------------------------------------------------

TYPEDEF_HEAD = re.compile(r'typedef\s+(struct|union)\b[^{;]*\{')
FWD_IFACE = re.compile(r'typedef\s+struct\s+(I\w+)\s+\1\s*;')


def scan_structs(paths, iface_names):
    """-> (bearing, why).

    `bearing` is the set of struct type names that reach an interface pointer
    through any member chain.  Brace-MATCHED, not regexed: these headers nest
    nameless unions inside D3D12_RESOURCE_BARRIER and
    D3D12_TEXTURE_COPY_LOCATION, and a non-greedy regex records the inner
    union under __C89_NAMELESSUNIONNAME and loses the outer struct entirely.
    Every identifier in the whole body counts as a member type --
    over-approximating costs a refusal; under-approximating hands vkd3d a
    guest proxy pointer."""
    members = {}
    ifaces_seen = set(iface_names)
    for path in paths:
        with open(path, errors="replace") as fh:
            text = fh.read()
        ifaces_seen |= set(FWD_IFACE.findall(text))
        for m in TYPEDEF_HEAD.finditer(text):
            depth, i = 1, m.end()
            while i < len(text) and depth:
                if text[i] == '{':
                    depth += 1
                elif text[i] == '}':
                    depth -= 1
                i += 1
            body = text[m.end():i - 1]
            tail = re.match(r'\s*(\w+)\s*;', text[i:])
            if not tail:
                continue
            name = tail.group(1)
            if name in members:
                continue
            # SORTED: the `why` chain below lands in the refusal TEXT of the
            # generated header, and set order would make the committed file
            # depend on PYTHONHASHSEED.
            members[name] = sorted(
                set(re.findall(r'\b(\w+)\s*\*', body)) |
                set(re.findall(r'\b(\w+)\s+\w+\s*(?:\[|;|:)', body)))

    hit, why = {}, {}
    for name in members:
        seen, stack = set(), [(name, [])]
        while stack:
            cur, path = stack.pop()
            if cur in seen:
                continue
            seen.add(cur)
            for m in members.get(cur, ()):
                if m in ifaces_seen:
                    hit[name] = True
                    why[name] = " -> ".join(path + [cur, m])
                    stack = []
                    break
                if m in members:
                    stack.append((m, path + [cur]))
    return set(hit), why


# --------------------------------------------------------------------------
# parameter parsing
# --------------------------------------------------------------------------

class Param:
    __slots__ = ("raw", "base", "stars", "inner_const", "array", "name")

    def __init__(self, raw):
        self.raw = " ".join(raw.split())
        t = self.raw
        self.array = bool(re.search(r'\[', t))
        t = re.sub(r'\[[^\]]*\]', '', t).strip()
        # `Iface *const *p`: the INNER pointer is const, which is how these
        # headers spell an INPUT array.
        self.inner_const = bool(re.search(r'\*\s*const\s*\*', t))
        t = re.sub(r'\bconst\b', ' ', t)
        toks = t.replace('*', ' * ').split()
        self.stars = toks.count('*')
        toks = [x for x in toks if x != '*']
        self.base = toks[0] if toks else ''
        self.name = toks[-1] if len(toks) > 1 else ''
        if self.base in POINTER_TYPEDEFS:
            self.stars += 1
            self.base = POINTER_TYPEDEFS[self.base]
        if self.array:
            self.stars += 1

    def is_riid(self):
        return re.match(r'^(REFIID|REFGUID|REFCLSID)\b', self.raw) is not None


def resolve_alias(p):
    if p.base in IFACE_ALIASES:
        p.base = IFACE_ALIASES[p.base]


# The roster spells parameters in vkd3d's snake_case: command_list_count,
# num_objects, buffer_count, region_count.
COUNT_RE = re.compile(r'^(num_?\w*|\w*_?count\w*)$', re.IGNORECASE)


def find_count(params, idx):
    """Index of the by-value count that governs the array at `idx`: nearest
    preceding, else nearest following.  None if there is none."""
    cands = [i for i, p in enumerate(params)
             if p.stars == 0 and p.base in ("UINT", "UINT32", "unsigned",
                                            "int", "DWORD", "ULONG")
             and COUNT_RE.match(p.name or '')]
    before = [i for i in cands if i < idx]
    after = [i for i in cands if i > idx]
    if before:
        return before[-1]
    if after:
        return after[0]
    return None


# --------------------------------------------------------------------------
# classification
# --------------------------------------------------------------------------

CA = dict(PASS=0, IFACE_IN=1, RIID=2, PPV_OUT=3, RET_PTR=4, EVENT=5,
          IFACE_ARR_IN=6, IFACE_OUT_STATIC=7, IFACE_ARR_OUT_STATIC=8)
CA_NAME = {v: "WINECOM_CA_" + k for k, v in CA.items()}


class Refused(Exception):
    pass


class Plan:
    """What classify() proved about one slot.  No fp_reason / no reverse
    lane on this surface: the invoker crosses a unixlib and the surface
    lacks WINECOM_SF_REVERSE, so a by-value float is a plain Refused."""

    __slots__ = ("cls", "xaux", "caux", "aux", "aux2", "xmask",
                 "narrowmask", "narrowwide", "narrowsign", "narrow_params",
                 "dwordmask", "dwordsign", "ret_via_arg")

    def __init__(self):
        self.cls = self.xaux = self.caux = None
        self.aux = self.aux2 = 0
        self.xmask = 0
        self.narrowmask = self.narrowwide = self.narrowsign = 0
        self.narrow_params = []
        self.dwordmask = self.dwordsign = 0
        self.ret_via_arg = False


def classify(key, slot, ifaces, iface_index, byval_ok, dword_class,
             bearing, why_bearing, oracle):
    """-> Plan, or raise Refused(reason)."""
    params = [Param(p) for p in slot["params"]]
    for p in params:
        resolve_alias(p)
    n = len(params)
    cls = [CA["PASS"]] * n
    xaux = [0] * n
    caux = [0] * n
    aux = aux2 = 0
    plan = Plan()

    if slot.get("aggregate_return"):
        # widl's __ret pointer: the caller's temporary, always parameter 0;
        # the runtime answers RAX = args[1] (WINECOM_F_RET_VIA_ARG).
        if not params or params[0].name != "__ret":
            raise Refused(
                "is marked aggregate_return but its first parameter is not "
                "the widl __ret pointer; the roster and this generator "
                "disagree and the safe answer is no")
        cls[0] = CA["RET_PTR"]
        plan.ret_via_arg = True

    if FLOAT_TOKENS.search(slot["ret"]) and "*" not in slot["ret"]:
        raise Refused(
            "returns %s by value; the unixlib invoker calls the host vtable "
            "slot in the widest INTEGER form, so the result would come back "
            "out of the wrong register file" % slot["ret"])
    if slot["ret"] != "void" and not slot.get("aggregate_return"):
        rp = Param(slot["ret"])
        if rp.stars == 0 and rp.base not in byval_ok:
            raise Refused(
                "return type %s is not provably integer-class on both ABIs; "
                "refusing rather than assuming" % slot["ret"])

    for i, p in enumerate(params):
        if cls[i] == CA["RET_PTR"]:
            continue
        if p.stars == 0:
            if p.base == "HANDLE" and key in EVENT_SLOTS:
                cls[i] = CA["EVENT"]
                continue
            if FLOAT_TOKENS.search(p.raw):
                raise Refused(
                    "passes %s by value; the unixlib invoker calls the host "
                    "vtable slot in the widest INTEGER form, so a float "
                    "argument would be placed in the wrong register file "
                    "entirely.  Serving it takes a hand-written stub, the "
                    "kind ClearDepthStencilView has always waited for"
                    % p.base)
            if p.base in GUEST_CODE_BYVAL:
                raise Refused(GUEST_CODE_BYVAL[p.base])
            if p.base in BYVAL_AGGREGATE:
                cls[i] = CA["PASS"]
                continue
            if p.base in BYVAL_ABI_SPLIT:
                raise Refused(BYVAL_ABI_SPLIT[p.base])
            if p.base not in byval_ok:
                raise Refused(
                    "by-value %s is not provably integer-class on both ABIs; "
                    "refusing rather than assuming it is an enum" % p.base)
            narrow = narrow_of(p)
            if narrow:
                if i >= 8:
                    raise Refused(
                        "passes a %d-byte %s by value in argument position "
                        "%d, past the eight parameters the narrowing masks "
                        "cover" % (narrow[0], p.base, i + 1))
                plan.narrowmask |= 1 << i
                if narrow[0] == 2:
                    plan.narrowwide |= 1 << i
                if narrow[1]:
                    plan.narrowsign |= 1 << i
                plan.narrow_params.append((i, p.base, narrow[0], narrow[1]))
            elif re.search(r'\blong\s+long\b', p.raw):
                pass    # 8 bytes; Param.base kept only the first `long`
            elif p.base in dword_class:
                # Four bytes: clean in a register, stale-topped on the stack
                # -- see DWORD_UNSIGNED above for the CopyDescriptors
                # measurement.  Sixteen mask bits cover every argc here.
                # The EXTENSION is clang's call, not a name list's: ELFv2
                # says signed types sign-extend and unsigned types
                # zero-extend, and whether the declared type is signed --
                # an enum's underlying type included -- is asked of the
                # oracle, the same probe the widths come from.
                if i >= 16:
                    raise Refused(
                        "passes a 4-byte %s by value in argument position %d, "
                        "past the sixteen parameters dwordmask covers"
                        % (p.base, i + 1))
                plan.dwordmask |= 1 << i
                if oracle.is_signed(byval_spelling(p.raw)):
                    plan.dwordsign |= 1 << i
            elif p.base not in QWORD_BYVAL:
                raise Refused(
                    "by-value %s is integer-class but this generator has no "
                    "measured width for it; a 32-bit stack slot passed whole "
                    "carries the guest's leftovers above bit 31, so the width "
                    "must be known, not assumed" % p.base)
            cls[i] = CA["PASS"]
            continue

        # ---- pointers
        if p.base in CARRIER_STRUCTS:
            raise Refused("%s is %s" % (p.base, CARRIER_STRUCTS[p.base]))
        if p.base in bearing:
            raise Refused(
                "%s carries interface pointers inside a struct (%s) and has "
                "no hand-written walker; the pointers inside it would reach "
                "vkd3d as guest proxies"
                % (p.base, why_bearing.get(p.base, p.base)))

        if p.base == "void" and p.stars == 2:
            prev = params[i - 1] if i else None
            if prev is not None and prev.is_riid():
                cls[i] = CA["PPV_OUT"]
                cls[i - 1] = CA["RIID"]
                aux = i - 1
                continue
            if key in VOID_PP_IS_MEMORY:
                cls[i] = CA["PASS"]
                continue
            raise Refused(
                "has a void** out-parameter (`%s`) with no REFIID beside it "
                "to type the result; an untyped interface pointer cannot be "
                "given a guest vtable" % p.raw)

        if p.base in ifaces:
            if p.stars == 1:
                # The TYPE is recorded (xaux/xmask) even though the forward
                # direction identifies an IN pointer by identity: the mask is
                # what lets a FUTURE reverse lane fail closed per-parameter
                # instead of per-surface.
                cls[i] = CA["IFACE_IN"]
                xaux[i] = iface_index[p.base]
                plan.xmask |= 1 << i
                continue
            if p.stars != 2:
                raise Refused(
                    "takes `%s`: an interface pointer at a level of "
                    "indirection this generator has no class for" % p.raw)
            if p.inner_const:
                c = find_count(params, i)
                if c is None:
                    raise Refused(
                        "takes the input interface array `%s` with no "
                        "by-value count parameter to bound it" % p.raw)
                cls[i] = CA["IFACE_ARR_IN"]
                aux2 = c
                continue
            c = find_count(params, i)
            plural = (p.name or '').endswith("s")
            if c is not None and plural:
                cls[i] = CA["IFACE_ARR_OUT_STATIC"]
                xaux[i] = iface_index[p.base]
                plan.xmask |= 1 << i
                caux[i] = c
                continue
            if plural:
                raise Refused(
                    "writes the interface array `%s` with no count parameter "
                    "this generator can identify; refusing rather than "
                    "wrapping only its first element" % p.raw)
            cls[i] = CA["IFACE_OUT_STATIC"]
            xaux[i] = iface_index[p.base]
            plan.xmask |= 1 << i
            continue

        # A pointer to a pointer that is not an interface out-parameter must
        # be named before it may pass: this is where an unrecognised
        # interface spelling would silently become a native vtable in the
        # guest's hands.
        if p.stars >= 2 and p.base not in PLAIN_PP:
            raise Refused(
                "writes `%s`, a pointer-to-pointer whose pointee this "
                "generator cannot prove is plain memory rather than an "
                "interface; add it to PLAIN_PP with the reason, or give it a "
                "marshal class" % p.raw)

        # An ordinary pointer to plain data crosses as an address: guest
        # memory IS host memory on this port, WCHAR is two bytes on both
        # sides of this surface, and the descriptor structs come from the
        # same vkd3d headers both halves compile.
        cls[i] = CA["PASS"]

    plan.cls, plan.xaux, plan.caux = cls, xaux, caux
    plan.aux, plan.aux2 = aux, aux2
    return plan


# --------------------------------------------------------------------------
# emission
# --------------------------------------------------------------------------

def c_guid(u):
    a, b, c, d, e = u.split("-")
    d4 = d + e
    return "{0x%s,0x%s,0x%s,{%s}}" % (
        a, b, c, ",".join("0x" + d4[i:i + 2] for i in range(0, 16, 2)))


def generate(roster, prefix, header_dir, oracle):
    ifaces = roster["interfaces"]
    order = sorted(ifaces)
    iface_index = {n: i for i, n in enumerate(order)}
    byval_ok = (set(BYVAL_INTEGER) | set(roster["enums"])
                | set(TYPEDEF_INTEGER))
    dword_class = set(DWORD_UNSIGNED) | set(DWORD_SIGNED) | set(roster["enums"])
    oracle.sign_names |= byval_ok
    oracle.measure(collect_spellings(ifaces))
    crosscheck_width64(ifaces, oracle, dword_class)
    # Scan every header the roster's interfaces were generated from.  A
    # missing directory is a HARD ERROR: a struct whose definition the scan
    # never saw is not refused -- it is PASSED THROUGH, the one outcome this
    # generator exists to prevent.
    if not os.path.isdir(header_dir):
        sys.exit("gen_winecom: %s is not a directory.  The vkd3d widl "
                 "headers are generated by ppc64le/vkd3d/gen-headers.sh; "
                 "generating without them silently drops every struct "
                 "refusal." % header_dir)
    paths = [os.path.join(header_dir, f) for f in sorted(os.listdir(header_dir))
             if f.endswith(".h")]
    bearing, why_bearing = scan_structs(paths, set(ifaces))
    hand_index, hand_order = {}, []
    for key, fn in HAND_SLOTS:
        if fn not in hand_order:
            hand_order.append(fn)
        hand_index[key] = hand_order.index(fn)

    out = []
    w = out.append
    stats = dict(marshalled=0, refused=0, hand=0, identity=0, iunknown=0,
                 geom=0, geom_unproven=0, qword_slots=0, ret_qword=0)
    refusal_log = []
    narrow_log = []
    qword_log = []
    unproven_log = []
    chk_entries = []
    chk_seen = set()

    w("""/* GENERATED by ppc64le/vkd3d/gen_winecom.py -- do not edit.
 *
 * Marshal tables for the %s surface (%d interfaces, %d vtable slots),
 * generated from ppc64le/vkd3d/interfaces_d3d12.json -- the same roster
 * dlls/d3d12/d3d12.thunks hands spec2thunk to build the guest trap
 * module.  Interface order is sorted by name, which is the order
 * spec2thunk COM mode gives the guest stub arrays; libs/winecom
 * cross-checks every IID and slot count at attach, so the two
 * generators cannot silently disagree.
 *
 * Slot/iface types and WINECOM_CA_* classes come from
 * include/wine/winecom.h, which must be included before this file.
 */
""" % (roster["surface"], len(order),
       sum(len(ifaces[n]["slots"] or ()) for n in order)))

    w("enum %s_iface_index\n{" % prefix)
    for n in order:
        w("    %s_IFACE_%s = %d," % (prefix.upper(), n, iface_index[n]))
    w("    %s_IFACE_COUNT = %d\n};\n" % (prefix.upper(), len(order)))
    w("#define %s_HAND_COUNT %d\n" % (prefix.upper(), len(hand_order)))
    if hand_order:
        w("/* hand_funcs[] order in dlls/d3d12/main.c:\n%s */\n"
          % "".join("     *   %d %s\n" % (i, f)
                    for i, f in enumerate(hand_order)))

    tables = []
    for n in order:
        slots = ifaces[n]["slots"]
        rows, decls = [], []
        for s in slots:
            key = "%s::%s" % (s["owner"], s["name"])
            if s["slot"] < 3:
                rows.append('    { "%s", NULL, NULL, NULL, %d, 0, 0, 0, NULL,'
                            ' 0, 0, 0 },  /* runtime */'
                            % (key, 1 if s["slot"] else 3))
                stats["iunknown"] += 1
                continue
            argc = 1 + len(s["params"])
            # The i386 frame geometry is computed for EVERY row -- hand and
            # refused included: a refused slot still has to pop the right
            # number of bytes before it can so much as answer E_NOTIMPL.
            qm, retq, geo_unproven = slot_geometry(s, oracle)
            gflags = []
            if geo_unproven is None:
                gflags.append("WINECOM_F_I386_GEOM")
                if retq:
                    gflags.append("WINECOM_F_RET_QWORD")
                stats["geom"] += 1
                if (key, argc, qm) not in chk_seen:
                    chk_seen.add((key, argc, qm))
                    chk_entries.append((key, s["params"], argc, qm))
                if qm:
                    stats["qword_slots"] += 1
                if retq:
                    stats["ret_qword"] += 1
                if qm or retq:
                    qword_log.append((key, qm, retq))
            else:
                stats["geom_unproven"] += 1
                unproven_log.append((key, geo_unproven))
            flags = []
            if s["ret"] == "void":
                flags.append("WINECOM_F_RET_VOID")
            if key in hand_index:
                rows.append('    { "%s", NULL, NULL, NULL, %d,'
                            ' %s, %d, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0,'
                            ' 0x%04x },'
                            % (key, argc,
                               "|".join(["WINECOM_F_HAND"] + gflags),
                               hand_index[key], qm))
                stats["hand"] += 1
                continue
            plan = None
            reason = REFUSALS.get(key)
            if reason is None:
                try:
                    plan = classify(key, s, ifaces, iface_index, byval_ok,
                                    dword_class, bearing, why_bearing,
                                    oracle)
                except Refused as e:
                    reason = str(e)
            if reason is not None:
                rows.append('    { "%s",\n      "%s: %s",\n'
                            '      NULL, NULL, %d, %s, 0, 0, NULL, 0, 0, 0,'
                            ' 0, 0, 0, 0, 0, 0x%04x },'
                            % (key, key, reason.replace('"', "'"), argc,
                               "|".join(gflags) or "0", qm))
                stats["refused"] += 1
                refusal_log.append((n, s["slot"], key, reason))
                continue
            if plan.ret_via_arg:
                flags.append("WINECOM_F_RET_VIA_ARG")
            cls, xaux, caux = plan.cls, plan.xaux, plan.caux
            cname = xname = kname = "NULL"
            if any(c != CA["PASS"] for c in cls):
                cname = "cls_%s_%d" % (n, s["slot"])
                decls.append("static const unsigned char %s[] = { %s };"
                             % (cname, ", ".join(CA_NAME[c] for c in cls)))
            # Emitted whenever a parameter is interface-typed, NOT when the
            # values happen to be non-zero: roster index 0 is a real
            # interface and `any(xaux)` would drop the row that names it.
            if plan.xmask:
                xname = "xaux_%s_%d" % (n, s["slot"])
                decls.append("static const unsigned char %s[] = { %s };"
                             % (xname, ", ".join(str(x) for x in xaux)))
            if any(caux):
                kname = "caux_%s_%d" % (n, s["slot"])
                decls.append("static const unsigned char %s[] = { %s };"
                             % (kname, ", ".join(str(x) for x in caux)))
            for np in plan.narrow_params:
                narrow_log.append((key,) + np)
            flags += gflags
            rows.append('    { "%s", NULL, %s, %s, %d, %s, %d, %d, %s, 0, 0,'
                        ' 0x%02x, 0x%02x, 0x%02x, 0x%02x, 0x%04x, 0x%04x,'
                        ' 0x%04x },'
                        % (key, cname, xname, argc,
                           "|".join(flags) or "0", plan.aux, plan.aux2, kname,
                           plan.xmask, plan.narrowmask, plan.narrowwide,
                           plan.narrowsign, plan.dwordmask, plan.dwordsign,
                           qm))
            stats["marshalled"] += 1

        if len(slots) <= 3:
            # Only IUnknown itself: its three slots are served by the runtime
            # from the proxy table without crossing.  Every OTHER interface
            # gets a real table -- a NULL table refuses every slot, which is
            # exactly the Device1..Device15 hole this generator was written
            # to close.
            stats["identity"] += 1
            tables.append((n, None))
            continue
        tables.append((n, (decls, rows)))

    for n, t in tables:
        if t is None:
            continue
        decls, rows = t
        w("")
        for d in decls:
            w(d)
        w("static const struct winecom_slot slots_%s[%d] =\n{" % (n, len(rows)))
        for r in rows:
            w(r)
        w("};")

    w("\nstatic const struct winecom_iface %s_com_ifaces[%s_IFACE_COUNT] =\n{"
      % (prefix, prefix.upper()))
    for n, t in tables:
        w('    { "%s", %s,\n      %d, %s, 0 },'
          % (n, c_guid(ifaces[n]["uuid"]), len(ifaces[n]["slots"]),
             "NULL" if t is None else "slots_" + n))
    w("};")

    # The second opinion on every published frame: clang's own stdcall @N.
    checked = oracle.check_stdcall_frames(chk_entries, IFACE_ALIASES)

    w("\n/* %d slot(s) marshalled, %d hand-written, %d refused with a named\n"
      " * reason, %d IUnknown slot(s) served by the runtime; %d interface(s)\n"
      " * (IUnknown itself) carry identity rows only.\n"
      " * i386 geometry: %d row(s) carry WINECOM_F_I386_GEOM (%d distinct\n"
      " * frames re-checked against clang's stdcall @N decoration), %d with\n"
      " * a non-zero qwordmask, %d returning EDX:EAX; %d row(s) publish no\n"
      " * i386 geometry and a 32-bit lane must fail closed on them. */"
      % (stats["marshalled"], stats["hand"], stats["refused"],
         stats["iunknown"], stats["identity"],
         stats["geom"], checked, stats["qword_slots"], stats["ret_qword"],
         stats["geom_unproven"]))
    return ("\n".join(out) + "\n", stats, refusal_log, narrow_log,
            qword_log, unproven_log)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--roster",
                    default=os.path.join(HERE, "interfaces_d3d12.json"))
    ap.add_argument("--headers",
                    default=os.path.join(HERE, "generated-headers"),
                    help="directory holding vkd3d's widl-generated headers")
    ap.add_argument("--prefix", default="d3d12")
    ap.add_argument("--out")
    ap.add_argument("--check", metavar="FILE")
    ap.add_argument("--report", action="store_true")
    ap.add_argument("--clang", default="clang",
                    help="the compiler the i386 width oracle asks")
    ap.add_argument("--build-include", default=None,
                    help="directory holding Wine's widl-GENERATED headers "
                         "(wtypes.h and friends); defaults to the sibling "
                         "wine-build/include when it exists")
    args = ap.parse_args()

    with open(args.roster) as fh:
        roster = json.load(fh)

    if not os.path.isdir(args.headers):
        sys.exit("gen_winecom: %s is not a directory.  The vkd3d widl "
                 "headers are generated by ppc64le/vkd3d/gen-headers.sh; "
                 "generating without them silently drops every struct "
                 "refusal." % args.headers)
    wine_root = os.path.abspath(os.path.join(HERE, "..", ".."))
    build_inc = args.build_include
    if build_inc is None:
        cand = os.path.abspath(os.path.join(wine_root, "..",
                                            "wine-build", "include"))
        build_inc = cand if os.path.isdir(cand) else None
    prelude = "".join('#include "%s"\n' % f
                      for f in sorted(os.listdir(args.headers))
                      if f.endswith(".h"))
    # The roster was generated by dxvk-ppc64le's gen_interfaces.py, so its
    # DXGI rows carry names from DXVK's vendored MinGW dxgi headers that no
    # vkd3d header declares (DXGI_MEMORY_SEGMENT_GROUP, WINBOOL) -- the
    # fallback world is therefore THOSE headers, not a guess.  WINBOOL is
    # the one base type the vendored headers leave to MinGW's windef.h
    # (their own copy sits under `#if 0`, widl's convention); mingw-w64
    # spells it `typedef int WINBOOL;` and so does this shim.
    shim = "typedef int WINBOOL;\n"
    dxvk_directx = os.path.abspath(os.path.join(
        HERE, "..", "dxvk", "src", "include", "native", "directx"))
    oracle = I386Oracle(args.clang, shim + prelude,
                        [args.headers,
                         os.path.join(HERE, "src", "include"), build_inc,
                         os.path.join(wine_root, "include"),
                         os.path.join(wine_root, "include", "msvcrt")],
                        set(), args.prefix,
                        fallback_prelude=shim + "#include <dxgi1_6.h>\n",
                        fallback_incdirs=[dxvk_directx, build_inc,
                                          os.path.join(wine_root, "include"),
                                          os.path.join(wine_root, "include",
                                                       "msvcrt")])

    text, stats, refusals, narrows, qwords, unproven = generate(
        roster, args.prefix, args.headers, oracle)

    print("surface %s: %d marshalled, %d hand-written, %d refused, "
          "%d IUnknown, %d identity-only interface(s)"
          % (roster["surface"], stats["marshalled"], stats["hand"],
             stats["refused"], stats["iunknown"], stats["identity"]))
    print("i386 geometry: %d row(s) published, %d qword-marked, %d EDX:EAX "
          "return(s), %d without geometry (fail closed)"
          % (stats["geom"], stats["qword_slots"], stats["ret_qword"],
             stats["geom_unproven"]))

    if args.report:
        print("\nslots whose i386 frame differs from all-dwords "
              "(qwordmask / EDX:EAX return):")
        for key, qmv, retq in sorted(set(qwords)):
            print("  %-64s qwordmask 0x%04x%s"
                  % (key, qmv, "  ret EDX:EAX" if retq else ""))
        if unproven:
            print("\nslots publishing NO i386 geometry, and why:")
            for key, why in sorted(set(unproven)):
                print("  %-64s %s" % (key, why))
        print("\nnarrow by-value parameters (extended by the runtime):")
        for key, i, base, width, signed in narrows:
            print("  %-60s arg %d: %d-byte %s%s"
                  % (key, i + 1, width, "signed " if signed else "", base))
        print("\nrefused slots, by reason:")
        seen = {}
        for n, slot, key, reason in refusals:
            seen.setdefault(reason.split(';')[0][:76], []).append(key)
        for reason, keys in sorted(seen.items(), key=lambda kv: -len(kv[1])):
            uniq = sorted(set(keys))
            print("  %4d  %s" % (len(keys), reason))
            for k in uniq[:8]:
                print("          %s" % k)
            if len(uniq) > 8:
                print("          ... and %d more distinct method(s)"
                      % (len(uniq) - 8))

    if args.check:
        with open(args.check) as fh:
            have = fh.read()
        if have == text:
            print("\ncheck passed: %s matches the roster" % args.check)
            return 0
        sys.exit("\ngen_winecom: %s has DRIFTED from the roster.  Regenerate "
                 "it (--out) and re-run every gate." % args.check)

    if args.out:
        with open(args.out, "w") as fh:
            fh.write(text)
        print("\nwrote %s" % args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
