#!/usr/bin/env python3
"""Emit the winecom marshal tables for the d3d12 (vkd3d-proton) surface.

  ./gen_winecom.py --out ../../dlls/d3d12/d3d12_marshal.h
  ./gen_winecom.py --report        # what is marshalled, what is refused, why
  ./gen_winecom.py --check ../../dlls/d3d12/d3d12_marshal.h

INPUT is interfaces_d3d12.json -- the ONE roster, the same file
dlls/d3d12/d3d12.thunks hands spec2thunk to build the guest trap module.
Both generators sort by interface name, and libs/winecom cross-checks every
IID and slot count at attach as the last line of defence.

OUTPUT is a header of `struct winecom_slot` / `struct winecom_iface` tables
(include/wine/winecom.h), consumed by dlls/d3d12/main.c.

HISTORY, because it explains the shape of this file: d3d12 was the FIRST
winecom surface and its marshal table was generated by a script that lived in
the dxvk-ppc64le clone and no longer exists anywhere.  That script only
emitted tables for the 21 interfaces its smoke test touched; the other 96 --
ID3D12Device1 through Device15 among them -- got NULL identity rows, so every
call through a Device4 proxy answered "no marshal plan".  Cyberpunk 2077 hit
exactly that: CreateCommittedResource1 and CreateHeap1 refused, the game
Reset() the command list it never checked.  This generator is the lane's
re-entry into the gen_winecom.py family (mf/audio/dxvk are the siblings; the
mf copy is the closest ancestor): every rostered interface now gets a real
table, and a slot refuses only for a reason this file can name.

WHAT IS DIFFERENT ON THIS SURFACE, each with the measurement behind it:

  * WCHAR crosses.  vkd3d's own vkd3d_windows.h line 89 says
    `typedef unsigned short WCHAR;`, the guest PE's WCHAR is two bytes too --
    unlike the DXVK lane, where dxvk-native's four-byte wchar_t made GetDesc
    answer "A" and zeros (dxvk-patches/0005).  SetName and the LPCWSTR family
    pass.
  * HANDLE mostly crosses AS A NUMBER the native side will not understand,
    and that is the committed policy, not an accident: vkd3d's unix side has
    no Wine handle table, so OpenSharedHandle-family slots pass the value and
    vkd3d answers its own E_NOTIMPL.  The exception is the completion-event
    slots (EVENT_SLOTS below): a real Wine event handle passed there would be
    WAITED ON natively, so those are classed WINECOM_CA_EVENT and the runtime
    refuses a non-NULL event until the eventfd relay exists.  A NULL event --
    the blocking form of SetEventOnCompletion -- is served, and is what the
    fence gates use.
  * HWND crosses.  There is one window-handle namespace in the process and
    this lane presents through win32u (unix_win32u.c), the same reasoning
    that put HWND back on the DXVK surface.
  * widl's aggregate returns (`GetDesc(D3D12_HEAP_DESC *__ret)`) are classed
    WINECOM_CA_RET_PTR with WINECOM_F_RET_VIA_ARG, the shape the runtime has
    served since the first commit of this lane.
  * NO WINECOM_F_REV, ever.  The invoker crosses a unixlib
    (dlls/d3d12/unix.c) and the surface deliberately lacks WINECOM_SF_REVERSE
    -- a reverse proxy is a PE-side object the unix side would call as data.
    A by-value float is therefore a plain refusal here (ClearDepthStencilView
    keeps the refusal the old table had), not a reverse-only row.

The struct scan below brace-matches instead of borrowing the siblings' crude
regex, and that is load-bearing: these headers spell D3D12_RESOURCE_BARRIER
and D3D12_TEXTURE_COPY_LOCATION with NESTED NAMELESS UNIONS, which the
non-greedy regex mis-parses so badly that D3D12_RESOURCE_BARRIER never enters
the bearing set at all -- and a struct the scan never saw is passed through,
which is the one outcome this generator exists to prevent.

Copyright 2026 the ppc64le port authors

This library is free software; you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the GNU
Free Software Foundation; either version 2.1 of the License, or (at your
option) any later version.
"""

import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# --------------------------------------------------------------------------
# by-value types that cross as an integer register and are the same width on
# both sides.  ANYTHING NOT LISTED BECOMES A NAMED REFUSAL -- see the banner.
# The roster's enum names are added to this set at run time; an enum is
# `int`-class in both ABIs.
# --------------------------------------------------------------------------
BYVAL_INTEGER = frozenset("""
    UINT INT LONG ULONG DWORD WORD BYTE BOOL WINBOOL UINT8 UINT16 UINT32
    UINT64 INT8 INT16 INT32 INT64 SIZE_T SSIZE_T LONGLONG ULONGLONG
    ULONG64 LONG64 QWORD HANDLE HWND HMODULE HMONITOR HRESULT
    ULONG_PTR DWORD_PTR UINT_PTR LONG_PTR INT_PTR
    SHORT USHORT CHAR UCHAR BOOLEAN
    unsigned int short char long
""".split())

# Integer typedefs these headers spell under their own names.  Each entry was
# read in the header, not assumed.
TYPEDEF_INTEGER = {
    "D3D12_GPU_VIRTUAL_ADDRESS": "typedef UINT64 (vkd3d_d3d12.h)",
    "DXGI_USAGE":                "typedef UINT (vkd3d_dxgi.h:231)",
}

# FOUR-BYTE by-value types, split by signedness -- winecom_slot::dwordmask /
# dwordsign.  A 32-bit argument is clean in a register (x86-64 zero-extends
# 32-bit register writes) but NOT on the stack, where the guest's 32-bit
# store leaves the slot's upper half stale.  [MEASURED] on THIS surface:
# ID3D12Device::CopyDescriptors passes the descriptor heap type as argument
# seven -- a stack slot -- and vkd3d's 64-bit switch missed an enum whose low
# half said 0, printing "Unhandled descriptor heap type 0" 32768 times per
# scene while every descriptor copy silently did nothing.  The roster's enums
# join DWORD_SIGNED at run time (an enum is int underneath).
#
# Every by-value type must land in exactly one of: NARROW_BYVAL, these two,
# QWORD_BYVAL, BYVAL_AGGREGATE -- a byval_ok type with no width is refused,
# because "probably 32 bits" is how a stack slot's stale upper half reaches a
# callee that trusts it.
DWORD_UNSIGNED = frozenset("""
    UINT ULONG DWORD BOOL WINBOOL UINT32 DXGI_USAGE unsigned
""".split())
DWORD_SIGNED = frozenset("""
    INT LONG INT32 HRESULT int long
""".split())
QWORD_BYVAL = frozenset("""
    UINT64 INT64 SIZE_T SSIZE_T LONGLONG ULONGLONG ULONG64 LONG64 QWORD
    HANDLE HWND HMODULE HMONITOR ULONG_PTR DWORD_PTR UINT_PTR LONG_PTR
    INT_PTR D3D12_GPU_VIRTUAL_ADDRESS
""".split())

# By-value integers NARROWER THAN 32 BITS: (bytes, signed).  MS-x64 leaves
# the upper bits of the register UNDEFINED and makes ignoring them the
# CALLEE's job; ELFv2 makes extending them the CALLER's job and a ppc64
# callee trusts that it happened.  The runtime does the extension
# (struct winecom_slot::narrowmask); this table tells it width and
# signedness.  [MEASURED] on the MF surface: IWMSyncReader::GetStreamSelected
# read a guest-passed WORD 1 as 0x40000001.  This roster has UINT8 parameters
# (ID3D12StateObjectProperties1 and friends), so unlike the DXVK copy the
# masks are emitted here, not merely recognised.
NARROW_BYVAL = {
    "WORD":    (2, False), "USHORT": (2, False), "UINT16":  (2, False),
    "SHORT":   (2, True),  "INT16":  (2, True),
    "BYTE":    (1, False), "UCHAR":  (1, False), "UINT8":   (1, False),
    "BOOLEAN": (1, False),
    "CHAR":    (1, True),  "INT8":   (1, True),
}

NARROW_RAW = (
    (r'\bunsigned\s+short\b',  (2, False)),
    (r'\bsigned\s+short\b',    (2, True)),
    (r'\bunsigned\s+char\b',   (1, False)),
    (r'\bsigned\s+char\b',     (1, True)),
    (r'\bshort\b',              (2, True)),
    (r'\bchar\b',               (1, True)),
)


def narrow_of(p):
    """(bytes, signed) for a by-value parameter narrower than 32 bits, else None."""
    if p.base in NARROW_BYVAL:
        return NARROW_BYVAL[p.base]
    for pat, w in NARROW_RAW:
        if re.search(pat, p.raw):
            return w
    return None


# 8-byte aggregates that are ONE integer register on both the MS-x64 and the
# ELFv2 side.  Each is here because its layout was checked in the header.
BYVAL_AGGREGATE = {
    "LUID": "{ DWORD LowPart; LONG HighPart; } -- 8 bytes, one register on "
            "both ABIs",
    "D3D12_CPU_DESCRIPTOR_HANDLE": "{ SIZE_T ptr; } -- 8 bytes, one register "
                                   "on both ABIs (vkd3d_d3d12.h:2847)",
    "D3D12_GPU_DESCRIPTOR_HANDLE": "{ UINT64 ptr; } -- 8 bytes, one register "
                                   "on both ABIs (vkd3d_d3d12.h:2850)",
}

# By-value aggregates the two ABIs pass DIFFERENTLY, refused by name with the
# mechanism rather than with the generic "not provably integer-class".
BYVAL_ABI_SPLIT = {
    "GUID":
        "takes a GUID BY VALUE, and the two ABIs disagree about how.  MS-x64 "
        "passes any aggregate that is not 1/2/4/8 bytes by a hidden POINTER "
        "to a caller-allocated temporary; ELFv2 passes 16 bytes in TWO GPRs. "
        "Needs a hand-written slot that dereferences, not a marshal class",
    "D3D12_NODE_ID":
        "takes a D3D12_NODE_ID ({ LPCWSTR Name; UINT ArrayIndex; }, 16 "
        "bytes) by value; a hidden pointer on one ABI and two registers on "
        "the other -- see the GUID case",
}

# Pointer spellings that are pointers without a `*` in the source text.
POINTER_TYPEDEFS = {
    "LPSTR": "char", "LPCSTR": "char", "LPWSTR": "WCHAR", "LPCWSTR": "WCHAR",
    "PWSTR": "WCHAR", "PCWSTR": "WCHAR",
    "LPVOID": "void", "PVOID": "void", "LPCVOID": "void",
    "REFIID": "GUID", "REFGUID": "GUID", "REFCLSID": "GUID",
}

# Interface names the headers spell differently from the roster.  ID3DBlob
# is widl's alias for ID3D10Blob -- same IID 8ba5fb08 -- and the roster
# carries the latter; without the alias every `ID3DBlob **` out-parameter
# would refuse as an unprovable pointer-to-pointer.
IFACE_ALIASES = {
    "ID3DBlob": "ID3D10Blob",
}

# Pointer-to-pointer parameters that really are blocks of plain memory, so
# CA_PASS is the right answer: the callee writes a HOST address into
# guest-visible storage, and on this port guest memory IS host memory.  An
# ALLOW-list, because the failure it guards is silent.
PLAIN_PP = {
    "void": "only reachable via VOID_PP_IS_MEMORY below",
    "D3D12_VERSIONED_ROOT_SIGNATURE_DESC":
        "the deserializer hands back a pointer to its own parsed copy -- "
        "plain data it owns",
    "DXGI_FORMAT":
        "the castable-formats arrays of the Device12 CreateCommittedResource3 "
        "family -- a const array of enums, plain data in",
}

FLOAT_TOKENS = re.compile(r'\b(FLOAT|float|double|DOUBLE)\b')

# Structs that carry an interface pointer behind a `const void *` payload the
# transitive scan below cannot see through.  Named here so the refusal states
# the mechanism.  The two Device slots that matter most are NOT refused --
# they are HAND_SLOTS -- but the SAME structs also appear on
# ID3D12PipelineLibrary1::LoadPipeline and the DXR family, and those stay
# refused until a title is measured hitting them.
CARRIER_STRUCTS = {
    "D3D12_PIPELINE_STATE_STREAM_DESC":
        "a subobject stream whose ROOT_SIGNATURE subobject is an "
        "ID3D12RootSignature* behind a void*, invisible to any signature or "
        "struct scan; dlls/d3d12/main.c's hand_create_pipeline_state walks "
        "it for the slots that have been measured to matter",
    "D3D12_STATE_OBJECT_DESC":
        "DXR state-object subobjects hide interface pointers "
        "(D3D12_GLOBAL_ROOT_SIGNATURE, D3D12_EXISTING_COLLECTION_DESC) "
        "behind const void*; needs a hand-written walker",
}

# Function pointers a guest would pass BY VALUE: guest x86-64 code entered as
# ppc64.  Refused by name; the day one matters it needs the guest-callback
# trampoline, not a marshal class.
GUEST_CODE_BYVAL = {
    "PFN_DESTRUCTION_CALLBACK":
        "takes a guest function pointer by value; native code calling it "
        "would execute x86-64 bytes as ppc64.  Needs the guest-callback "
        "trampoline (ppc64le/thunks), not a marshal class",
}

# Completion-event slots: the by-value HANDLE is a Wine event the native side
# would WAIT ON or SIGNAL, which vkd3d's unix half cannot do.  Classed
# WINECOM_CA_EVENT -- the runtime serves the NULL (blocking) form and refuses
# a real handle with the reason, instead of corrupting.  Keyed
# "Owner::Method" so ID3D12Fence1 and every later Device inherit the class.
# IDXGIFactory2's RegisterStereoStatusEvent/RegisterOcclusionStatusEvent are
# deliberately NOT here: the committed table always passed them (vkd3d's
# swapchain ignores stereo/occlusion registration) and this regeneration
# changes no served row's meaning.
EVENT_SLOTS = frozenset((
    "ID3D12Fence::SetEventOnCompletion",
    "ID3D12Device1::SetEventOnMultipleFenceCompletion",
    "ID3D12Device6::SetBackgroundProcessingMode",
    "IDXGIAdapter3::RegisterHardwareContentProtectionTeardownStatusEvent",
    "IDXGIAdapter3::RegisterVideoMemoryBudgetChangeNotificationEvent",
    "IDXGIFactory7::RegisterAdaptersChangedEvent",
))

# --------------------------------------------------------------------------
# Hand-written slots.  Keyed "Owner::Method" so an inherited slot gets the
# same hand function in every derived interface's table -- ResourceBarrier
# at slot 26 of ID3D12GraphicsCommandList is slot 26 of GraphicsCommandList10
# too, and the hand function forwards by slot number.  The C functions live
# in dlls/d3d12/main.c and the order here IS the hand_funcs[] order there;
# the first three predate this generator and their indices are frozen.
# --------------------------------------------------------------------------
HAND_SLOTS = [
    ("ID3D12GraphicsCommandList::ResourceBarrier", "hand_resource_barrier"),
    ("ID3D12Device::CreateComputePipelineState",   "hand_create_compute_pso"),
    ("IDXGIFactory2::CreateSwapChainForHwnd",      "hand_create_swapchain_for_hwnd"),
    # D3D12_GRAPHICS_PIPELINE_STATE_DESC's one interface member is
    # pRootSignature; the walker copies the desc and unwraps it, the same
    # shape hand_create_compute_pso has.
    ("ID3D12Device::CreateGraphicsPipelineState",  "hand_create_graphics_pso"),
    # The modern PSO path: a subobject stream (see CARRIER_STRUCTS).  The
    # walker mirrors vkd3d's own vkd3d_pipeline_state_desc_from_d3d12_stream_desc
    # -- type enum, naturally-aligned payload, stride padded to pointer size
    # -- and unwraps the ROOT_SIGNATURE subobject in a copy.
    ("ID3D12Device2::CreatePipelineState",         "hand_create_pipeline_state"),
    # The texture-upload path: two D3D12_TEXTURE_COPY_LOCATIONs whose
    # pResource members are proxies; the walker copies both one-struct
    # arguments and unwraps them.
    ("ID3D12GraphicsCommandList::CopyTextureRegion", "hand_copy_texture_region"),
]

# Refusals decided here rather than derived.  Keyed "Owner::Method".
REFUSALS = {}

# void** out-parameters that are blocks of memory rather than untyped
# interface pointers, checked one by one against the headers.  Everything
# else with a bare void** is refused: the default has to be the safe one.
VOID_PP_IS_MEMORY = frozenset((
    "ID3D12Resource::Map",                    # the mapped bytes
))


# --------------------------------------------------------------------------
# struct bodies -- which ones reach an interface pointer, transitively
# --------------------------------------------------------------------------

TYPEDEF_HEAD = re.compile(r'typedef\s+(struct|union)\b[^{;]*\{')
FWD_IFACE = re.compile(r'typedef\s+struct\s+(I\w+)\s+\1\s*;')


def scan_structs(paths, iface_names):
    """-> (bearing, why).

    `bearing` is the set of struct type names that reach an interface pointer
    through any member chain.  Brace-MATCHED, not regexed: these headers nest
    nameless unions inside D3D12_RESOURCE_BARRIER and
    D3D12_TEXTURE_COPY_LOCATION, and a non-greedy regex records the inner
    union under __C89_NAMELESSUNIONNAME and loses the outer struct entirely.
    Every identifier in the whole body counts as a member type --
    over-approximating costs a refusal; under-approximating hands vkd3d a
    guest proxy pointer."""
    members = {}
    ifaces_seen = set(iface_names)
    for path in paths:
        with open(path, errors="replace") as fh:
            text = fh.read()
        ifaces_seen |= set(FWD_IFACE.findall(text))
        for m in TYPEDEF_HEAD.finditer(text):
            depth, i = 1, m.end()
            while i < len(text) and depth:
                if text[i] == '{':
                    depth += 1
                elif text[i] == '}':
                    depth -= 1
                i += 1
            body = text[m.end():i - 1]
            tail = re.match(r'\s*(\w+)\s*;', text[i:])
            if not tail:
                continue
            name = tail.group(1)
            if name in members:
                continue
            # SORTED: the `why` chain below lands in the refusal TEXT of the
            # generated header, and set order would make the committed file
            # depend on PYTHONHASHSEED.
            members[name] = sorted(
                set(re.findall(r'\b(\w+)\s*\*', body)) |
                set(re.findall(r'\b(\w+)\s+\w+\s*(?:\[|;|:)', body)))

    hit, why = {}, {}
    for name in members:
        seen, stack = set(), [(name, [])]
        while stack:
            cur, path = stack.pop()
            if cur in seen:
                continue
            seen.add(cur)
            for m in members.get(cur, ()):
                if m in ifaces_seen:
                    hit[name] = True
                    why[name] = " -> ".join(path + [cur, m])
                    stack = []
                    break
                if m in members:
                    stack.append((m, path + [cur]))
    return set(hit), why


# --------------------------------------------------------------------------
# parameter parsing
# --------------------------------------------------------------------------

class Param:
    __slots__ = ("raw", "base", "stars", "inner_const", "array", "name")

    def __init__(self, raw):
        self.raw = " ".join(raw.split())
        t = self.raw
        self.array = bool(re.search(r'\[', t))
        t = re.sub(r'\[[^\]]*\]', '', t).strip()
        # `Iface *const *p`: the INNER pointer is const, which is how these
        # headers spell an INPUT array.
        self.inner_const = bool(re.search(r'\*\s*const\s*\*', t))
        t = re.sub(r'\bconst\b', ' ', t)
        toks = t.replace('*', ' * ').split()
        self.stars = toks.count('*')
        toks = [x for x in toks if x != '*']
        self.base = toks[0] if toks else ''
        self.name = toks[-1] if len(toks) > 1 else ''
        if self.base in POINTER_TYPEDEFS:
            self.stars += 1
            self.base = POINTER_TYPEDEFS[self.base]
        if self.array:
            self.stars += 1

    def is_riid(self):
        return re.match(r'^(REFIID|REFGUID|REFCLSID)\b', self.raw) is not None


def resolve_alias(p):
    if p.base in IFACE_ALIASES:
        p.base = IFACE_ALIASES[p.base]


# The roster spells parameters in vkd3d's snake_case: command_list_count,
# num_objects, buffer_count, region_count.
COUNT_RE = re.compile(r'^(num_?\w*|\w*_?count\w*)$', re.IGNORECASE)


def find_count(params, idx):
    """Index of the by-value count that governs the array at `idx`: nearest
    preceding, else nearest following.  None if there is none."""
    cands = [i for i, p in enumerate(params)
             if p.stars == 0 and p.base in ("UINT", "UINT32", "unsigned",
                                            "int", "DWORD", "ULONG")
             and COUNT_RE.match(p.name or '')]
    before = [i for i in cands if i < idx]
    after = [i for i in cands if i > idx]
    if before:
        return before[-1]
    if after:
        return after[0]
    return None


# --------------------------------------------------------------------------
# classification
# --------------------------------------------------------------------------

CA = dict(PASS=0, IFACE_IN=1, RIID=2, PPV_OUT=3, RET_PTR=4, EVENT=5,
          IFACE_ARR_IN=6, IFACE_OUT_STATIC=7, IFACE_ARR_OUT_STATIC=8)
CA_NAME = {v: "WINECOM_CA_" + k for k, v in CA.items()}


class Refused(Exception):
    pass


class Plan:
    """What classify() proved about one slot.  No fp_reason / no reverse
    lane on this surface: the invoker crosses a unixlib and the surface
    lacks WINECOM_SF_REVERSE, so a by-value float is a plain Refused."""

    __slots__ = ("cls", "xaux", "caux", "aux", "aux2", "xmask",
                 "narrowmask", "narrowwide", "narrowsign", "narrow_params",
                 "dwordmask", "dwordsign", "ret_via_arg")

    def __init__(self):
        self.cls = self.xaux = self.caux = None
        self.aux = self.aux2 = 0
        self.xmask = 0
        self.narrowmask = self.narrowwide = self.narrowsign = 0
        self.narrow_params = []
        self.dwordmask = self.dwordsign = 0
        self.ret_via_arg = False


def classify(key, slot, ifaces, iface_index, byval_ok, dword_signed,
             bearing, why_bearing):
    """-> Plan, or raise Refused(reason)."""
    params = [Param(p) for p in slot["params"]]
    for p in params:
        resolve_alias(p)
    n = len(params)
    cls = [CA["PASS"]] * n
    xaux = [0] * n
    caux = [0] * n
    aux = aux2 = 0
    plan = Plan()

    if slot.get("aggregate_return"):
        # widl's __ret pointer: the caller's temporary, always parameter 0;
        # the runtime answers RAX = args[1] (WINECOM_F_RET_VIA_ARG).
        if not params or params[0].name != "__ret":
            raise Refused(
                "is marked aggregate_return but its first parameter is not "
                "the widl __ret pointer; the roster and this generator "
                "disagree and the safe answer is no")
        cls[0] = CA["RET_PTR"]
        plan.ret_via_arg = True

    if FLOAT_TOKENS.search(slot["ret"]) and "*" not in slot["ret"]:
        raise Refused(
            "returns %s by value; the unixlib invoker calls the host vtable "
            "slot in the widest INTEGER form, so the result would come back "
            "out of the wrong register file" % slot["ret"])
    if slot["ret"] != "void" and not slot.get("aggregate_return"):
        rp = Param(slot["ret"])
        if rp.stars == 0 and rp.base not in byval_ok:
            raise Refused(
                "return type %s is not provably integer-class on both ABIs; "
                "refusing rather than assuming" % slot["ret"])

    for i, p in enumerate(params):
        if cls[i] == CA["RET_PTR"]:
            continue
        if p.stars == 0:
            if p.base == "HANDLE" and key in EVENT_SLOTS:
                cls[i] = CA["EVENT"]
                continue
            if FLOAT_TOKENS.search(p.raw):
                raise Refused(
                    "passes %s by value; the unixlib invoker calls the host "
                    "vtable slot in the widest INTEGER form, so a float "
                    "argument would be placed in the wrong register file "
                    "entirely.  Serving it takes a hand-written stub, the "
                    "kind ClearDepthStencilView has always waited for"
                    % p.base)
            if p.base in GUEST_CODE_BYVAL:
                raise Refused(GUEST_CODE_BYVAL[p.base])
            if p.base in BYVAL_AGGREGATE:
                cls[i] = CA["PASS"]
                continue
            if p.base in BYVAL_ABI_SPLIT:
                raise Refused(BYVAL_ABI_SPLIT[p.base])
            if p.base not in byval_ok:
                raise Refused(
                    "by-value %s is not provably integer-class on both ABIs; "
                    "refusing rather than assuming it is an enum" % p.base)
            narrow = narrow_of(p)
            if narrow:
                if i >= 8:
                    raise Refused(
                        "passes a %d-byte %s by value in argument position "
                        "%d, past the eight parameters the narrowing masks "
                        "cover" % (narrow[0], p.base, i + 1))
                plan.narrowmask |= 1 << i
                if narrow[0] == 2:
                    plan.narrowwide |= 1 << i
                if narrow[1]:
                    plan.narrowsign |= 1 << i
                plan.narrow_params.append((i, p.base, narrow[0], narrow[1]))
            elif re.search(r'\blong\s+long\b', p.raw):
                pass    # 8 bytes; Param.base kept only the first `long`
            elif p.base in DWORD_UNSIGNED or p.base in dword_signed:
                # Four bytes: clean in a register, stale-topped on the stack
                # -- see DWORD_UNSIGNED above for the CopyDescriptors
                # measurement.  Sixteen mask bits cover every argc here.
                if i >= 16:
                    raise Refused(
                        "passes a 4-byte %s by value in argument position %d, "
                        "past the sixteen parameters dwordmask covers"
                        % (p.base, i + 1))
                plan.dwordmask |= 1 << i
                if p.base in dword_signed:
                    plan.dwordsign |= 1 << i
            elif p.base not in QWORD_BYVAL:
                raise Refused(
                    "by-value %s is integer-class but this generator has no "
                    "measured width for it; a 32-bit stack slot passed whole "
                    "carries the guest's leftovers above bit 31, so the width "
                    "must be known, not assumed" % p.base)
            cls[i] = CA["PASS"]
            continue

        # ---- pointers
        if p.base in CARRIER_STRUCTS:
            raise Refused("%s is %s" % (p.base, CARRIER_STRUCTS[p.base]))
        if p.base in bearing:
            raise Refused(
                "%s carries interface pointers inside a struct (%s) and has "
                "no hand-written walker; the pointers inside it would reach "
                "vkd3d as guest proxies"
                % (p.base, why_bearing.get(p.base, p.base)))

        if p.base == "void" and p.stars == 2:
            prev = params[i - 1] if i else None
            if prev is not None and prev.is_riid():
                cls[i] = CA["PPV_OUT"]
                cls[i - 1] = CA["RIID"]
                aux = i - 1
                continue
            if key in VOID_PP_IS_MEMORY:
                cls[i] = CA["PASS"]
                continue
            raise Refused(
                "has a void** out-parameter (`%s`) with no REFIID beside it "
                "to type the result; an untyped interface pointer cannot be "
                "given a guest vtable" % p.raw)

        if p.base in ifaces:
            if p.stars == 1:
                # The TYPE is recorded (xaux/xmask) even though the forward
                # direction identifies an IN pointer by identity: the mask is
                # what lets a FUTURE reverse lane fail closed per-parameter
                # instead of per-surface.
                cls[i] = CA["IFACE_IN"]
                xaux[i] = iface_index[p.base]
                plan.xmask |= 1 << i
                continue
            if p.stars != 2:
                raise Refused(
                    "takes `%s`: an interface pointer at a level of "
                    "indirection this generator has no class for" % p.raw)
            if p.inner_const:
                c = find_count(params, i)
                if c is None:
                    raise Refused(
                        "takes the input interface array `%s` with no "
                        "by-value count parameter to bound it" % p.raw)
                cls[i] = CA["IFACE_ARR_IN"]
                aux2 = c
                continue
            c = find_count(params, i)
            plural = (p.name or '').endswith("s")
            if c is not None and plural:
                cls[i] = CA["IFACE_ARR_OUT_STATIC"]
                xaux[i] = iface_index[p.base]
                plan.xmask |= 1 << i
                caux[i] = c
                continue
            if plural:
                raise Refused(
                    "writes the interface array `%s` with no count parameter "
                    "this generator can identify; refusing rather than "
                    "wrapping only its first element" % p.raw)
            cls[i] = CA["IFACE_OUT_STATIC"]
            xaux[i] = iface_index[p.base]
            plan.xmask |= 1 << i
            continue

        # A pointer to a pointer that is not an interface out-parameter must
        # be named before it may pass: this is where an unrecognised
        # interface spelling would silently become a native vtable in the
        # guest's hands.
        if p.stars >= 2 and p.base not in PLAIN_PP:
            raise Refused(
                "writes `%s`, a pointer-to-pointer whose pointee this "
                "generator cannot prove is plain memory rather than an "
                "interface; add it to PLAIN_PP with the reason, or give it a "
                "marshal class" % p.raw)

        # An ordinary pointer to plain data crosses as an address: guest
        # memory IS host memory on this port, WCHAR is two bytes on both
        # sides of this surface, and the descriptor structs come from the
        # same vkd3d headers both halves compile.
        cls[i] = CA["PASS"]

    plan.cls, plan.xaux, plan.caux = cls, xaux, caux
    plan.aux, plan.aux2 = aux, aux2
    return plan


# --------------------------------------------------------------------------
# emission
# --------------------------------------------------------------------------

def c_guid(u):
    a, b, c, d, e = u.split("-")
    d4 = d + e
    return "{0x%s,0x%s,0x%s,{%s}}" % (
        a, b, c, ",".join("0x" + d4[i:i + 2] for i in range(0, 16, 2)))


def generate(roster, prefix, header_dir):
    ifaces = roster["interfaces"]
    order = sorted(ifaces)
    iface_index = {n: i for i, n in enumerate(order)}
    byval_ok = (set(BYVAL_INTEGER) | set(roster["enums"])
                | set(TYPEDEF_INTEGER))
    dword_signed = set(DWORD_SIGNED) | set(roster["enums"])
    # Scan every header the roster's interfaces were generated from.  A
    # missing directory is a HARD ERROR: a struct whose definition the scan
    # never saw is not refused -- it is PASSED THROUGH, the one outcome this
    # generator exists to prevent.
    if not os.path.isdir(header_dir):
        sys.exit("gen_winecom: %s is not a directory.  The vkd3d widl "
                 "headers are generated by ppc64le/vkd3d/gen-headers.sh; "
                 "generating without them silently drops every struct "
                 "refusal." % header_dir)
    paths = [os.path.join(header_dir, f) for f in sorted(os.listdir(header_dir))
             if f.endswith(".h")]
    bearing, why_bearing = scan_structs(paths, set(ifaces))
    hand_index, hand_order = {}, []
    for key, fn in HAND_SLOTS:
        if fn not in hand_order:
            hand_order.append(fn)
        hand_index[key] = hand_order.index(fn)

    out = []
    w = out.append
    stats = dict(marshalled=0, refused=0, hand=0, identity=0, iunknown=0)
    refusal_log = []
    narrow_log = []

    w("""/* GENERATED by ppc64le/vkd3d/gen_winecom.py -- do not edit.
 *
 * Marshal tables for the %s surface (%d interfaces, %d vtable slots),
 * generated from ppc64le/vkd3d/interfaces_d3d12.json -- the same roster
 * dlls/d3d12/d3d12.thunks hands spec2thunk to build the guest trap
 * module.  Interface order is sorted by name, which is the order
 * spec2thunk COM mode gives the guest stub arrays; libs/winecom
 * cross-checks every IID and slot count at attach, so the two
 * generators cannot silently disagree.
 *
 * Slot/iface types and WINECOM_CA_* classes come from
 * include/wine/winecom.h, which must be included before this file.
 */
""" % (roster["surface"], len(order),
       sum(len(ifaces[n]["slots"] or ()) for n in order)))

    w("enum %s_iface_index\n{" % prefix)
    for n in order:
        w("    %s_IFACE_%s = %d," % (prefix.upper(), n, iface_index[n]))
    w("    %s_IFACE_COUNT = %d\n};\n" % (prefix.upper(), len(order)))
    w("#define %s_HAND_COUNT %d\n" % (prefix.upper(), len(hand_order)))
    if hand_order:
        w("/* hand_funcs[] order in dlls/d3d12/main.c:\n%s */\n"
          % "".join("     *   %d %s\n" % (i, f)
                    for i, f in enumerate(hand_order)))

    tables = []
    for n in order:
        slots = ifaces[n]["slots"]
        rows, decls = [], []
        for s in slots:
            key = "%s::%s" % (s["owner"], s["name"])
            if s["slot"] < 3:
                rows.append('    { "%s", NULL, NULL, NULL, %d, 0, 0, 0, NULL,'
                            ' 0, 0, 0 },  /* runtime */'
                            % (key, 1 if s["slot"] else 3))
                stats["iunknown"] += 1
                continue
            argc = 1 + len(s["params"])
            flags = []
            if s["ret"] == "void":
                flags.append("WINECOM_F_RET_VOID")
            if key in hand_index:
                rows.append('    { "%s", NULL, NULL, NULL, %d,'
                            ' WINECOM_F_HAND, %d, 0, NULL, 0, 0, 0 },'
                            % (key, argc, hand_index[key]))
                stats["hand"] += 1
                continue
            plan = None
            reason = REFUSALS.get(key)
            if reason is None:
                try:
                    plan = classify(key, s, ifaces, iface_index, byval_ok,
                                    dword_signed, bearing, why_bearing)
                except Refused as e:
                    reason = str(e)
            if reason is not None:
                rows.append('    { "%s",\n      "%s: %s",\n'
                            '      NULL, NULL, %d, 0, 0, 0, NULL, 0, 0, 0 },'
                            % (key, key, reason.replace('"', "'"), argc))
                stats["refused"] += 1
                refusal_log.append((n, s["slot"], key, reason))
                continue
            if plan.ret_via_arg:
                flags.append("WINECOM_F_RET_VIA_ARG")
            cls, xaux, caux = plan.cls, plan.xaux, plan.caux
            cname = xname = kname = "NULL"
            if any(c != CA["PASS"] for c in cls):
                cname = "cls_%s_%d" % (n, s["slot"])
                decls.append("static const unsigned char %s[] = { %s };"
                             % (cname, ", ".join(CA_NAME[c] for c in cls)))
            # Emitted whenever a parameter is interface-typed, NOT when the
            # values happen to be non-zero: roster index 0 is a real
            # interface and `any(xaux)` would drop the row that names it.
            if plan.xmask:
                xname = "xaux_%s_%d" % (n, s["slot"])
                decls.append("static const unsigned char %s[] = { %s };"
                             % (xname, ", ".join(str(x) for x in xaux)))
            if any(caux):
                kname = "caux_%s_%d" % (n, s["slot"])
                decls.append("static const unsigned char %s[] = { %s };"
                             % (kname, ", ".join(str(x) for x in caux)))
            for np in plan.narrow_params:
                narrow_log.append((key,) + np)
            rows.append('    { "%s", NULL, %s, %s, %d, %s, %d, %d, %s, 0, 0,'
                        ' 0x%02x, 0x%02x, 0x%02x, 0x%02x, 0x%04x, 0x%04x },'
                        % (key, cname, xname, argc,
                           "|".join(flags) or "0", plan.aux, plan.aux2, kname,
                           plan.xmask, plan.narrowmask, plan.narrowwide,
                           plan.narrowsign, plan.dwordmask, plan.dwordsign))
            stats["marshalled"] += 1

        if len(slots) <= 3:
            # Only IUnknown itself: its three slots are served by the runtime
            # from the proxy table without crossing.  Every OTHER interface
            # gets a real table -- a NULL table refuses every slot, which is
            # exactly the Device1..Device15 hole this generator was written
            # to close.
            stats["identity"] += 1
            tables.append((n, None))
            continue
        tables.append((n, (decls, rows)))

    for n, t in tables:
        if t is None:
            continue
        decls, rows = t
        w("")
        for d in decls:
            w(d)
        w("static const struct winecom_slot slots_%s[%d] =\n{" % (n, len(rows)))
        for r in rows:
            w(r)
        w("};")

    w("\nstatic const struct winecom_iface %s_com_ifaces[%s_IFACE_COUNT] =\n{"
      % (prefix, prefix.upper()))
    for n, t in tables:
        w('    { "%s", %s,\n      %d, %s, 0 },'
          % (n, c_guid(ifaces[n]["uuid"]), len(ifaces[n]["slots"]),
             "NULL" if t is None else "slots_" + n))
    w("};")

    w("\n/* %d slot(s) marshalled, %d hand-written, %d refused with a named\n"
      " * reason, %d IUnknown slot(s) served by the runtime; %d interface(s)\n"
      " * (IUnknown itself) carry identity rows only. */"
      % (stats["marshalled"], stats["hand"], stats["refused"],
         stats["iunknown"], stats["identity"]))
    return "\n".join(out) + "\n", stats, refusal_log, narrow_log


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--roster",
                    default=os.path.join(HERE, "interfaces_d3d12.json"))
    ap.add_argument("--headers",
                    default=os.path.join(HERE, "generated-headers"),
                    help="directory holding vkd3d's widl-generated headers")
    ap.add_argument("--prefix", default="d3d12")
    ap.add_argument("--out")
    ap.add_argument("--check", metavar="FILE")
    ap.add_argument("--report", action="store_true")
    args = ap.parse_args()

    with open(args.roster) as fh:
        roster = json.load(fh)
    text, stats, refusals, narrows = generate(roster, args.prefix,
                                              args.headers)

    print("surface %s: %d marshalled, %d hand-written, %d refused, "
          "%d IUnknown, %d identity-only interface(s)"
          % (roster["surface"], stats["marshalled"], stats["hand"],
             stats["refused"], stats["iunknown"], stats["identity"]))

    if args.report:
        print("\nnarrow by-value parameters (extended by the runtime):")
        for key, i, base, width, signed in narrows:
            print("  %-60s arg %d: %d-byte %s%s"
                  % (key, i + 1, width, "signed " if signed else "", base))
        print("\nrefused slots, by reason:")
        seen = {}
        for n, slot, key, reason in refusals:
            seen.setdefault(reason.split(';')[0][:76], []).append(key)
        for reason, keys in sorted(seen.items(), key=lambda kv: -len(kv[1])):
            uniq = sorted(set(keys))
            print("  %4d  %s" % (len(keys), reason))
            for k in uniq[:8]:
                print("          %s" % k)
            if len(uniq) > 8:
                print("          ... and %d more distinct method(s)"
                      % (len(uniq) - 8))

    if args.check:
        with open(args.check) as fh:
            have = fh.read()
        if have == text:
            print("\ncheck passed: %s matches the roster" % args.check)
            return 0
        sys.exit("\ngen_winecom: %s has DRIFTED from the roster.  Regenerate "
                 "it (--out) and re-run every gate." % args.check)

    if args.out:
        with open(args.out, "w") as fh:
            fh.write(text)
        print("\nwrote %s" % args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
