/*** Autogenerated by WIDL 11.15 from vkd3d_dxgibase.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __vkd3d_dxgibase_h__
#define __vkd3d_dxgibase_h__

/* Forward declarations */

/* Headers for imported files */

#include <vkd3d_windows.h>
#include <vkd3d_dxgiformat.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DXGI_ERROR_INVALID_CALL
#define DXGI_ERROR_INVALID_CALL   _HRESULT_TYPEDEF_(0x887a0001)
#endif
#ifndef DXGI_ERROR_DEVICE_REMOVED
#define DXGI_ERROR_DEVICE_REMOVED _HRESULT_TYPEDEF_(0x887a0005)
#endif
#ifndef DXGI_ERROR_SDK_COMPONENT_MISSING
#define DXGI_ERROR_SDK_COMPONENT_MISSING _HRESULT_TYPEDEF_(0x887a002d)
#endif
#ifndef DXGI_ERROR_ALREADY_EXISTS
#define DXGI_ERROR_ALREADY_EXISTS _HRESULT_TYPEDEF_(0x887a0036)
#endif
#ifndef DXGI_STATUS_OCCLUDED
#define DXGI_STATUS_OCCLUDED _HRESULT_TYPEDEF_(0x087a0001)
#endif
typedef struct DXGI_SAMPLE_DESC {
    UINT Count;
    UINT Quality;
} DXGI_SAMPLE_DESC;
typedef struct DXGI_RGB {
    float Red;
    float Green;
    float Blue;
} DXGI_RGB;
/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __vkd3d_dxgibase_h__ */
