/* GENERATED by ppc64le/shell/gen_dinput_surface.py -- do not edit.
 *
 * Marshal tables for the wine-dinput8 surface (6 interfaces, 102 vtable slots),
 * generated from ppc64le/shell/interfaces_dinput.json -- the same roster
 * dlls/dinput8/dinput8.thunks hands spec2thunk to build the guest trap
 * module.  Interface order is sorted by name, which is the order spec2thunk
 * COM mode gives the guest stub arrays; libs/winecom cross-checks every IID
 * and slot count at attach, so the two generators cannot silently disagree.
 *
 * Slot/iface types and WINECOM_CA_* classes come from include/wine/winecom.h,
 * which must be included before this file.
 */

enum dinput8_iface_index
{
    DINPUT8_IFACE_IDirectInput8A = 0,
    DINPUT8_IFACE_IDirectInput8W = 1,
    DINPUT8_IFACE_IDirectInputDevice8A = 2,
    DINPUT8_IFACE_IDirectInputDevice8W = 3,
    DINPUT8_IFACE_IDirectInputEffect = 4,
    DINPUT8_IFACE_IUnknown = 5,
    DINPUT8_IFACE_COUNT = 6
};

#define DINPUT8_HAND_COUNT 6
/* hand_funcs[] order in dlls/dinput8/guestcom.c:
 *   0 hand_enum_cb2
 *   1 hand_enum_cb1
 *   2 hand_enum_semantics_a
 *   3 hand_enum_semantics_w
 *   4 hand_configure_devices
 *   5 hand_enum_created_fx
 */

static const unsigned char cls_IDirectInput8A_CreateDevice[3] = { WINECOM_CA_PASS, WINECOM_CA_IFACE_OUT_STATIC, WINECOM_CA_IFACE_IN };
static const unsigned char xaux_IDirectInput8A_CreateDevice[3] = { 0, 2, 5 };

static const struct winecom_slot slots_IDirectInput8A[11] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInput8A::CreateDevice", NULL, cls_IDirectInput8A_CreateDevice, xaux_IDirectInput8A_CreateDevice, 4, 0, 0, 0, NULL, 0, 0, 0x06 },
    { "IDirectInput8A::EnumDevices", NULL, NULL, NULL, 5, WINECOM_F_HAND, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInput8A::GetDeviceStatus", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInput8A::RunControlPanel", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInput8A::Initialize", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInput8A::FindDevice", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInput8A::EnumDevicesBySemantics", NULL, NULL, NULL, 6, WINECOM_F_HAND, 2, 0, NULL, 0, 0, 0 },
    { "IDirectInput8A::ConfigureDevices", NULL, NULL, NULL, 5, WINECOM_F_HAND, 4, 0, NULL, 0, 0, 0 },
};
static const unsigned char cls_IDirectInput8W_CreateDevice[3] = { WINECOM_CA_PASS, WINECOM_CA_IFACE_OUT_STATIC, WINECOM_CA_IFACE_IN };
static const unsigned char xaux_IDirectInput8W_CreateDevice[3] = { 0, 3, 5 };

static const struct winecom_slot slots_IDirectInput8W[11] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInput8W::CreateDevice", NULL, cls_IDirectInput8W_CreateDevice, xaux_IDirectInput8W_CreateDevice, 4, 0, 0, 0, NULL, 0, 0, 0x06 },
    { "IDirectInput8W::EnumDevices", NULL, NULL, NULL, 5, WINECOM_F_HAND, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInput8W::GetDeviceStatus", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInput8W::RunControlPanel", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInput8W::Initialize", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInput8W::FindDevice", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInput8W::EnumDevicesBySemantics", NULL, NULL, NULL, 6, WINECOM_F_HAND, 3, 0, NULL, 0, 0, 0 },
    { "IDirectInput8W::ConfigureDevices", NULL, NULL, NULL, 5, WINECOM_F_HAND, 4, 0, NULL, 0, 0, 0 },
};
static const unsigned char cls_IDirectInputDevice8A_CreateEffect[4] = { WINECOM_CA_PASS, WINECOM_CA_PASS, WINECOM_CA_IFACE_OUT_STATIC, WINECOM_CA_IFACE_IN };
static const unsigned char xaux_IDirectInputDevice8A_CreateEffect[4] = { 0, 0, 4, 5 };

static const struct winecom_slot slots_IDirectInputDevice8A[32] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceA::GetCapabilities", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceA::EnumObjects", NULL, NULL, NULL, 4, WINECOM_F_HAND, 1, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceA::GetProperty", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceA::SetProperty", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceA::Acquire", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceA::Unacquire", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceA::GetDeviceState", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceA::GetDeviceData", NULL, NULL, NULL, 5, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceA::SetDataFormat", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceA::SetEventNotification", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceA::SetCooperativeLevel", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceA::GetObjectInfo", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceA::GetDeviceInfo", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceA::RunControlPanel", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceA::Initialize", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice2A::CreateEffect", NULL, cls_IDirectInputDevice8A_CreateEffect, xaux_IDirectInputDevice8A_CreateEffect, 5, 0, 0, 0, NULL, 0, 0, 0x0c },
    { "IDirectInputDevice2A::EnumEffects", NULL, NULL, NULL, 4, WINECOM_F_HAND, 1, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice2A::GetEffectInfo", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice2A::GetForceFeedbackState", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice2A::SendForceFeedbackCommand", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice2A::EnumCreatedEffectObjects", NULL, NULL, NULL, 4, WINECOM_F_HAND, 5, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice2A::Escape", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice2A::Poll", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice2A::SendDeviceData", NULL, NULL, NULL, 5, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice7A::EnumEffectsInFile", NULL, NULL, NULL, 5, WINECOM_F_HAND, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice7A::WriteEffectToFile", NULL, NULL, NULL, 5, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice8A::BuildActionMap", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice8A::SetActionMap", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice8A::GetImageInfo", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0, 0, 0 },
};
static const unsigned char cls_IDirectInputDevice8W_CreateEffect[4] = { WINECOM_CA_PASS, WINECOM_CA_PASS, WINECOM_CA_IFACE_OUT_STATIC, WINECOM_CA_IFACE_IN };
static const unsigned char xaux_IDirectInputDevice8W_CreateEffect[4] = { 0, 0, 4, 5 };

static const struct winecom_slot slots_IDirectInputDevice8W[32] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceW::GetCapabilities", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceW::EnumObjects", NULL, NULL, NULL, 4, WINECOM_F_HAND, 1, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceW::GetProperty", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceW::SetProperty", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceW::Acquire", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceW::Unacquire", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceW::GetDeviceState", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceW::GetDeviceData", NULL, NULL, NULL, 5, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceW::SetDataFormat", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceW::SetEventNotification", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceW::SetCooperativeLevel", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceW::GetObjectInfo", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceW::GetDeviceInfo", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceW::RunControlPanel", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDeviceW::Initialize", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice2W::CreateEffect", NULL, cls_IDirectInputDevice8W_CreateEffect, xaux_IDirectInputDevice8W_CreateEffect, 5, 0, 0, 0, NULL, 0, 0, 0x0c },
    { "IDirectInputDevice2W::EnumEffects", NULL, NULL, NULL, 4, WINECOM_F_HAND, 1, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice2W::GetEffectInfo", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice2W::GetForceFeedbackState", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice2W::SendForceFeedbackCommand", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice2W::EnumCreatedEffectObjects", NULL, NULL, NULL, 4, WINECOM_F_HAND, 5, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice2W::Escape", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice2W::Poll", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice2W::SendDeviceData", NULL, NULL, NULL, 5, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice7W::EnumEffectsInFile", NULL, NULL, NULL, 5, WINECOM_F_HAND, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice7W::WriteEffectToFile", NULL, NULL, NULL, 5, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice8W::BuildActionMap", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice8W::SetActionMap", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputDevice8W::GetImageInfo", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0, 0, 0 },
};

static const struct winecom_slot slots_IDirectInputEffect[13] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputEffect::Initialize", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputEffect::GetEffectGuid", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputEffect::GetParameters", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputEffect::SetParameters", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputEffect::Start", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputEffect::Stop", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputEffect::GetEffectStatus", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputEffect::Download", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputEffect::Unload", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },
    { "IDirectInputEffect::Escape", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0, 0, 0 },
};

static const struct winecom_iface dinput8_com_ifaces[DINPUT8_IFACE_COUNT] =
{
    { "IDirectInput8A", {0xbf798030,0x483a,0x4da2,{0xaa,0x99,0x5d,0x64,0xed,0x36,0x97,0x00}},
      11, slots_IDirectInput8A, 0 },
    { "IDirectInput8W", {0xbf798031,0x483a,0x4da2,{0xaa,0x99,0x5d,0x64,0xed,0x36,0x97,0x00}},
      11, slots_IDirectInput8W, 0 },
    { "IDirectInputDevice8A", {0x54d41080,0xdc15,0x4833,{0xa4,0x1b,0x74,0x8f,0x73,0xa3,0x81,0x79}},
      32, slots_IDirectInputDevice8A, 0 },
    { "IDirectInputDevice8W", {0x54d41081,0xdc15,0x4833,{0xa4,0x1b,0x74,0x8f,0x73,0xa3,0x81,0x79}},
      32, slots_IDirectInputDevice8W, 0 },
    { "IDirectInputEffect", {0xe7e1f7c0,0x88d2,0x11d0,{0x9a,0xd0,0x00,0xa0,0xc9,0xa0,0x6e,0x35}},
      13, slots_IDirectInputEffect, 0 },
    { "IUnknown", {0x00000000,0x0000,0x0000,{0xc0,0x00,0x00,0x00,0x00,0x00,0x00,0x46}},
      3, NULL, 0 },
};

/*
 * 70 slot(s) marshalled, 14 hand-written, 0 refused with a named reason, 18
 * IUnknown slot(s) served by the runtime.
 *
 * Hand-written (a guest callback swapped for one of ntdll's trampolines at
 * the moment it arrives): IDirectInput8A::EnumDevices,
 * IDirectInput8A::EnumDevicesBySemantics, IDirectInput8A::ConfigureDevices,
 * IDirectInput8W::EnumDevices, IDirectInput8W::EnumDevicesBySemantics,
 * IDirectInput8W::ConfigureDevices, IDirectInputDeviceA::EnumObjects,
 * IDirectInputDevice2A::EnumEffects,
 * IDirectInputDevice2A::EnumCreatedEffectObjects,
 * IDirectInputDevice7A::EnumEffectsInFile,
 * IDirectInputDeviceW::EnumObjects, IDirectInputDevice2W::EnumEffects,
 * IDirectInputDevice2W::EnumCreatedEffectObjects,
 * IDirectInputDevice7W::EnumEffectsInFile
 */
