/* GENERATED by ppc64le/audio/gen_winecom.py -- do not edit.
 *
 * Marshal tables for the wine-dsound surface (21 interfaces, 202 vtable slots),
 * generated from ppc64le/audio/interfaces_dsound.json -- the same roster the guest
 * thunk module's .thunks file hands spec2thunk.  Interface order is
 * sorted by name, which is the order spec2thunk COM mode gives the
 * guest stub arrays; libs/winecom cross-checks every IID and slot
 * count at attach, so the two generators cannot silently disagree.
 *
 * Slot/iface types and WINECOM_CA_* classes come from
 * include/wine/winecom.h, which must be included before this file.
 */

enum dsound_iface_index
{
    DSOUND_IFACE_IDirectSound = 0,
    DSOUND_IFACE_IDirectSound3DBuffer = 1,
    DSOUND_IFACE_IDirectSound3DListener = 2,
    DSOUND_IFACE_IDirectSound8 = 3,
    DSOUND_IFACE_IDirectSoundBuffer = 4,
    DSOUND_IFACE_IDirectSoundBuffer8 = 5,
    DSOUND_IFACE_IDirectSoundCapture = 6,
    DSOUND_IFACE_IDirectSoundCaptureBuffer = 7,
    DSOUND_IFACE_IDirectSoundCaptureBuffer8 = 8,
    DSOUND_IFACE_IDirectSoundFXChorus = 9,
    DSOUND_IFACE_IDirectSoundFXCompressor = 10,
    DSOUND_IFACE_IDirectSoundFXDistortion = 11,
    DSOUND_IFACE_IDirectSoundFXEcho = 12,
    DSOUND_IFACE_IDirectSoundFXFlanger = 13,
    DSOUND_IFACE_IDirectSoundFXGargle = 14,
    DSOUND_IFACE_IDirectSoundFXI3DL2Reverb = 15,
    DSOUND_IFACE_IDirectSoundFXParamEq = 16,
    DSOUND_IFACE_IDirectSoundFXWavesReverb = 17,
    DSOUND_IFACE_IDirectSoundFullDuplex = 18,
    DSOUND_IFACE_IDirectSoundNotify = 19,
    DSOUND_IFACE_IKsPropertySet = 20,
    DSOUND_IFACE_COUNT = 21
};

#define DSOUND_HAND_COUNT 5

/* hand_funcs[] order in the client module:
 *   0 hand_create_sound_buffer
 *   1 hand_create_capture_buffer
 *   2 hand_ffffff_i
 *   3 hand_fff_i
 *   4 hand_f_i
 */


static const unsigned char cls_IDirectSound_5[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_IFACE_OUT_STATIC };
static const unsigned char xaux_IDirectSound_5[] = { 4, 4 };
static const struct winecom_slot slots_IDirectSound[11] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IDirectSound::CreateSoundBuffer", NULL, NULL, NULL, 4, WINECOM_F_HAND, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound::GetCaps", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound::DuplicateSoundBuffer", NULL, cls_IDirectSound_5, xaux_IDirectSound_5, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x03 },
    { "IDirectSound::SetCooperativeLevel", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound::Compact", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound::GetSpeakerConfig", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound::SetSpeakerConfig", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound::Initialize", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const struct winecom_slot slots_IDirectSound3DBuffer[21] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IDirectSound3DBuffer::GetAllParameters", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound3DBuffer::GetConeAngles", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound3DBuffer::GetConeOrientation", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound3DBuffer::GetConeOutsideVolume", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound3DBuffer::GetMaxDistance", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound3DBuffer::GetMinDistance", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound3DBuffer::GetMode", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound3DBuffer::GetPosition", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound3DBuffer::GetVelocity", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound3DBuffer::SetAllParameters", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound3DBuffer::SetConeAngles", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound3DBuffer::SetConeOrientation", NULL, NULL, NULL, 5, WINECOM_F_HAND|WINECOM_F_REV, 3, 0, NULL, 0x07, 0x00, 0x00 },
    { "IDirectSound3DBuffer::SetConeOutsideVolume", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound3DBuffer::SetMaxDistance", NULL, NULL, NULL, 3, WINECOM_F_HAND|WINECOM_F_REV, 4, 0, NULL, 0x01, 0x00, 0x00 },
    { "IDirectSound3DBuffer::SetMinDistance", NULL, NULL, NULL, 3, WINECOM_F_HAND|WINECOM_F_REV, 4, 0, NULL, 0x01, 0x00, 0x00 },
    { "IDirectSound3DBuffer::SetMode", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound3DBuffer::SetPosition", NULL, NULL, NULL, 5, WINECOM_F_HAND|WINECOM_F_REV, 3, 0, NULL, 0x07, 0x00, 0x00 },
    { "IDirectSound3DBuffer::SetVelocity", NULL, NULL, NULL, 5, WINECOM_F_HAND|WINECOM_F_REV, 3, 0, NULL, 0x07, 0x00, 0x00 },
};

static const struct winecom_slot slots_IDirectSound3DListener[18] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IDirectSound3DListener::GetAllParameters", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound3DListener::GetDistanceFactor", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound3DListener::GetDopplerFactor", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound3DListener::GetOrientation", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound3DListener::GetPosition", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound3DListener::GetRolloffFactor", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound3DListener::GetVelocity", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound3DListener::SetAllParameters", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound3DListener::SetDistanceFactor", NULL, NULL, NULL, 3, WINECOM_F_HAND|WINECOM_F_REV, 4, 0, NULL, 0x01, 0x00, 0x00 },
    { "IDirectSound3DListener::SetDopplerFactor", NULL, NULL, NULL, 3, WINECOM_F_HAND|WINECOM_F_REV, 4, 0, NULL, 0x01, 0x00, 0x00 },
    { "IDirectSound3DListener::SetOrientation", NULL, NULL, NULL, 8, WINECOM_F_HAND|WINECOM_F_REV, 2, 0, NULL, 0x3f, 0x00, 0x00 },
    { "IDirectSound3DListener::SetPosition", NULL, NULL, NULL, 5, WINECOM_F_HAND|WINECOM_F_REV, 3, 0, NULL, 0x07, 0x00, 0x00 },
    { "IDirectSound3DListener::SetRolloffFactor", NULL, NULL, NULL, 3, WINECOM_F_HAND|WINECOM_F_REV, 4, 0, NULL, 0x01, 0x00, 0x00 },
    { "IDirectSound3DListener::SetVelocity", NULL, NULL, NULL, 5, WINECOM_F_HAND|WINECOM_F_REV, 3, 0, NULL, 0x07, 0x00, 0x00 },
    { "IDirectSound3DListener::CommitDeferredSettings", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const unsigned char cls_IDirectSound8_5[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_IFACE_OUT_STATIC };
static const unsigned char xaux_IDirectSound8_5[] = { 4, 4 };
static const struct winecom_slot slots_IDirectSound8[12] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IDirectSound8::CreateSoundBuffer", NULL, NULL, NULL, 4, WINECOM_F_HAND, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound8::GetCaps", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound8::DuplicateSoundBuffer", NULL, cls_IDirectSound8_5, xaux_IDirectSound8_5, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x03 },
    { "IDirectSound8::SetCooperativeLevel", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound8::Compact", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound8::GetSpeakerConfig", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound8::SetSpeakerConfig", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound8::Initialize", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSound8::VerifyCertification", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const unsigned char cls_IDirectSoundBuffer_10[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_PASS };
static const unsigned char xaux_IDirectSoundBuffer_10[] = { 0, 0 };
static const struct winecom_slot slots_IDirectSoundBuffer[21] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IDirectSoundBuffer::GetCaps", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer::GetCurrentPosition", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer::GetFormat", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer::GetVolume", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer::GetPan", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer::GetFrequency", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer::GetStatus", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer::Initialize", NULL, cls_IDirectSoundBuffer_10, xaux_IDirectSoundBuffer_10, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IDirectSoundBuffer::Lock", NULL, NULL, NULL, 8, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer::Play", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer::SetCurrentPosition", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer::SetFormat", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer::SetVolume", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer::SetPan", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer::SetFrequency", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer::Stop", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer::Unlock", NULL, NULL, NULL, 5, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer::Restore", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const unsigned char cls_IDirectSoundBuffer8_10[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_PASS };
static const unsigned char xaux_IDirectSoundBuffer8_10[] = { 0, 0 };
static const unsigned char cls_IDirectSoundBuffer8_23[] = { WINECOM_CA_PASS, WINECOM_CA_PASS, WINECOM_CA_RIID, WINECOM_CA_PPV_OUT };
static const struct winecom_slot slots_IDirectSoundBuffer8[24] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IDirectSoundBuffer8::GetCaps", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer8::GetCurrentPosition", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer8::GetFormat", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer8::GetVolume", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer8::GetPan", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer8::GetFrequency", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer8::GetStatus", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer8::Initialize", NULL, cls_IDirectSoundBuffer8_10, xaux_IDirectSoundBuffer8_10, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IDirectSoundBuffer8::Lock", NULL, NULL, NULL, 8, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer8::Play", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer8::SetCurrentPosition", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer8::SetFormat", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer8::SetVolume", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer8::SetPan", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer8::SetFrequency", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer8::Stop", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer8::Unlock", NULL, NULL, NULL, 5, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer8::Restore", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer8::SetFX", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer8::AcquireResources", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundBuffer8::GetObjectInPath", NULL, cls_IDirectSoundBuffer8_23, NULL, 5, 0, 2, 0, NULL, 0x00, 0x00, 0x00 },
};

static const struct winecom_slot slots_IDirectSoundCapture[6] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IDirectSoundCapture::CreateCaptureBuffer", NULL, NULL, NULL, 4, WINECOM_F_HAND, 1, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundCapture::GetCaps", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundCapture::Initialize", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const unsigned char cls_IDirectSoundCaptureBuffer_7[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_PASS };
static const unsigned char xaux_IDirectSoundCaptureBuffer_7[] = { 6, 0 };
static const struct winecom_slot slots_IDirectSoundCaptureBuffer[12] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IDirectSoundCaptureBuffer::GetCaps", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundCaptureBuffer::GetCurrentPosition", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundCaptureBuffer::GetFormat", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundCaptureBuffer::GetStatus", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundCaptureBuffer::Initialize", NULL, cls_IDirectSoundCaptureBuffer_7, xaux_IDirectSoundCaptureBuffer_7, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IDirectSoundCaptureBuffer::Lock", NULL, NULL, NULL, 8, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundCaptureBuffer::Start", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundCaptureBuffer::Stop", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundCaptureBuffer::Unlock", NULL, NULL, NULL, 5, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const unsigned char cls_IDirectSoundCaptureBuffer8_7[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_PASS };
static const unsigned char xaux_IDirectSoundCaptureBuffer8_7[] = { 6, 0 };
static const unsigned char cls_IDirectSoundCaptureBuffer8_12[] = { WINECOM_CA_PASS, WINECOM_CA_PASS, WINECOM_CA_RIID, WINECOM_CA_PPV_OUT };
static const struct winecom_slot slots_IDirectSoundCaptureBuffer8[14] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IDirectSoundCaptureBuffer::GetCaps", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundCaptureBuffer::GetCurrentPosition", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundCaptureBuffer::GetFormat", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundCaptureBuffer::GetStatus", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundCaptureBuffer::Initialize", NULL, cls_IDirectSoundCaptureBuffer8_7, xaux_IDirectSoundCaptureBuffer8_7, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IDirectSoundCaptureBuffer::Lock", NULL, NULL, NULL, 8, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundCaptureBuffer::Start", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundCaptureBuffer::Stop", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundCaptureBuffer::Unlock", NULL, NULL, NULL, 5, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundCaptureBuffer8::GetObjectInPath", NULL, cls_IDirectSoundCaptureBuffer8_12, NULL, 5, 0, 2, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundCaptureBuffer8::GetFXStatus", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const struct winecom_slot slots_IDirectSoundFXChorus[5] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IDirectSoundFXChorus::SetAllParameters", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundFXChorus::GetAllParameters", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const struct winecom_slot slots_IDirectSoundFXCompressor[5] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IDirectSoundFXCompressor::SetAllParameters", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundFXCompressor::GetAllParameters", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const struct winecom_slot slots_IDirectSoundFXDistortion[5] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IDirectSoundFXDistortion::SetAllParameters", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundFXDistortion::GetAllParameters", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const struct winecom_slot slots_IDirectSoundFXEcho[5] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IDirectSoundFXEcho::SetAllParameters", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundFXEcho::GetAllParameters", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const struct winecom_slot slots_IDirectSoundFXFlanger[5] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IDirectSoundFXFlanger::SetAllParameters", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundFXFlanger::GetAllParameters", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const struct winecom_slot slots_IDirectSoundFXGargle[5] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IDirectSoundFXGargle::SetAllParameters", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundFXGargle::GetAllParameters", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const struct winecom_slot slots_IDirectSoundFXI3DL2Reverb[9] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IDirectSoundFXI3DL2Reverb::SetAllParameters", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundFXI3DL2Reverb::GetAllParameters", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundFXI3DL2Reverb::SetPreset", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundFXI3DL2Reverb::GetPreset", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundFXI3DL2Reverb::SetQuality", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundFXI3DL2Reverb::GetQuality", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const struct winecom_slot slots_IDirectSoundFXParamEq[5] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IDirectSoundFXParamEq::SetAllParameters", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundFXParamEq::GetAllParameters", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const struct winecom_slot slots_IDirectSoundFXWavesReverb[5] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IDirectSoundFXWavesReverb::SetAllParameters", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IDirectSoundFXWavesReverb::GetAllParameters", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const unsigned char cls_IDirectSoundFullDuplex_3[] = { WINECOM_CA_PASS, WINECOM_CA_PASS, WINECOM_CA_PASS, WINECOM_CA_PASS, WINECOM_CA_PASS, WINECOM_CA_PASS, WINECOM_CA_IFACE_OUT_STATIC, WINECOM_CA_IFACE_OUT_STATIC };
static const unsigned char xaux_IDirectSoundFullDuplex_3[] = { 0, 0, 0, 0, 0, 0, 8, 5 };
static const struct winecom_slot slots_IDirectSoundFullDuplex[4] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IDirectSoundFullDuplex::Initialize", NULL, cls_IDirectSoundFullDuplex_3, xaux_IDirectSoundFullDuplex_3, 9, 0, 0, 0, NULL, 0x00, 0x00, 0xc0 },
};

static const struct winecom_slot slots_IDirectSoundNotify[4] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IDirectSoundNotify::SetNotificationPositions", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const struct winecom_slot slots_IKsPropertySet[6] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IKsPropertySet::Get", NULL, NULL, NULL, 8, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IKsPropertySet::Set", NULL, NULL, NULL, 7, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IKsPropertySet::QuerySupport", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const struct winecom_iface dsound_com_ifaces[DSOUND_IFACE_COUNT] =
{
    { "IDirectSound", {0x279afa83,0x4981,0x11ce,{0xa5,0x21,0x00,0x20,0xaf,0x0b,0xe5,0x60}},
      11, slots_IDirectSound, 0 },
    { "IDirectSound3DBuffer", {0x279afa86,0x4981,0x11ce,{0xa5,0x21,0x00,0x20,0xaf,0x0b,0xe5,0x60}},
      21, slots_IDirectSound3DBuffer, 0 },
    { "IDirectSound3DListener", {0x279afa84,0x4981,0x11ce,{0xa5,0x21,0x00,0x20,0xaf,0x0b,0xe5,0x60}},
      18, slots_IDirectSound3DListener, 0 },
    { "IDirectSound8", {0xc50a7e93,0xf395,0x4834,{0x9e,0xf6,0x7f,0xa9,0x9d,0xe5,0x09,0x66}},
      12, slots_IDirectSound8, 0 },
    { "IDirectSoundBuffer", {0x279afa85,0x4981,0x11ce,{0xa5,0x21,0x00,0x20,0xaf,0x0b,0xe5,0x60}},
      21, slots_IDirectSoundBuffer, 0 },
    { "IDirectSoundBuffer8", {0x6825a449,0x7524,0x4d82,{0x92,0x0f,0x50,0xe3,0x6a,0xb3,0xab,0x1e}},
      24, slots_IDirectSoundBuffer8, 0 },
    { "IDirectSoundCapture", {0xb0210781,0x89cd,0x11d0,{0xaf,0x08,0x00,0xa0,0xc9,0x25,0xcd,0x16}},
      6, slots_IDirectSoundCapture, 0 },
    { "IDirectSoundCaptureBuffer", {0xb0210782,0x89cd,0x11d0,{0xaf,0x08,0x00,0xa0,0xc9,0x25,0xcd,0x16}},
      12, slots_IDirectSoundCaptureBuffer, 0 },
    { "IDirectSoundCaptureBuffer8", {0x00990df4,0x0dbb,0x4872,{0x83,0x3e,0x6d,0x30,0x3e,0x80,0xae,0xb6}},
      14, slots_IDirectSoundCaptureBuffer8, 0 },
    { "IDirectSoundFXChorus", {0x880842e3,0x145f,0x43e6,{0xa9,0x34,0xa7,0x18,0x06,0xe5,0x05,0x47}},
      5, slots_IDirectSoundFXChorus, 0 },
    { "IDirectSoundFXCompressor", {0x4bbd1154,0x62f6,0x4e2c,{0xa1,0x5c,0xd3,0xb6,0xc4,0x17,0xf7,0xa0}},
      5, slots_IDirectSoundFXCompressor, 0 },
    { "IDirectSoundFXDistortion", {0x8ecf4326,0x455f,0x4d8b,{0xbd,0xa9,0x8d,0x5d,0x3e,0x9e,0x3e,0x0b}},
      5, slots_IDirectSoundFXDistortion, 0 },
    { "IDirectSoundFXEcho", {0x8bd28edf,0x50db,0x4e92,{0xa2,0xbd,0x44,0x54,0x88,0xd1,0xed,0x42}},
      5, slots_IDirectSoundFXEcho, 0 },
    { "IDirectSoundFXFlanger", {0x903e9878,0x2c92,0x4072,{0x9b,0x2c,0xea,0x68,0xf5,0x39,0x67,0x83}},
      5, slots_IDirectSoundFXFlanger, 0 },
    { "IDirectSoundFXGargle", {0xd616f352,0xd622,0x11ce,{0xaa,0xc5,0x00,0x20,0xaf,0x0b,0x99,0xa3}},
      5, slots_IDirectSoundFXGargle, 0 },
    { "IDirectSoundFXI3DL2Reverb", {0x4b166a6a,0x0d66,0x43f3,{0x80,0xe3,0xee,0x62,0x80,0xde,0xe1,0xa4}},
      9, slots_IDirectSoundFXI3DL2Reverb, 0 },
    { "IDirectSoundFXParamEq", {0xc03ca9fe,0xfe90,0x4204,{0x80,0x78,0x82,0x33,0x4c,0xd1,0x77,0xda}},
      5, slots_IDirectSoundFXParamEq, 0 },
    { "IDirectSoundFXWavesReverb", {0x46858c3a,0x0dc6,0x45e3,{0xb7,0x60,0xd4,0xee,0xf1,0x6c,0xb3,0x25}},
      5, slots_IDirectSoundFXWavesReverb, 0 },
    { "IDirectSoundFullDuplex", {0xedcb4c7a,0xdaab,0x4216,{0xa4,0x2e,0x6c,0x50,0x59,0x6d,0xdc,0x1d}},
      4, slots_IDirectSoundFullDuplex, 0 },
    { "IDirectSoundNotify", {0xb0210783,0x89cd,0x11d0,{0xaf,0x08,0x00,0xa0,0xc9,0x25,0xcd,0x16}},
      4, slots_IDirectSoundNotify, 0 },
    { "IKsPropertySet", {0x31efac30,0x515c,0x11d0,{0xa9,0xaa,0x00,0xaa,0x00,0x61,0xbe,0x93}},
      6, slots_IKsPropertySet, 0 },
};

/* 125 slot(s) marshalled, 14 hand-written (11 of them float-bearing,
 * routed by argument shape), 0 refused with a named reason, 63
 * IUnknown slot(s) served by the runtime; 11 interface(s) carry
 * only CA_PASS rows, 0 are [local] and served by the client. */
