/* GENERATED by ppc64le/thunks/gen_repack32.py -- do not edit.
 *
 * 32<->64 struct repacks for the guest thunk surface.  A 32-bit guest lays
 * pointer members out in four bytes and aligns to four, so every aggregate
 * listed here has fields at different offsets than the native code reading
 * it expects.  Each function copies field by field at MEASURED offsets --
 * clang's own record layouts for both targets, plus a sizeof pass -- so a
 * header change moves the offsets here too rather than silently corrupting
 * a descriptor.
 *
 * repack32_X( dst, src32 )  guest 32-bit struct  -> native layout   (IN)
 * repack64_X( dst32, src )  native layout -> guest 32-bit struct    (OUT)
 *
 * Aggregates that do NOT diverge appear nowhere in this file: their guest
 * pointer is passed through untouched, exactly as on the 64-bit lane.
 */

#pragma once

#include <string.h>

/* ------------------------------------------- pointer-width SCALAR pointees
 *
 * Not an aggregate, and emitted unconditionally because it is a property of
 * the two ABIs rather than of any header: a parameter declared `HANDLE *h`
 * (or SIZE_T *, ULONG_PTR *, HMODULE * ...) points at a cell that is FOUR
 * bytes in the guest and EIGHT in the native callee.  Passing that guest
 * pointer through raw makes the callee read eight bytes of a four-byte cell
 * and, worse, write eight over it -- four bytes of the guest's own stack
 * frame or heap block, silently.
 *
 * D3D9 is where this stopped being theoretical: `HANDLE *pSharedHandle` is
 * the last parameter of EVERY resource creator -- CreateTexture,
 * CreateVertexBuffer, CreateIndexBuffer, CreateRenderTarget,
 * CreateDepthStencilSurface, CreateCubeTexture, CreateVolumeTexture,
 * CreateOffscreenPlainSurface and the three *Ex twins -- nineteen rows, i.e.
 * every way a D3D9 title can allocate anything.  [MEASURED 2026-08-30]
 *
 * THE NARROWING IS THE HONEST PART.  Going up (IN) is a zero-extend and
 * cannot lose.  Coming down (OUT) can: a handle whose high half is set does
 * not fit the guest's cell.  It is NOT clamped -- a clamped handle names a
 * different object, which is worse than none -- so the loss is reported and
 * the cell is zeroed, which is what "no shared handle" means to every caller
 * of these methods.  In practice DXVK's d3d9 answers pSharedHandle only for
 * shared resources and NT handles are 32-bit values, so this is a tripwire
 * rather than a path anything is expected to take.
 */
#ifndef WINE_REPACK32_PTRWIDTH_DEFINED
#define WINE_REPACK32_PTRWIDTH_DEFINED
/* Defined in libs/winecom, which every consumer of this header already
 * imports.  Declared here rather than included from a Wine header, because
 * this file deliberately pulls in nothing but <string.h>. */
extern void wine_repack32_ptrwidth_lost( unsigned long long v );

static inline void wine_repack32_PTRWIDTH( void *dst, const void *src32 )
{
    unsigned int lo;
    memcpy( &lo, src32, 4 );
    *(unsigned long long *)dst = (unsigned long long)lo;
}
static inline void wine_repack64_PTRWIDTH( void *dst32, const void *src )
{
    unsigned long long v = *(const unsigned long long *)src;
    unsigned int lo = (unsigned int)v;

    if (v >> 32)
    {
        static int logged;
        if (!logged)
        {
            logged = 1;
            wine_repack32_ptrwidth_lost( v );
        }
        lo = 0;
    }
    memcpy( dst32, &lo, 4 );
}
#endif

/* forward declarations: nested aggregates repack recursively */
static inline void wine_repack32_D3DADAPTER_IDENTIFIER9( void *dst, const void *src32 );
static inline void wine_repack64_D3DADAPTER_IDENTIFIER9( void *dst32, const void *src );
static inline void wine_repack32_D3DCONTENTPROTECTIONCAPS( void *dst, const void *src32 );
static inline void wine_repack64_D3DCONTENTPROTECTIONCAPS( void *dst32, const void *src );
static inline void wine_repack32_D3DDEVICE_CREATION_PARAMETERS( void *dst, const void *src32 );
static inline void wine_repack64_D3DDEVICE_CREATION_PARAMETERS( void *dst32, const void *src );
static inline void wine_repack32_D3DLOCKED_BOX( void *dst, const void *src32 );
static inline void wine_repack64_D3DLOCKED_BOX( void *dst32, const void *src );
static inline void wine_repack32_D3DLOCKED_RECT( void *dst, const void *src32 );
static inline void wine_repack64_D3DLOCKED_RECT( void *dst32, const void *src );
static inline void wine_repack32_D3DMEMORYPRESSURE( void *dst, const void *src32 );
static inline void wine_repack64_D3DMEMORYPRESSURE( void *dst32, const void *src );
static inline void wine_repack32_D3DPRESENTSTATS( void *dst, const void *src32 );
static inline void wine_repack64_D3DPRESENTSTATS( void *dst32, const void *src );
static inline void wine_repack32_D3DPRESENT_PARAMETERS( void *dst, const void *src32 );
static inline void wine_repack64_D3DPRESENT_PARAMETERS( void *dst32, const void *src );

/* D3DADAPTER_IDENTIFIER9: 1104 bytes / align 8 on a 64-bit guest, 1100 / 4 on i386 */
#define WINE_REPACK32_SIZE_D3DADAPTER_IDENTIFIER9 1100
static inline void wine_repack32_D3DADAPTER_IDENTIFIER9( void *dst, const void *src32 )
{
    memcpy( (char *)dst + 0, (const char *)src32 + 0, 512 );
    memcpy( (char *)dst + 512, (const char *)src32 + 512, 512 );
    memcpy( (char *)dst + 1024, (const char *)src32 + 1024, 32 );
    memcpy( (char *)dst + 1056, (const char *)src32 + 1056, 8 );
    memcpy( (char *)dst + 1064, (const char *)src32 + 1064, 4 );
    memcpy( (char *)dst + 1068, (const char *)src32 + 1068, 4 );
    memcpy( (char *)dst + 1072, (const char *)src32 + 1072, 4 );
    memcpy( (char *)dst + 1076, (const char *)src32 + 1076, 4 );
    memcpy( (char *)dst + 1080, (const char *)src32 + 1080, 16 );
    memcpy( (char *)dst + 1096, (const char *)src32 + 1096, 4 );
}
static inline void wine_repack64_D3DADAPTER_IDENTIFIER9( void *dst32, const void *src )
{
    memcpy( (char *)dst32 + 0, (const char *)src + 0, 512 );
    memcpy( (char *)dst32 + 512, (const char *)src + 512, 512 );
    memcpy( (char *)dst32 + 1024, (const char *)src + 1024, 32 );
    memcpy( (char *)dst32 + 1056, (const char *)src + 1056, 8 );
    memcpy( (char *)dst32 + 1064, (const char *)src + 1064, 4 );
    memcpy( (char *)dst32 + 1068, (const char *)src + 1068, 4 );
    memcpy( (char *)dst32 + 1072, (const char *)src + 1072, 4 );
    memcpy( (char *)dst32 + 1076, (const char *)src + 1076, 4 );
    memcpy( (char *)dst32 + 1080, (const char *)src + 1080, 16 );
    memcpy( (char *)dst32 + 1096, (const char *)src + 1096, 4 );
}

/* D3DCONTENTPROTECTIONCAPS: 40 bytes / align 8 on a 64-bit guest, 36 / 4 on i386 */
#define WINE_REPACK32_SIZE_D3DCONTENTPROTECTIONCAPS 36
static inline void wine_repack32_D3DCONTENTPROTECTIONCAPS( void *dst, const void *src32 )
{
    memcpy( (char *)dst + 0, (const char *)src32 + 0, 4 );
    memcpy( (char *)dst + 4, (const char *)src32 + 4, 16 );
    memcpy( (char *)dst + 20, (const char *)src32 + 20, 4 );
    memcpy( (char *)dst + 24, (const char *)src32 + 24, 4 );
    memcpy( (char *)dst + 32, (const char *)src32 + 28, 8 );
}
static inline void wine_repack64_D3DCONTENTPROTECTIONCAPS( void *dst32, const void *src )
{
    memcpy( (char *)dst32 + 0, (const char *)src + 0, 4 );
    memcpy( (char *)dst32 + 4, (const char *)src + 4, 16 );
    memcpy( (char *)dst32 + 20, (const char *)src + 20, 4 );
    memcpy( (char *)dst32 + 24, (const char *)src + 24, 4 );
    memcpy( (char *)dst32 + 28, (const char *)src + 32, 8 );
}

/* D3DDEVICE_CREATION_PARAMETERS: 24 bytes / align 8 on a 64-bit guest, 16 / 4 on i386 */
#define WINE_REPACK32_SIZE_D3DDEVICE_CREATION_PARAMETERS 16
static inline void wine_repack32_D3DDEVICE_CREATION_PARAMETERS( void *dst, const void *src32 )
{
    memcpy( (char *)dst + 0, (const char *)src32 + 0, 4 );
    memcpy( (char *)dst + 4, (const char *)src32 + 4, 4 );
    *(unsigned long long *)((char *)dst + 8) = (unsigned long long)*(const unsigned int *)((const char *)src32 + 8);
    memcpy( (char *)dst + 16, (const char *)src32 + 12, 4 );
}
static inline void wine_repack64_D3DDEVICE_CREATION_PARAMETERS( void *dst32, const void *src )
{
    memcpy( (char *)dst32 + 0, (const char *)src + 0, 4 );
    memcpy( (char *)dst32 + 4, (const char *)src + 4, 4 );
    *(unsigned int *)((char *)dst32 + 8) = (unsigned int)*(const unsigned long long *)((const char *)src + 8);
    memcpy( (char *)dst32 + 12, (const char *)src + 16, 4 );
}

/* D3DLOCKED_BOX: 16 bytes / align 8 on a 64-bit guest, 12 / 4 on i386 */
#define WINE_REPACK32_SIZE_D3DLOCKED_BOX 12
static inline void wine_repack32_D3DLOCKED_BOX( void *dst, const void *src32 )
{
    memcpy( (char *)dst + 0, (const char *)src32 + 0, 4 );
    memcpy( (char *)dst + 4, (const char *)src32 + 4, 4 );
    *(unsigned long long *)((char *)dst + 8) = (unsigned long long)*(const unsigned int *)((const char *)src32 + 8);
}
static inline void wine_repack64_D3DLOCKED_BOX( void *dst32, const void *src )
{
    memcpy( (char *)dst32 + 0, (const char *)src + 0, 4 );
    memcpy( (char *)dst32 + 4, (const char *)src + 4, 4 );
    *(unsigned int *)((char *)dst32 + 8) = (unsigned int)*(const unsigned long long *)((const char *)src + 8);
}

/* D3DLOCKED_RECT: 16 bytes / align 8 on a 64-bit guest, 8 / 4 on i386 */
#define WINE_REPACK32_SIZE_D3DLOCKED_RECT 8
static inline void wine_repack32_D3DLOCKED_RECT( void *dst, const void *src32 )
{
    memcpy( (char *)dst + 0, (const char *)src32 + 0, 4 );
    *(unsigned long long *)((char *)dst + 8) = (unsigned long long)*(const unsigned int *)((const char *)src32 + 4);
}
static inline void wine_repack64_D3DLOCKED_RECT( void *dst32, const void *src )
{
    memcpy( (char *)dst32 + 0, (const char *)src + 0, 4 );
    *(unsigned int *)((char *)dst32 + 4) = (unsigned int)*(const unsigned long long *)((const char *)src + 8);
}

/* D3DMEMORYPRESSURE: 24 bytes / align 8 on a 64-bit guest, 20 / 4 on i386 */
#define WINE_REPACK32_SIZE_D3DMEMORYPRESSURE 20
static inline void wine_repack32_D3DMEMORYPRESSURE( void *dst, const void *src32 )
{
    memcpy( (char *)dst + 0, (const char *)src32 + 0, 8 );
    memcpy( (char *)dst + 8, (const char *)src32 + 8, 8 );
    memcpy( (char *)dst + 16, (const char *)src32 + 16, 4 );
}
static inline void wine_repack64_D3DMEMORYPRESSURE( void *dst32, const void *src )
{
    memcpy( (char *)dst32 + 0, (const char *)src + 0, 8 );
    memcpy( (char *)dst32 + 8, (const char *)src + 8, 8 );
    memcpy( (char *)dst32 + 16, (const char *)src + 16, 4 );
}

/* D3DPRESENTSTATS: 32 bytes / align 8 on a 64-bit guest, 28 / 4 on i386 */
#define WINE_REPACK32_SIZE_D3DPRESENTSTATS 28
static inline void wine_repack32_D3DPRESENTSTATS( void *dst, const void *src32 )
{
    memcpy( (char *)dst + 0, (const char *)src32 + 0, 4 );
    memcpy( (char *)dst + 4, (const char *)src32 + 4, 4 );
    memcpy( (char *)dst + 8, (const char *)src32 + 8, 4 );
    memcpy( (char *)dst + 16, (const char *)src32 + 12, 8 );
    memcpy( (char *)dst + 24, (const char *)src32 + 20, 8 );
}
static inline void wine_repack64_D3DPRESENTSTATS( void *dst32, const void *src )
{
    memcpy( (char *)dst32 + 0, (const char *)src + 0, 4 );
    memcpy( (char *)dst32 + 4, (const char *)src + 4, 4 );
    memcpy( (char *)dst32 + 8, (const char *)src + 8, 4 );
    memcpy( (char *)dst32 + 12, (const char *)src + 16, 8 );
    memcpy( (char *)dst32 + 20, (const char *)src + 24, 8 );
}

/* D3DPRESENT_PARAMETERS: 64 bytes / align 8 on a 64-bit guest, 56 / 4 on i386 */
#define WINE_REPACK32_SIZE_D3DPRESENT_PARAMETERS 56
static inline void wine_repack32_D3DPRESENT_PARAMETERS( void *dst, const void *src32 )
{
    memcpy( (char *)dst + 0, (const char *)src32 + 0, 4 );
    memcpy( (char *)dst + 4, (const char *)src32 + 4, 4 );
    memcpy( (char *)dst + 8, (const char *)src32 + 8, 4 );
    memcpy( (char *)dst + 12, (const char *)src32 + 12, 4 );
    memcpy( (char *)dst + 16, (const char *)src32 + 16, 4 );
    memcpy( (char *)dst + 20, (const char *)src32 + 20, 4 );
    memcpy( (char *)dst + 24, (const char *)src32 + 24, 4 );
    *(unsigned long long *)((char *)dst + 32) = (unsigned long long)*(const unsigned int *)((const char *)src32 + 28);
    memcpy( (char *)dst + 40, (const char *)src32 + 32, 4 );
    memcpy( (char *)dst + 44, (const char *)src32 + 36, 4 );
    memcpy( (char *)dst + 48, (const char *)src32 + 40, 4 );
    memcpy( (char *)dst + 52, (const char *)src32 + 44, 4 );
    memcpy( (char *)dst + 56, (const char *)src32 + 48, 4 );
    memcpy( (char *)dst + 60, (const char *)src32 + 52, 4 );
}
static inline void wine_repack64_D3DPRESENT_PARAMETERS( void *dst32, const void *src )
{
    memcpy( (char *)dst32 + 0, (const char *)src + 0, 4 );
    memcpy( (char *)dst32 + 4, (const char *)src + 4, 4 );
    memcpy( (char *)dst32 + 8, (const char *)src + 8, 4 );
    memcpy( (char *)dst32 + 12, (const char *)src + 12, 4 );
    memcpy( (char *)dst32 + 16, (const char *)src + 16, 4 );
    memcpy( (char *)dst32 + 20, (const char *)src + 20, 4 );
    memcpy( (char *)dst32 + 24, (const char *)src + 24, 4 );
    *(unsigned int *)((char *)dst32 + 28) = (unsigned int)*(const unsigned long long *)((const char *)src + 32);
    memcpy( (char *)dst32 + 32, (const char *)src + 40, 4 );
    memcpy( (char *)dst32 + 36, (const char *)src + 44, 4 );
    memcpy( (char *)dst32 + 40, (const char *)src + 48, 4 );
    memcpy( (char *)dst32 + 44, (const char *)src + 52, 4 );
    memcpy( (char *)dst32 + 48, (const char *)src + 56, 4 );
    memcpy( (char *)dst32 + 52, (const char *)src + 60, 4 );
}

