/* GENERATED by ppc64le/audio/gen_winecom.py -- do not edit.
 *
 * Marshal tables for the wine-xaudio2_9 surface (8 interfaces, 115 vtable slots),
 * generated from ppc64le/audio/interfaces_xaudio2_9.json -- the same roster the guest
 * thunk module's .thunks file hands spec2thunk.  Interface order is
 * sorted by name, which is the order spec2thunk COM mode gives the
 * guest stub arrays; libs/winecom cross-checks every IID and slot
 * count at attach, so the two generators cannot silently disagree.
 *
 * Slot/iface types and WINECOM_CA_* classes come from
 * include/wine/winecom.h, which must be included before this file.
 */

enum xaudio2_iface_index
{
    XAUDIO2_IFACE_IXAudio2 = 0,
    XAUDIO2_IFACE_IXAudio2EngineCallback = 1,
    XAUDIO2_IFACE_IXAudio2Extension = 2,
    XAUDIO2_IFACE_IXAudio2MasteringVoice = 3,
    XAUDIO2_IFACE_IXAudio2SourceVoice = 4,
    XAUDIO2_IFACE_IXAudio2SubmixVoice = 5,
    XAUDIO2_IFACE_IXAudio2Voice = 6,
    XAUDIO2_IFACE_IXAudio2VoiceCallback = 7,
    XAUDIO2_IFACE_COUNT = 8
};

#define XAUDIO2_HAND_COUNT 8

#define XAUDIO2_SLOT_IXAudio2Voice_DestroyVoice 18

/* hand_funcs[] order in the client module:
 *   0 hand_create_source_voice
 *   1 hand_create_submix_voice
 *   2 hand_create_mastering_voice
 *   3 hand_set_output_voices
 *   4 hand_set_effect_chain
 *   5 hand_ffffff_i
 *   6 hand_fff_i
 *   7 hand_f_i
 */


static const unsigned char cls_IXAudio2_3[] = { WINECOM_CA_IFACE_IN };
static const unsigned char xaux_IXAudio2_3[] = { 1 };
static const unsigned char cls_IXAudio2_4[] = { WINECOM_CA_IFACE_IN };
static const unsigned char xaux_IXAudio2_4[] = { 1 };
static const struct winecom_slot slots_IXAudio2[13] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IXAudio2::RegisterForCallbacks", NULL, cls_IXAudio2_3, xaux_IXAudio2_3, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IXAudio2::UnregisterForCallbacks", NULL, cls_IXAudio2_4, xaux_IXAudio2_4, 2, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IXAudio2::CreateSourceVoice", NULL, NULL, NULL, 8, WINECOM_F_HAND, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2::CreateSubmixVoice", NULL, NULL, NULL, 8, WINECOM_F_HAND, 1, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2::CreateMasteringVoice", NULL, NULL, NULL, 8, WINECOM_F_HAND, 2, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2::StartEngine", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2::StopEngine", NULL, NULL, NULL, 1, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2::CommitChanges", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2::GetPerformanceData", NULL, NULL, NULL, 2, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2::SetDebugConfiguration", NULL, NULL, NULL, 3, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const struct winecom_slot slots_IXAudio2EngineCallback[3] =
{
    { "IXAudio2EngineCallback::OnProcessingPassStart", NULL, NULL, NULL, 1, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2EngineCallback::OnProcessingPassEnd", NULL, NULL, NULL, 1, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2EngineCallback::OnCriticalError", NULL, NULL, NULL, 2, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const struct winecom_slot slots_IXAudio2Extension[5] =
{
    { "IUnknown::QueryInterface", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::AddRef", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IUnknown::Release", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0, 0, 0 },  /* runtime */
    { "IXAudio2Extension::GetProcessingQuantum", NULL, NULL, NULL, 3, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Extension::GetProcessor", NULL, NULL, NULL, 2, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const unsigned char cls_IXAudio2MasteringVoice_10[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_PASS, WINECOM_CA_PASS };
static const unsigned char xaux_IXAudio2MasteringVoice_10[] = { 6, 0, 0 };
static const unsigned char cls_IXAudio2MasteringVoice_11[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_PASS };
static const unsigned char xaux_IXAudio2MasteringVoice_11[] = { 6, 0 };
static const unsigned char cls_IXAudio2MasteringVoice_16[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_PASS, WINECOM_CA_PASS, WINECOM_CA_PASS, WINECOM_CA_PASS };
static const unsigned char xaux_IXAudio2MasteringVoice_16[] = { 6, 0, 0, 0, 0 };
static const unsigned char cls_IXAudio2MasteringVoice_17[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_PASS, WINECOM_CA_PASS, WINECOM_CA_PASS };
static const unsigned char xaux_IXAudio2MasteringVoice_17[] = { 6, 0, 0, 0 };
static const struct winecom_slot slots_IXAudio2MasteringVoice[20] =
{
    { "IXAudio2Voice::GetVoiceDetails", NULL, NULL, NULL, 2, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetOutputVoices", NULL, NULL, NULL, 2, WINECOM_F_HAND, 3, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetEffectChain", NULL, NULL, NULL, 2, WINECOM_F_HAND, 4, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::EnableEffect", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::DisableEffect", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::GetEffectState", NULL, NULL, NULL, 3, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetEffectParameters", NULL, NULL, NULL, 5, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::GetEffectParameters", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetFilterParameters", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::GetFilterParameters", NULL, NULL, NULL, 2, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetOutputFilterParameters", NULL, cls_IXAudio2MasteringVoice_10, xaux_IXAudio2MasteringVoice_10, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IXAudio2Voice::GetOutputFilterParameters", NULL, cls_IXAudio2MasteringVoice_11, xaux_IXAudio2MasteringVoice_11, 3, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IXAudio2Voice::SetVolume", NULL, NULL, NULL, 3, WINECOM_F_HAND|WINECOM_F_REV, 7, 0, NULL, 0x01, 0x00, 0x00 },
    { "IXAudio2Voice::GetVolume", NULL, NULL, NULL, 2, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetChannelVolumes", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::GetChannelVolumes", NULL, NULL, NULL, 3, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetOutputMatrix", NULL, cls_IXAudio2MasteringVoice_16, xaux_IXAudio2MasteringVoice_16, 6, 0, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IXAudio2Voice::GetOutputMatrix", NULL, cls_IXAudio2MasteringVoice_17, xaux_IXAudio2MasteringVoice_17, 5, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IXAudio2Voice::DestroyVoice", NULL, NULL, NULL, 1, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2MasteringVoice::GetChannelMask", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const unsigned char cls_IXAudio2SourceVoice_10[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_PASS, WINECOM_CA_PASS };
static const unsigned char xaux_IXAudio2SourceVoice_10[] = { 6, 0, 0 };
static const unsigned char cls_IXAudio2SourceVoice_11[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_PASS };
static const unsigned char xaux_IXAudio2SourceVoice_11[] = { 6, 0 };
static const unsigned char cls_IXAudio2SourceVoice_16[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_PASS, WINECOM_CA_PASS, WINECOM_CA_PASS, WINECOM_CA_PASS };
static const unsigned char xaux_IXAudio2SourceVoice_16[] = { 6, 0, 0, 0, 0 };
static const unsigned char cls_IXAudio2SourceVoice_17[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_PASS, WINECOM_CA_PASS, WINECOM_CA_PASS };
static const unsigned char xaux_IXAudio2SourceVoice_17[] = { 6, 0, 0, 0 };
static const struct winecom_slot slots_IXAudio2SourceVoice[29] =
{
    { "IXAudio2Voice::GetVoiceDetails", NULL, NULL, NULL, 2, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetOutputVoices", NULL, NULL, NULL, 2, WINECOM_F_HAND, 3, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetEffectChain", NULL, NULL, NULL, 2, WINECOM_F_HAND, 4, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::EnableEffect", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::DisableEffect", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::GetEffectState", NULL, NULL, NULL, 3, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetEffectParameters", NULL, NULL, NULL, 5, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::GetEffectParameters", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetFilterParameters", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::GetFilterParameters", NULL, NULL, NULL, 2, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetOutputFilterParameters", NULL, cls_IXAudio2SourceVoice_10, xaux_IXAudio2SourceVoice_10, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IXAudio2Voice::GetOutputFilterParameters", NULL, cls_IXAudio2SourceVoice_11, xaux_IXAudio2SourceVoice_11, 3, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IXAudio2Voice::SetVolume", NULL, NULL, NULL, 3, WINECOM_F_HAND|WINECOM_F_REV, 7, 0, NULL, 0x01, 0x00, 0x00 },
    { "IXAudio2Voice::GetVolume", NULL, NULL, NULL, 2, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetChannelVolumes", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::GetChannelVolumes", NULL, NULL, NULL, 3, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetOutputMatrix", NULL, cls_IXAudio2SourceVoice_16, xaux_IXAudio2SourceVoice_16, 6, 0, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IXAudio2Voice::GetOutputMatrix", NULL, cls_IXAudio2SourceVoice_17, xaux_IXAudio2SourceVoice_17, 5, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IXAudio2Voice::DestroyVoice", NULL, NULL, NULL, 1, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2SourceVoice::Start", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2SourceVoice::Stop", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2SourceVoice::SubmitSourceBuffer", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2SourceVoice::FlushSourceBuffers", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2SourceVoice::Discontinuity", NULL, NULL, NULL, 1, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2SourceVoice::ExitLoop", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2SourceVoice::GetState", NULL, NULL, NULL, 3, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2SourceVoice::SetFrequencyRatio", NULL, NULL, NULL, 3, WINECOM_F_HAND|WINECOM_F_REV, 7, 0, NULL, 0x01, 0x00, 0x00 },
    { "IXAudio2SourceVoice::GetFrequencyRatio", NULL, NULL, NULL, 2, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2SourceVoice::SetSourceSampleRate", NULL, NULL, NULL, 2, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const unsigned char cls_IXAudio2SubmixVoice_10[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_PASS, WINECOM_CA_PASS };
static const unsigned char xaux_IXAudio2SubmixVoice_10[] = { 6, 0, 0 };
static const unsigned char cls_IXAudio2SubmixVoice_11[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_PASS };
static const unsigned char xaux_IXAudio2SubmixVoice_11[] = { 6, 0 };
static const unsigned char cls_IXAudio2SubmixVoice_16[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_PASS, WINECOM_CA_PASS, WINECOM_CA_PASS, WINECOM_CA_PASS };
static const unsigned char xaux_IXAudio2SubmixVoice_16[] = { 6, 0, 0, 0, 0 };
static const unsigned char cls_IXAudio2SubmixVoice_17[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_PASS, WINECOM_CA_PASS, WINECOM_CA_PASS };
static const unsigned char xaux_IXAudio2SubmixVoice_17[] = { 6, 0, 0, 0 };
static const struct winecom_slot slots_IXAudio2SubmixVoice[19] =
{
    { "IXAudio2Voice::GetVoiceDetails", NULL, NULL, NULL, 2, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetOutputVoices", NULL, NULL, NULL, 2, WINECOM_F_HAND, 3, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetEffectChain", NULL, NULL, NULL, 2, WINECOM_F_HAND, 4, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::EnableEffect", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::DisableEffect", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::GetEffectState", NULL, NULL, NULL, 3, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetEffectParameters", NULL, NULL, NULL, 5, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::GetEffectParameters", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetFilterParameters", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::GetFilterParameters", NULL, NULL, NULL, 2, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetOutputFilterParameters", NULL, cls_IXAudio2SubmixVoice_10, xaux_IXAudio2SubmixVoice_10, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IXAudio2Voice::GetOutputFilterParameters", NULL, cls_IXAudio2SubmixVoice_11, xaux_IXAudio2SubmixVoice_11, 3, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IXAudio2Voice::SetVolume", NULL, NULL, NULL, 3, WINECOM_F_HAND|WINECOM_F_REV, 7, 0, NULL, 0x01, 0x00, 0x00 },
    { "IXAudio2Voice::GetVolume", NULL, NULL, NULL, 2, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetChannelVolumes", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::GetChannelVolumes", NULL, NULL, NULL, 3, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetOutputMatrix", NULL, cls_IXAudio2SubmixVoice_16, xaux_IXAudio2SubmixVoice_16, 6, 0, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IXAudio2Voice::GetOutputMatrix", NULL, cls_IXAudio2SubmixVoice_17, xaux_IXAudio2SubmixVoice_17, 5, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IXAudio2Voice::DestroyVoice", NULL, NULL, NULL, 1, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const unsigned char cls_IXAudio2Voice_10[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_PASS, WINECOM_CA_PASS };
static const unsigned char xaux_IXAudio2Voice_10[] = { 6, 0, 0 };
static const unsigned char cls_IXAudio2Voice_11[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_PASS };
static const unsigned char xaux_IXAudio2Voice_11[] = { 6, 0 };
static const unsigned char cls_IXAudio2Voice_16[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_PASS, WINECOM_CA_PASS, WINECOM_CA_PASS, WINECOM_CA_PASS };
static const unsigned char xaux_IXAudio2Voice_16[] = { 6, 0, 0, 0, 0 };
static const unsigned char cls_IXAudio2Voice_17[] = { WINECOM_CA_IFACE_IN, WINECOM_CA_PASS, WINECOM_CA_PASS, WINECOM_CA_PASS };
static const unsigned char xaux_IXAudio2Voice_17[] = { 6, 0, 0, 0 };
static const struct winecom_slot slots_IXAudio2Voice[19] =
{
    { "IXAudio2Voice::GetVoiceDetails", NULL, NULL, NULL, 2, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetOutputVoices", NULL, NULL, NULL, 2, WINECOM_F_HAND, 3, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetEffectChain", NULL, NULL, NULL, 2, WINECOM_F_HAND, 4, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::EnableEffect", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::DisableEffect", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::GetEffectState", NULL, NULL, NULL, 3, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetEffectParameters", NULL, NULL, NULL, 5, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::GetEffectParameters", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetFilterParameters", NULL, NULL, NULL, 3, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::GetFilterParameters", NULL, NULL, NULL, 2, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetOutputFilterParameters", NULL, cls_IXAudio2Voice_10, xaux_IXAudio2Voice_10, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IXAudio2Voice::GetOutputFilterParameters", NULL, cls_IXAudio2Voice_11, xaux_IXAudio2Voice_11, 3, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IXAudio2Voice::SetVolume", NULL, NULL, NULL, 3, WINECOM_F_HAND|WINECOM_F_REV, 7, 0, NULL, 0x01, 0x00, 0x00 },
    { "IXAudio2Voice::GetVolume", NULL, NULL, NULL, 2, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetChannelVolumes", NULL, NULL, NULL, 4, 0, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::GetChannelVolumes", NULL, NULL, NULL, 3, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2Voice::SetOutputMatrix", NULL, cls_IXAudio2Voice_16, xaux_IXAudio2Voice_16, 6, 0, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IXAudio2Voice::GetOutputMatrix", NULL, cls_IXAudio2Voice_17, xaux_IXAudio2Voice_17, 5, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x01 },
    { "IXAudio2Voice::DestroyVoice", NULL, NULL, NULL, 1, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const struct winecom_slot slots_IXAudio2VoiceCallback[7] =
{
    { "IXAudio2VoiceCallback::OnVoiceProcessingPassStart", NULL, NULL, NULL, 2, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2VoiceCallback::OnVoiceProcessingPassEnd", NULL, NULL, NULL, 1, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2VoiceCallback::OnStreamEnd", NULL, NULL, NULL, 1, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2VoiceCallback::OnBufferStart", NULL, NULL, NULL, 2, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2VoiceCallback::OnBufferEnd", NULL, NULL, NULL, 2, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2VoiceCallback::OnLoopEnd", NULL, NULL, NULL, 2, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
    { "IXAudio2VoiceCallback::OnVoiceError", NULL, NULL, NULL, 3, WINECOM_F_RET_VOID, 0, 0, NULL, 0x00, 0x00, 0x00 },
};

static const struct winecom_iface xaudio2_com_ifaces[XAUDIO2_IFACE_COUNT] =
{
    { "IXAudio2", {0x2b02e3cf,0x2e0b,0x4ec3,{0xbe,0x45,0x1b,0x2a,0x3f,0xe7,0x21,0x0d}},
      13, slots_IXAudio2, 0 },
    { "IXAudio2EngineCallback", {0xe052c39d,0xed73,0x58c6,{0xac,0xd9,0x76,0x0e,0x2c,0x8f,0x79,0x68}},
      3, slots_IXAudio2EngineCallback, WINECOM_IF_LOCAL },
    { "IXAudio2Extension", {0x84ac29bb,0xd619,0x44d2,{0xb1,0x97,0xe4,0xac,0xf7,0xdf,0x3e,0xd6}},
      5, slots_IXAudio2Extension, 0 },
    { "IXAudio2MasteringVoice", {0x359298ea,0xdc9b,0x572f,{0x82,0xc6,0xcf,0xd2,0x05,0x11,0xf2,0x15}},
      20, slots_IXAudio2MasteringVoice, WINECOM_IF_LOCAL },
    { "IXAudio2SourceVoice", {0xe8116f61,0xbcd1,0x5163,{0x8e,0x67,0xf6,0x84,0x4b,0x28,0xf3,0x7e}},
      29, slots_IXAudio2SourceVoice, WINECOM_IF_LOCAL },
    { "IXAudio2SubmixVoice", {0x735f90fc,0xf8c2,0x5c07,{0x9c,0xb0,0x67,0xd0,0x6f,0xe8,0x28,0x27}},
      19, slots_IXAudio2SubmixVoice, WINECOM_IF_LOCAL },
    { "IXAudio2Voice", {0x76c75fa9,0x5832,0x597c,{0x96,0xae,0x87,0x30,0xae,0x5f,0xab,0x3d}},
      19, slots_IXAudio2Voice, WINECOM_IF_LOCAL },
    { "IXAudio2VoiceCallback", {0x19dec719,0x686c,0x5835,{0x9b,0xe0,0x6a,0x1b,0x6c,0x9a,0x02,0x9a}},
      7, slots_IXAudio2VoiceCallback, WINECOM_IF_LOCAL },
};

/* Interfaces that are NOT IUnknown-derived: slot 0 is a real method, not
 * QueryInterface.  libs/winecom's dispatcher serves slots 0..2 from the proxy
 * table for every interface it is given, so the client's __wine_com_dispatch
 * MUST test this array and serve these itself before delegating. */
static const unsigned char xaudio2_iface_local[XAUDIO2_IFACE_COUNT] =
{
    0,  /* IXAudio2 */
    1,  /* IXAudio2EngineCallback */
    0,  /* IXAudio2Extension */
    1,  /* IXAudio2MasteringVoice */
    1,  /* IXAudio2SourceVoice */
    1,  /* IXAudio2SubmixVoice */
    1,  /* IXAudio2Voice */
    1,  /* IXAudio2VoiceCallback */
};

/* 93 slot(s) marshalled, 16 hand-written (5 of them float-bearing,
 * routed by argument shape), 0 refused with a named reason, 6
 * IUnknown slot(s) served by the runtime; 3 interface(s) carry
 * only CA_PASS rows, 6 are [local] and served by the client. */
