/*
 * import_chain_probe.c -- the RUNTIME leg of check-import-chain.sh.
 *
 * The static leg proves every import of a third-party guest DLL has a real
 * export behind it.  This proves the loader agrees: the module actually LOADS
 * as a guest, its DllMain runs to completion, and GetProcAddress hands back
 * callable addresses.  A static answer alone cannot see a DllMain that faults
 * on a sentinel, which is exactly how DOOM's chain failed.
 *
 * Built for x86_64-windows and run as a GUEST.  No CRT: the only imports are
 * the six kernel32 entry points below, so nothing but the subject under test
 * is being exercised.
 *
 * probe_names.h is generated by the gate and defines:
 *   PROBE_DLL        the subject's file name
 *   PROBE_ORDINALS   a comma-separated list of live export ordinals
 *   PROBE_NAMED_DLL  (optional) a second subject fetched BY NAME
 *   PROBE_NAMES      (optional) its export names, as string literals
 */

#include <windows.h>
#include "probe_names.h"

static void put( const char *s )
{
    DWORD n = 0, w;
    const char *p = s;
    while (*p++) n++;
    WriteFile( GetStdHandle( STD_OUTPUT_HANDLE ), s, n, &w, NULL );
}

static void putnum( ULONG v )
{
    char b[12];
    int i = 11;
    b[i] = 0;
    if (!v) b[--i] = '0';
    while (v) { b[--i] = (char)('0' + v % 10); v /= 10; }
    put( b + i );
}

static int fails;

static void expect( int ok, const char *what )
{
    put( ok ? "  ok    " : "  FAIL  " );
    put( what );
    put( "\n" );
    if (!ok) fails++;
}

void probe_entry(void)
{
    static const WORD ordinals[] = { PROBE_ORDINALS };
    HMODULE h;
    unsigned i;

    put( "import-chain-probe: subject " PROBE_DLL "\n" );

    h = LoadLibraryA( PROBE_DLL );
    expect( h != NULL, "LoadLibraryA(" PROBE_DLL ")" );
    if (!h)
    {
        /* Nothing below can mean anything without the module.  Say so and
         * leave, rather than reporting a cascade of derived failures. */
        put( "import-chain-probe: FAIL (subject did not load)\n" );
        ExitProcess( 1 );
    }

    for (i = 0; i < sizeof(ordinals) / sizeof(ordinals[0]); i++)
    {
        void *p = (void *)GetProcAddress( h, (const char *)(ULONG_PTR)ordinals[i] );
        put( p ? "  ok    ordinal " : "  FAIL  ordinal " );
        putnum( ordinals[i] );
        put( "\n" );
        if (!p) fails++;
    }

#ifdef PROBE_NAMED_DLL
    {
        static const char * const names[] = { PROBE_NAMES };
        HMODULE n = LoadLibraryA( PROBE_NAMED_DLL );
        expect( n != NULL, "LoadLibraryA(" PROBE_NAMED_DLL ")" );
        if (n)
        {
            for (i = 0; i < sizeof(names) / sizeof(names[0]); i++)
            {
                void *p = (void *)GetProcAddress( n, names[i] );
                put( p ? "  ok    " : "  FAIL  " );
                put( names[i] );
                put( "\n" );
                if (!p) fails++;
            }
        }
    }
#endif

    put( fails ? "import-chain-probe: FAIL\n" : "import-chain-probe: PASS\n" );
    ExitProcess( fails ? 1 : 0 );
}
